### ISSUE TITLE
Test interoperability with Helia and remove dependency on ipfs/interop

### ISSUE THREAD

**Issue by BigLep** [ipfs/kubo#10013]
## Done Criteria
1. Kubo no longer relies on https://github.com/ipfs/interop for interoperability testing
2. Kubo CI checks to ensure it doesn't break compatibility with Helia
3. https://github.com/ipfs/interop is archived

## Why Important
We don't have Helia interoperability testing.
Relying on js-ipfs testing is keeping things like mplex around even though it should be deprecated: https://github.com/ipfs/kubo/issues/9958

## Notes
https://github.com/ipfs/interop is testing js-ipfs/js-ipfs, js-ipfs/kubo, and kubo/kubo.
js-ipfs is deprecated: https://github.com/ipfs/js-ipfs/issues/4336
We're not covering Kubo/Helia in the Kubo CI.
Kubo tests cover the Kubo/Kubo case better. 

Ideally, we run https://github.com/ipfs/helia/tree/main/packages/interop as part of Kubo CI and configure it to test the latest blessed Helia release against any PR's against Kubo master/main.

**Comment by Jorropo** [comment]
:+1: thx, we should also archive `ipfs/interop`
