### ISSUE TITLE
bash: ipfs: command not found

### ISSUE THREAD

**Issue by 0xdopeman** [ipfs/kubo#10023]
I sucesfully installed IPFS Kubo but when i ran the command ipfs init on gitbash and powershell the result is bash: ipfs: command not found
![image](https://github.com/ipfs/ipfs-desktop/assets/47253573/e7232d03-1b08-4a62-9e5a-402e02476149)
![image](https://github.com/ipfs/ipfs-desktop/assets/47253573/c61168a6-ac93-420e-a60c-1bd81ed4b6b7)

**Comment by SgtPooki** [comment]
@rereyfaruq you may want to reach out on slack/discord/discuss.ipfs.tech for assistance because this should be resolve-able without any code changes to Kubo.

**Comment by gammazero** [comment]
Closing: This is an environment/path issue.
