### ISSUE TITLE
Exec format error when building from source from docker image

### ISSUE THREAD

**Issue by deavmi** [ipfs/kubo#10038]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

built from source

### Version

```Text
Can't give you this if it won't build in the first place.
```

### Config

```json
See above.
```

### Description

Trying to build using the official provided image of [this](https://hub.docker.com/r/ipfs/kubo) on `Linux dockerHost 6.2.0-1009-raspi #11-Ubuntu SMP PREEMPT Mon Jul 17 10:19:57 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux` but it seems that the `tini` gives me `exec format error`:

I just get this spewed in the logs:

```
exec /sbin/tini: exec format error

exec /sbin/tini: exec format error

exec /sbin/tini: exec format error

exec /sbin/tini: exec format error

exec /sbin/tini: exec format error

exec /sbin/tini: exec format error

exec /sbin/tini: exec format error

exec /sbin/tini: exec format error

exec /sbin/tini: exec format error

exec /sbin/tini: exec format error

exec /sbin/tini: exec format error
```

I have spent the whole day searching but nothing has worked yet.

**Comment by TheColorman** [comment]
+1

**Comment by TheColorman** [comment]
Seems to be handled my #9901 (see https://github.com/ipfs/kubo/issues/9901#issuecomment-1654141632)

**Comment by deavmi** [comment]
Thanks!

**Comment by Kiggins26** [comment]
Should this issue not be closed?

**Comment by deavmi** [comment]
Yes, all good
