### ISSUE TITLE
Stop running split DHTs routing table for client and server when not using the accelerated DHT client

### ISSUE THREAD

**Issue by Jorropo** [ipfs/kubo#10076]
This has no known benefits today (cc @guillaumemichel correct ?) given they run the same bucket refresh code, poisoning one or the other is not particularly harder or anything, ~~the requirements on the bucket health for answering server and client roles is identical.~~ \*the bar for a successful client is much lower, in theory 1 healthy peer is enough to bootstrap any DHT query, however having healthy buckets accelerate requests by allowing to skip some DHT steps, you could do something smarter for the client by selecting nodes uniformly in the keyspace but we don't do that and the benefits are not crazy.
Having a shared routing table save resources, less memory usage and cut in half the number of network requests we send to outbound peers while doing refreshes.

**Comment by guillaumemichel** [comment]
That is correct! The DHT Client and Server should share the same routing table (as long as they use the same `peer.ID`).

Technically, if a Kubo node is in DHT Client mode it wouldn't even need to maintain Kademlia _buckets_. As long as the Kubo node keeps advertising its peer record at the right location in the DHT, the Kubo node's routing table should cache peers that are uniformly distributed across the keyspace.

**Comment by Jorropo** [comment]
thx,
We can always revist this in the future, currently having buckets for the client accelerate queries, a smarter thing could be done but we don't do it right now.

**Comment by Jorropo** [comment]
Yeah so we don't do that, it looks like we do because `ipfs stats dht --help` list both wan and wanserver, there exists a field named client and server in the struct, but we set both to the same dht instance.
