### ISSUE TITLE
HTTP API equivalent with ipfs add -r command?

### ISSUE THREAD

**Issue by bip39org** [ipfs/kubo#10079]
### Checklist

- [X] I am reporting a documentation issue in this repo, not https://docs.ipfs.tech.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

Hello,

I could not find the proper documentation for adding a directory recursively ( Equivalent with `ipfs add -r` ).

How should I add those via the HTTP API?

Thanks.

**Comment by hacdias** [comment]
Hello @bip39org, you can find the documentation on how to upload recursively through the HTTP API here: https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-add - You'll have to send a multipart request with information regarding each file and directory.

Doing it manually can be laborious. I would recommend using one the clients: https://github.com/ipfs/kubo/blob/master/docs/http-rpc-clients.md

Let me know if that helped

**Comment by bip39org** [comment]
Hello @hacdias, thank you for your reply.

For the clarification, could you give me any examples for the multipart requests?

Maybe adding it to the docs would be helpful for users like myself.

Thanks.

**Comment by hacdias** [comment]
@bip39org there is an example on the linked page.

> Directory parts have a special content type application/x-directory. These parts do not carry any data. The part headers look as follows:
> 
> ```
> Content-Disposition: form-data; name="file"; filename="folderName"
> Content-Type: application/x-directory
> ```
> 
> File parts carry the file payload after the following headers:
> 
> ```
> Abspath: /absolute/path/to/file.txt
> Content-Disposition: form-data; name="file"; filename="folderName%2Ffile.txt"
> Content-Type: application/octet-stream
> 
> ...contents...
> ```
> 
> The above file includes its path in the "folderName/file.txt" hierarchy and IPFS will therefore be able to add it inside "folderName". The parts declaring the directories are optional when they have files inside and will be inferred from the filenames. In any case, a depth-first traversal of the directory tree is recommended to order the different parts making the request.

**Comment by hacdias** [comment]
@bip39org there is an example on the linked page:

> Directory parts have a special content type application/x-directory. These parts do not carry any data. The part headers look as follows:
> 
> ```
> Content-Disposition: form-data; name="file"; filename="folderName"
> Content-Type: application/x-directory
> ```
> 
> File parts carry the file payload after the following headers:
> 
> ```
> Abspath: /absolute/path/to/file.txt
> Content-Disposition: form-data; name="file"; filename="folderName%2Ffile.txt"
> Content-Type: application/octet-stream
> 
> ...contents...
> ```
> 
> The above file includes its path in the "folderName/file.txt" hierarchy and IPFS will therefore be able to add it inside "folderName". The parts declaring the directories are optional when they have files inside and will be inferred from the filenames. In any case, a depth-first traversal of the directory tree is recommended to order the different parts making the request.

So... you can send a folder `folderName` with a file `file.txt` containing `Hello, World!` as follows (with cURL):

```
curl -H "Content-Type: multipart/form-data; boundary=XXX" -X POST http://127.0.0.1:5001/api/v0/add --data-binary @- <<EOF
--XXX
Content-Disposition: form-data; name="file"; filename="folderName"
Content-Type: application/x-directory

--XXX
Abspath: /absolute/path/to/file.txt
Content-Disposition: form-data; name="file"; filename="folderName%2Ffile.txt"
Content-Type: application/octet-stream

Hello, World!
--XXX--
EOF
```

That will output:

```
{"Name":"folderName/file.txt","Hash":"QmZoBFCYa4gJRYhpKuVWXon461apqQYKb7FUqS2h9HPM3e","Size":"21"}
{"Name":"folderName","Hash":"QmRxn5DfZwvc2H26rb8c7N6TTStrkneZSQNvGVBNNbjt7Y","Size":"75"}
```

**Comment by bip39org** [comment]
Ah that will do the work thanks!
