### ISSUE TITLE
Kubo Release v0.22.1

### ISSUE THREAD

**Issue by Jorropo** [ipfs/kubo#10074]
*Tentative, not decided yet*

Things to include:
- [ ] #10064 
- [x] bump https://github.com/libp2p/go-libp2p-kad-dht/pull/866
  - [ ] https://github.com/ipfs/kubo/pull/10086
- [ ] (Bug not yet pin pointed), fixes for https://filecoinproject.slack.com/archives/C03KF8VCHV4/p1692116752256399
- [ ] https://github.com/ipfs/boxo/issues/432

**Comment by marten-seemann** [comment]
> [ ] [Support go1.21.0 #10064](https://github.com/ipfs/kubo/issues/10064)

This won't be possible without updating to go-libp2p v0.30.0, which according to semver is out of scope for a patch release.

**Comment by Jorropo** [comment]
https://github.com/ipfs/boxo/issues/432's fix is wrong and needs to be reverted, the fix wont be as-easy.

I found a bug in `go-libp2p-routing-handlers`, given the new work adding up I think we will just go with v0.23.0.
