### ISSUE TITLE
Is there any updated documentation for using ipfs kubo with go codes?

### ISSUE THREAD

**Issue by unicornlox** [ipfs/kubo#10096]
### Checklist

- [X] I am reporting a documentation issue in this repo, not https://docs.ipfs.tech.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

hi, i want to use kubo with go language, but when i read the ipfs and kubo documentation and follow the links there, i see that old packages that are no longer used are described, and while some packages are no longer used, i could not find a document that tells me how to use them in new packages. where can i learn how to use kubo with go language?
```[tasklist]
### Tasks
```

**Comment by lidel** [comment]
Thank you for filling this @unicornlox, we are in the process of extracting parts of Kubo into Boxo, and indeed some docs may be outdated.

What is the use case you are trying to solve? 
Which docs you tried to read but gave up? 
The feedback here will be very useful to make our docs and examples better :pray: 

For now, quick pointers:

- Use Kubo RPC from GO code? 
  - Use the RPC client library from  `kubo/client/rpc`
    - see the example in https://github.com/ipfs/kubo/tree/master/client/rpc#readme
    - and docs at https://pkg.go.dev/github.com/ipfs/kubo/client/rpc 
  - (`go-ipfs-api` and `go-ipfs-http-client` still work, but are no longer maintained and are being deprecated, as noted in https://github.com/ipfs/kubo/issues/9124)
- Write a Kubo plugin (e.g. a custom datastore)?  
  - https://github.com/ipfs/kubo/blob/master/docs/plugins.md should be up-to-date
- Create light IPFS node without the complexity of Kuboi? 
   - some useful things are already in https://github.com/ipfs/boxo (let us know if anything is missing for your use case, or what type of docs would help :pray: )
