### ISSUE TITLE
remove mplex

### ISSUE THREAD

**Issue by marten-seemann** [ipfs/kubo#10090]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

[go-libp2p v0.30.0 ](https://github.com/libp2p/go-libp2p/releases/tag/v0.30.0) dropped mplex support. I'm surprised to see that the mplex support was re-added with little discussion on the original issue: https://github.com/ipfs/kubo/issues/9958.

Dropping mplex will be a prerequisite for updating go-libp2p, unless Kubo wants to copy-paste the now deleted mplex package (see https://github.com/libp2p/go-libp2p/pull/2498 for discussion).

**Comment by Jorropo** [comment]
https://github.com/ipfs/kubo/issues/10069
