### ISSUE TITLE
IPFS mount to Kubo running on docker

### ISSUE THREAD

**Issue by viniciusd** [ipfs/kubo#10107]
### Checklist

- [X] I am reporting a documentation issue in this repo, not https://docs.ipfs.tech.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Location

https://github.com/ipfs/kubo/blob/master/docs/fuse.md

### Description

The documentation describes how one can use the FUSE interface to mount IPFS using Kubo.

But is it possible to mount it in the host machine when Kubo is running on Docker? I see no mention on that. It only states how one should do `ipfs daemon --mount`, but I have the daemon running on Docker and my ipfs cli connects to it from the host machine.

**Comment by lidel** [comment]
This is goes against the idea of containerization (where you mount things from outside INTO container, and not the other way around :).  But in practice, you could mount some external directory `/foo-out`  into `/foo-in` the container, and then have Kubo running inside of the container mount FUSE at `/foo-in/ipfs` and then (assuming filesystem permissions are aligned) you might see `/foo-out/ipfs` outside (did not test this, just a loose idea). 

ps. in the future, ask support questions for power user setups like this in https://discuss.ipfs.tech/c/help/13 :pray:
