### ISSUE TITLE
IPNS Name republishing does not appear to be working (with Accelerated DHT and Optimistic Provide)

### ISSUE THREAD

**Issue by Rashkae2** [ipfs/kubo#10111]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.tech

### Version

```Text
Kubo version: 0.22.0
Repo version: 14
System version: amd64/linux
Golang version: go1.19.12
```

### Config

```json
{
  "API": {
    "HTTPHeaders": {
      "Access-Control-Allow-Methods": [
        "PUT",
        "POST"
      ],
      "Access-Control-Allow-Origin": [
        "http://10.0.0.10:5001",
        "http://localhost:3000",
        "http://127.0.0.1:5001",
        "https://webui.ipfs.io"
      ]
    }
  },
  "Addresses": {
    "API": "/ip4/0.0.0.0/tcp/5001",
    "Announce": [],
    "AppendAnnounce": [],
    "Gateway": "/ip4/0.0.0.0/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic",
      "/ip4/0.0.0.0/udp/4001/quic-v1",
      "/ip4/0.0.0.0/udp/4001/quic-v1/webtransport",
      "/ip6/::/udp/4001/quic",
      "/ip6/::/udp/4001/quic-v1",
      "/ip6/::/udp/4001/quic-v1/webtransport"
    ]
  },
  "AutoNAT": {},
  "Bootstrap": [
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
    "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.131.131.82/udp/4001/quic/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ"
  ],
  "DNS": {
    "Resolvers": {}
  },
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "10GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true
    }
  },
  "Experimental": {
    "FilestoreEnabled": true,
    "GraphsyncEnabled": false,
    "Libp2pStreamMounting": false,
    "OptimisticProvide": true,
    "OptimisticProvideJobsPoolSize": 300,
    "P2pHttpProxy": false,
    "StrategicProviding": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "DeserializedResponses": null,
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": false,
    "PathPrefixes": [],
    "PublicGateways": null,
    "RootRedirect": ""
  },
  "Identity": {
    "PeerID": "12D3KooWG2qoPwip8t5LGa7fmRoRaX2TPBAxHiXTC5iJVmxij4oh"
  },
  "Internal": {},
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Migration": {
    "DownloadSources": [],
    "Keep": ""
  },
  "Mounts": {
    "FuseAllowOther": true,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Peering": {
    "Peers": null
  },
  "Pinning": {
    "RemoteServices": {}
  },
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {
    "Strategy": "all"
  },
  "Routing": {
    "AcceleratedDHTClient": true,
    "Methods": null,
    "Routers": null
  },
  "Swarm": {
    "AddrFilters": null,
    "ConnMgr": {},
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "RelayClient": {},
    "RelayService": {},
    "ResourceMgr": {
      "Limits": {}
    },
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  }
}
```

### Description

I am publishing a few CID's with IPNS from this node:  Example: k51qzi5uqu5dkhxkgaqzgjtb266p3clrbqdwekfp8vmxv2v6obuq0wlzdtudqc

This seems to work. However, after 24 hours, other nodes (on a different vm) start loosing the ability to resolve this address 

(ipfs name resolve /ipns/k51qzi5uqu5dkhxkgaqzgjtb266p3clrbqdwekfp8vmxv2v6obuq0wlzdtudqc  will return an error that is is unable to resolve the address.  Unfortunately, copy the exact error before getting it working again.)

Not all nodes are affected equally... 1 node might be able to still resolve the name(s)... while another node can not.  Eventually, the only way to get it working again is to republish the CID.. (in my simple method, I am using the WebUI and choosing the "Publish to IPNS" from the files tab.).  After which, the nodes that were unable to resolve the name start working immediately, (for the next 24 to 48 hours)

Nodes that are unable to resolve the name are able to find the related CIDs (ipfs dht findprov CID) without fail.

I did not realize until I started writing this report that I had left OptimisticProvide turned on.  I know that interfered with IPNS Name publish when it was first introduced.  I will try to reproduce with this option turned off.

**Comment by Rashkae2** [comment]
The same thing happened with OptimisticProvide turned off.  Approx 20 hours after I manually published records to IPNS, the V.0.21 ipfs node included with web browser can not longer resolve those ipns keys.  (The 0.22 IPFS Desktop node still works.)  

I will re-test with an explicitely defined 2h ipns.republishPeriod.

**Comment by Jorropo** [comment]
Just so you know, Optimistic Provide is incompatible with the Accelerated DHT Client, the flag does nothing then. So this is very likely not related.

**Comment by Rashkae2** [comment]
I thought I would work around this by publishing my ipns keys in a bash script on a 2 hour cron job.  This appears to work, 

From command: 
/usr/local/bin/ipfs name publish --key="Twitch Streams" \
    /ipfs/QmWboV6dd75m4taYLynpkjPW8upTknKWfvemyw3SQzSUds

I get output:

Published to k51qzi5uqu5dkhxkgaqzgjtb266p3clrbqdwekfp8vmxv2v6obuq0wlzdtudqc: /ipfs/QmWboV6dd75m4taYLynpkjPW8upTknKWfvemyw3SQzSUds

However, the Kudo v 0.21 embedded in Brave Browser does not pick up the new CID, even after the script has run 3 times over the past 6 hours.  (it works with Kubo 0.22 included with IPFS Desktop.)  I'm confident from previous experience that if I publish the CID to IPNS through the WebUI, the change will be detected immediately.  I can only surmise that publishing a CID to IPNS through the WebUI is doing /something/ that the ipfs name publish command is *not* doing.

**Comment by Rashkae2** [comment]
Publishing my IPNS keys via command line script on a scheduler definitively solved any practical issues I had.  But there is a question that this might have been my mis-understanding.  Is there any mechanism of persistence for IPNS publishing between sessions?  I can't find a way to list or show the associations between IPNS keys and IPFS Address.  If these  commands need to be issued every time the deamon starts, that would explain what I was seeing and this should be moved from bug report to feature request.

**Comment by maxkaneco** [comment]
We observed a similar issue (not sure if related through). We are publishing IPNS records using version 21. It can be resolved by version 21 without issue. For example, "./ipfs resolve -r /ipns/k51qzi5uqu5dj2va4ha12r6n9rsa4juckz05ut21q3k2xqi1t4" is resolved to /ipfs/QmZbZPWX7pBnJBRjh2LkGMo4Fx9NcyLp8Cc8pe2NZGoxuW as of now. But version 22 reports error saying invalid path. Looks like what it gets is missing a "/ipfs" prefix.

**Comment by aschmahmann** [comment]
@maxkaneco a few questions:
1. Can you give an example IPNS ID where this happens? (the one you have `k51...t4` is incomplete/was cut off)
2. Can you try with the latest kubo and see if that works?
3. Can you post the IPNS record for your identifier (base encoded if that's easier for you)? You can get the record bytes with `ipfs routing get /ipns/<my-id>`.
