### ISSUE TITLE
Reenable libp2p smart dialer

### ISSUE THREAD

**Issue by Jorropo** [ipfs/kubo#10138]
Since we havn't updated to go-libp2p-kad-dht v0.25.1 yet we don't properly filter addresses by the DHT, this cause use to find plenty of local addresses which fancy new libp2p prioritize first.
Instead we go back to the all spamming code where we try everything in parallel, this is not nice but we need to update to go-libp2p-kad-dht to v0.25.1 and fix all the tests that are breaking because of that.

**Comment by sukunrt** [comment]
>this cause use to find plenty of local addresses which fancy new libp2p prioritize first.

Smart dialing should dial local addresses in parallel with the public addresses, not prioritise local/private addresses over public ones. So this should have no impact.

**Comment by Jorropo** [comment]
Ohhhhhhhhh well good
