### ISSUE TITLE
Help of add command confusing when running offline

### ISSUE THREAD

**Issue by stolab** [ipfs/kubo#10208]
### Checklist

- [X] I am reporting a documentation issue in this repo, not https://docs.ipfs.tech.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

I was playing with kubo/ipfs in offline mode (ie without running any daemon).

When you run the help for the add command `ipfs add --help` it says the following about the offline mode:

>  If the daemon is not running, it will just add locally.

However when adding a dummy file (`ipfs add my-file`), I was surprise to be able to retrieve it using `curl https://ipfs.io/ipfs/<CID>`. To my understanding it should have been only available locally and not online.

Then when continuing reading the help page, it says the following :

> Files imported with 'ipfs add' are protected from GC (implicit '--pin=true')

Which, if I correctly understand, mean that, by default, your file is globally available.

So to me it feel like it's a bit contradictory here. On one side it says that it will only be added locally if the daemon is not running and on the other side it says that `--pin` is true by default.

Did I misunderstood something here ?

**Comment by KiritoCyanPine** [comment]
Files added with `ipfs add` are implicitly pinned.
This generally means that the file is retained in your repository and the garbage collector is not eligible to remove it.

The `pin` status does not indicate the availability of content globally, It indicates if the content should be kept available on a specific device/repository.

**Comment by stolab** [comment]
Hey @KiritoCyanPine, yes indeed thanks for your explanation of the `pin` I was indeed a bit confused about it.

However it does not change the part where my file is available globally even if I'm not running in daemon mode.... Is there any explanation for that?

To my understanding I should not be able to retrieve my file using `curl https://ipfs.io/ipfs/<CID>` in that case

**Comment by stolab** [comment]
Never mind actually the explanation is extremely stupid.....

My test was on a very basic file (`echo "this is a test" > test.txt`). This very basic file has probably been uploaded by someone else at some point and that's why this is available globally.

If you try with a file which have a bigger probability of never been uploaded by anybody, you don't face this issue.
