### ISSUE TITLE
Incorrect repo size reported by `repo stat`

### ISSUE THREAD

**Issue by SmaugPool** [ipfs/kubo#10252]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.tech

### Version

```Text
Kubo version: 0.24.0
Repo version: 15
System version: amd64/linux
Golang version: go1.21.3
```

### Config

<details>
  <summary>👉️ Click to expand</summary>
  
```json
{
  "API": {
    "HTTPHeaders": {}
  },
  "Addresses": {
    "API": "/ip4/0.0.0.0/tcp/5001",
    "Announce": [],
    "AppendAnnounce": null,
    "Gateway": "/ip4/0.0.0.0/tcp/8080",
    "NoAnnounce": [
      "/ip4/10.0.0.0/ipcidr/8",
      "/ip4/100.64.0.0/ipcidr/10",
      "/ip4/169.254.0.0/ipcidr/16",
      "/ip4/172.16.0.0/ipcidr/12",
      "/ip4/192.0.0.0/ipcidr/24",
      "/ip4/192.0.2.0/ipcidr/24",
      "/ip4/192.168.0.0/ipcidr/16",
      "/ip4/198.18.0.0/ipcidr/15",
      "/ip4/198.51.100.0/ipcidr/24",
      "/ip4/203.0.113.0/ipcidr/24",
      "/ip4/240.0.0.0/ipcidr/4",
      "/ip6/100::/ipcidr/64",
      "/ip6/2001:2::/ipcidr/48",
      "/ip6/2001:db8::/ipcidr/32",
      "/ip6/fc00::/ipcidr/7",
      "/ip6/fe80::/ipcidr/10"
    ],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic",
      "/ip4/0.0.0.0/udp/4001/quic-v1",
      "/ip4/0.0.0.0/udp/4001/quic-v1/webtransport",
      "/ip6/::/udp/4001/quic",
      "/ip6/::/udp/4001/quic-v1",
      "/ip6/::/udp/4001/quic-v1/webtransport"
    ]
  },
  "AutoNAT": {},
  "Bootstrap": [
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
    "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.131.131.82/udp/4001/quic/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa"
  ],
  "DNS": {
    "Resolvers": null
  },
  "Datastore": {
    "BloomFilterSize": 8388608,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/3",
            "sync": false,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "20TB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": false,
      "Interval": 10
    }
  },
  "Experimental": {
    "FilestoreEnabled": false,
    "GraphsyncEnabled": false,
    "Libp2pStreamMounting": false,
    "OptimisticProvide": false,
    "OptimisticProvideJobsPoolSize": 0,
    "P2pHttpProxy": false,
    "StrategicProviding": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "DeserializedResponses": null,
    "DisableHTMLErrors": null,
    "ExposeRoutingAPI": null,
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": false,
    "PathPrefixes": [],
    "PublicGateways": null,
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "..."
  },
  "Internal": {
    "Bitswap": {
      "EngineBlockstoreWorkerCount": 16,
      "EngineTaskWorkerCount": 8,
      "MaxOutstandingBytesPerPeer": 1048576,
      "ProviderSearchDelay": null,
      "TaskWorkerCount": 8
    }
  },
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Migration": {
    "DownloadSources": null,
    "Keep": ""
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Peering": {
    "Peers": [
      ...
    ]
  },
  "Pinning": {},
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {
    "Interval": "0s",
    "Strategy": "roots"
  },
  "Routing": {
    "AcceleratedDHTClient": false,
    "Methods": null,
    "Routers": null,
    "Type": "autoclient"
  },
  "Swarm": {
    "AddrFilters": [
      "/ip4/10.0.0.0/ipcidr/8",
      "/ip4/100.64.0.0/ipcidr/10",
      "/ip4/169.254.0.0/ipcidr/16",
      "/ip4/172.16.0.0/ipcidr/12",
      "/ip4/192.0.0.0/ipcidr/24",
      "/ip4/192.0.2.0/ipcidr/24",
      "/ip4/192.168.0.0/ipcidr/16",
      "/ip4/198.18.0.0/ipcidr/15",
      "/ip4/198.51.100.0/ipcidr/24",
      "/ip4/203.0.113.0/ipcidr/24",
      "/ip4/240.0.0.0/ipcidr/4",
      "/ip6/100::/ipcidr/64",
      "/ip6/2001:2::/ipcidr/48",
      "/ip6/2001:db8::/ipcidr/32",
      "/ip6/fc00::/ipcidr/7",
      "/ip6/fe80::/ipcidr/10"
    ],
    "ConnMgr": {
      "GracePeriod": "20s",
      "HighWater": 128,
      "LowWater": 64,
      "Type": "basic"
    },
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": true,
    "RelayClient": {},
    "RelayService": {},
    "ResourceMgr": {
      "Enabled": true,
      "MaxMemory": "8 GB"
    },
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  }
}
```

</details>

### Description

`ipfs repo stat --size-only` is reporting unexpected repo size values:
```
$ ipfs repo stat -H --size-only
RepoSize:   21 TB
StorageMax: 20 TB

$ ipfs repo stat --size-only
RepoSize:   21109414718512
StorageMax: 20000000000000
```
My config:
```
$ ipfs config Datastore.StorageMax
20TB
```
So `StorageMax` is fine but only about 6.3T are used on disk:
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/md3         30T  6.1T   23T  21% /home
```
So `RepoSize` looks wrong.

As a consequence I get unexpected warnings in `ipfs-cluster` logs:
```
WARN        diskinfo        disk/disk.go:138        reported freespace is 0
```
Filesystem used is XFS:
```
$ mount | grep home
/dev/md3 on /home type xfs (rw,noatime,nodiratime,attr2,inode64,logbufs=8,logbsize=32k,sunit=1024,swidth=2048,noquota)
```

**Comment by lidel** [comment]
Tried to reproduce on smaller repo, but was not able to reproduce with EXT4, smaller numbers ~match for me:

```console
$ ipfs repo stat -H --size-only
RepoSize:   121 GB
StorageMax: 100 GB

$ du -sh $IPFS_PATH
119G
```

It feels like something specific to your custom setup, either the size of `/dev/md3` or XFS filesystem.

@SmaugPool mind providing more details about your setup?

- What does `ipfs-cluster` has to do with your setup?
  - Are you pointing `ipfs` CLI at Kubo or `ipfs-cluster` instance?
  - Are you running kubo and ipfs-cluster on the same box?
- Just to confirm, where is your `$IPFS_PATH` (repo) located? `/home/user/.ipfs` or something else?
- How `/dev/md3` got created? 
- why are you using XFS with `flatfs`?
- did you run `xfs_check` and `xfs_repair` to eliminate  xfs corruption?

**Comment by SmaugPool** [comment]
> * What does `ipfs-cluster` has to do with your setup?

I mentioned `ipfs-cluster` because its `freespace is 0` warning is how I noticed the issue and I looked into it and it uses Kubo RPC repo size call. I then confirmed with Kubo CLI the result.

>   * Are you pointing `ipfs` CLI at Kubo or `ipfs-cluster` instance?

Not sure what you mean, I just run `ipfs repo stat -H --size-only` command so I think it points at Kubo.

>   * Are you running kubo and ipfs-cluster on the same box?

Yes

> * Just to confirm, where is your `$IPFS_PATH` (repo) located? `/home/user/.ipfs` or something else?

IPFS home is `/home/ipfs/.ipfs`.

> * How `/dev/md3` got created?

It's a Linux software RAID 10 device. What do you want to know? 
I pasted the XFS mount options in the issue, but here is more info:
```
$ cat /proc/mdstat 
md3 : active raid10 sdd4[0] sdc4[1] sdb4[2] sda4[3]
      31148729344 blocks super 1.2 512K chunks 2 near-copies [4/4] [UUUU]
      bitmap: 74/233 pages [296KB], 65536KB chunk

$ xfs_info /dev/md3
meta-data=/dev/md3               isize=512    agcount=32, agsize=243349376 blks
         =                       sectsz=4096  attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=1, rmapbt=0
         =                       reflink=1    bigtime=1 inobtcount=1
data     =                       bsize=4096   blocks=7787180032, imaxpct=5
         =                       sunit=128    swidth=256 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=4096   blocks=521728, version=2
         =                       sectsz=4096  sunit=1 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0

```

> * why are you using XFS with `flatfs`?

I follow `ipfs-cluster` recommendations for large clusters in production (millions of pins, terabytes of data):
https://ipfscluster.io/documentation/deployment/setup/#settings-for-production
> Unlike a previous recommendation, we have found that the flatfs datastore performs better than badger or very large repositories on modern hardware, and gives less headaches (i.e. does not need several minutes to be ready).

Do you imply that those recommendations are obsolete?

> * did you run `xfs_check` and `xfs_repair` to eliminate  xfs corruption?

No, the filesystem is just a few days old and clean. Also I have 2 nodes with the same setup/config and both have the issue.

**Comment by lidel** [comment]
Thank you for clarifications. Sadly nothing pops out immediately.

Flatfs recommendations are fine, just trying to gather enough information about your setup, as (afaik) we've not seen this before.  (cc @hsanjuan _for visibility, if free space discrepancy came up before for cluster users, or if I mischaracterized anything below._)

### Idea 1

`6.1T` figure comes from `df`, which might ignore metadata, sparse files, etc and not include all overhead in its "used" space calculation.
`22T` is produced by [calling syscall.Statfs](https://github.com/whyrusleeping/go-sysinfo/blob/4a357d4b90b11a6fd867fdb51c21d686645830c2/info_linux.go#L20C9-L20C23) on /home/ipfs/.ipfs which is more expensive, but closer to what `du -sh /home/ipfs/.ipfs` does. It is not the total sum of blocks in the repo, but the size of xfs filesystem directory that holds them, which should be a bigger number.

@SmaugPool are you able to run `du -sh /home/ipfs/.ipfs` to confirm?

### Idea 2

Other loose idea is that this is due to some XFS specifcs around metadata or things like sparse files. It depends on the data you pin, but the majority of IPFS blocks is somewhere between 128KiB - 256KiB - max 1MiB, and if xfs filesystem uses 4KiB `bsize` it might mean metadata eats more space than needed (wild guess).

You could also narrow down even further by doing `du -sh --apparent-size /home/ipfs/.ipfs`, and difference between that  and `df` will be ballpark estimation of filesystem overhead in XFS and if it is closer to 22T than 6.1T, means XFS params need to be adjusted to eat less space.

**Comment by SmaugPool** [comment]
@lidel Nothing matches `ipfs repo stat` values:
```
$ df -h  /home
Filesystem      Size  Used Avail Use% Mounted on
/dev/md3         30T   15T   15T  49% /home

$ du -hs /home/ipfs/.ipfs
14T     /home/ipfs/.ipfs

$ du -hs --apparent-size /home/ipfs/.ipfs
14T     /home/ipfs/.ipfs
```
But
```
$ ipfs repo stat -H --size-only
RepoSize:   29 TB
StorageMax: 30 TB
```

**Comment by SmaugPool** [comment]
Ok I found the culprit and it was my fault. I rsync the initial repository which included the `.ipfs/blocks/diskUsage.cache` file from another node. Once removed, it has been recalculated and everything is fine.
