### ISSUE TITLE
CI fails on helia-interop

### ISSUE THREAD

**Issue by lidel** [ipfs/kubo#10275]
helia interop tests in Kubo repo are all red ([example from PR](https://github.com/ipfs/kubo/actions/runs/7398097919/job/20126562484), [example from master]())

> ![2024-01-04_01-18](https://github.com/ipfs/kubo/assets/157609/c4eb7e0a-a4a7-418c-bf8f-5dbe7cf64159)

**Comment by BigLep** [comment]
Some conversation in FIL slack: https://filecoinproject.slack.com/archives/C046HDAHA13/p1703850246248479
