### ISSUE TITLE
Can http:/...:5001/webui be turned off via kubo config?

### ISSUE THREAD

**Issue by ozerhakan** [ipfs/kubo#10282]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

hi everyone,
I will use the API through my application, and I do not want the web UI to be accessible. Currently, files can be edited via the address https://...:5001/webui. I am planning to block this at the network level. However, it would be more convenient if this could be configured through the application's settings

**Comment by Jorropo** [comment]
The `/webui` endpoint does not do anything and is purely readonly.
It then serves an html, css and javascript bundles which hits the `/api/v0` api.

We could add a flag to allow to disable it but it wouldn't stop any modification of the node state, someone could use `ipfs` cli like this `echo "/ip4/1.2.3.4/tcp/5001" > ~/.ipfs/api`.

Leaving the API exposed is considered unsafe.

**Comment by ozerhakan** [comment]
You can unpin it using the web UI once it has been pinned. Something I don't want to happen.
At the same time, how do you think API security should be ensured?

**Comment by Jorropo** [comment]
I limit it to `127.0.0.1` or `/unix` listeners so other peoples can't access it.
Then I can put a reverse proxy like nginx or caddy in front which can do Bearer Token authentication and TLS encryption.

**Comment by ozerhakan** [comment]
Of course it can be done  
thx

**Comment by hacdias** [comment]
@ozerhakan it seems that your goal is to prevent unauthorized access to the API via the Web UI. You can use the API Authorizations configuration: https://github.com/ipfs/kubo/blob/master/docs/config.md#apiauthorizations. By using this, all API requests need to be authenticated, which is not compatible with the Web UI.

Disabling the `/webui` endpoint is not possible at the moment, and wouldn't solve any issue. If a user has access to `:5001/webui`, they also have to `:5001/api/v0` and could still do any modifications they want through the RPC API.
