### ISSUE TITLE
Deprecate and remove `/api/v0` under the gateway port

### ISSUE THREAD

**Issue by hacdias** [ipfs/kubo#10312]
We've been wanting to deprecate the access to `/api/v0` under the gateway path for [at least two years](https://github.com/ipfs/kubo/commit/84ed0ec59f2472e8ca4ef7f5f3f4027fe58b10ac#diff-28221ed38896d1567acc67ba8c040755be2931ff71190fc4efd2f3e8c7b94d91R116), but I have not found any issue. This is the tracking issue.

- [x] **Kubo 0.27:** deprecate `/api/v0` from gateway port: https://github.com/ipfs/kubo/pull/10311.
- [ ] **Kubo 0.28**: completely remove `/api/v0` from gateway port: https://github.com/ipfs/kubo/pull/10352

**Comment by bahner** [comment]
Is this just for the gateway functionality or the API in general. Over localhost we'll still be using this or am I missing something? The issues here are a little confusing to understand.

**Comment by hacdias** [comment]
@bahner this is about removing `/api/v0` on the gateway port (default 8080). The API will still be available on the API port (default 5001).
