### ISSUE TITLE
IPFS RPC API documentation

### ISSUE THREAD

**Issue by stolab** [ipfs/kubo#10446]
### Checklist

- [X] I am reporting a documentation issue in this repo, not https://docs.ipfs.tech.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

Is there some documentation available on how to use the RPC API for kubo](https://pkg.go.dev/github.com/ipfs/kubo/client/rpc) ? 
It feels like it's capable of doing a loooot of stuff but it's really hard (at least for me) to understand how to use that.

For example I cannot understand how to get an asset from a localAPI based on the CID....

**Comment by stolab** [comment]
+ it seems that coreinterface (https://pkg.go.dev/github.com/ipfs/boxo/coreiface#CoreAPI) it's not part of boxo anymore.........

Which means even the example at the top does not work anymore......

**Comment by gammazero** [comment]
The example above has been updated and should work now: https://github.com/ipfs/kubo/tree/master/client/rpc#coreifacecoreapi-over-http-rpc

The reference documentation will be updated with the upcoming release.

**Comment by lidel** [comment]
https://pkg.go.dev/github.com/ipfs/kubo/client/rpc now reflects 0.30.0
