### ISSUE TITLE
Exception 0xc0000005 0x8 0x0 0x0 when try to run ipfs.

### ISSUE THREAD

**Issue by ivan386** [ipfs/kubo#10454]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.tech](https://discuss.ipfs.tech/c/help/13).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.tech

### Version

```Text
v0.29.0
```

### Description

I try to run ipfs from [release v0.29.0](https://github.com/ipfs/kubo/releases/tag/v0.29.0) kubo_v0.29.0_windows-386.zip and  kubo_v0.29.0_windows-amd64.zip  on windows 7 x64. Both give me same exception.

windows-386:
```con
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall(0x20)
        runtime/sys_windows_386.s:44 +0x2a fp=0x18fe28 sp=0x18fe24 pc=0x47ca0a
eax     0x8
ebx     0x2d1cb10
ecx     0x0
edx     0x18fe58
edi     0x18fe2c
esi     0x18fe8c
ebp     0x18fe2c
esp     0x18fe20
eip     0x0
eflags  0x10206
cs      0x23
fs      0x53
gs      0x2b
```

windows-amd64:
```con
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall(0x22fcf8)
        runtime/sys_windows_amd64.s:75 +0x7a fp=0x22fc80 sp=0x22fc60 pc=0x47b8fa
rax     0x0
rbx     0x3018c58
rcx     0x30a2f28
rdx     0x20
rdi     0x7fffffdd000
rsi     0x22fe78
rbp     0x22fdc0
rsp     0x22fc58
r8      0x0
r9      0x22fee8
r10     0x30a2e8
r11     0xc000004000
r12     0x22fec8
r13     0x0
r14     0x3017ac0
r15     0x3
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
```

last version that work on my pc is:
```
Kubo version: 0.24.0
```

**Comment by hsanjuan** [comment]
Cursory google search gives that windows 7 is not supported by go >= 1.21.5 https://github.com/golang/go/issues/64622. You can try compiling with an older version of Go though.

**Comment by lidel** [comment]
Yes, Windows 7 is not supported by golang anymore. Feel free to fork/build, but we can't officially support it.
See https://github.com/ipfs/ipfs-desktop/issues/2823#issuecomment-2163182898
