### ISSUE TITLE
Debian handler scripts - Copy or Submodule?

### ISSUE THREAD

**Issue by twdragon** [ipfs/kubo#10475]
After the successful launch of the unofficial Ubuntu PPA as an installation source (#10467), and some tests, here is my suggestion to *add building of the Debian packages to the mainline Github Workflows CI*. The maintainer scripts and build handler scripts are maintained now in the repository: https://github.com/twdragon/kubo-debian-pkg

The question is: **Should I open the pull request to**
- Create the **submodule** containing the handler scripts within the original Kubo repository.
- **Copy** the code from the Debian handler scripts repository to the Kubo repository and archive the original one.

**Comment by lidel** [comment]
Closing, as we had discussion in https://github.com/ipfs/kubo/pull/10479 and decided distribution-specific packaging pipelines need to live outside of this repository. 

We are happy to add community-maintained packages in https://github.com/ipfs/kubo?tab=readme-ov-file#unofficial-linux-packages

Rationale in https://github.com/ipfs/kubo/pull/10479#pullrequestreview-2238503257 and https://github.com/ipfs/kubo/pull/10479#issuecomment-2299586801
