### ISSUE TITLE
[question] How to failfast when get a none-exists CID

### ISSUE THREAD

**Issue by timandy** [ipfs/kubo#10500]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

**I use kubo as a dependency library and run it on the local lan network.**

**My expect:**
I want to download files through IPFS, and when the file does not exist, I hope the core api immediately return.
When the file exists, download it using the timeout given by `ctx`.
Or in other words,  The `Get` API Can use two `ctx`, one is used to detect file exist or not, the other for
 download timeout.

**NOW:**
I found that when get a non-existent CID through the core API, it will hang and not return.
Is there any way to determine if a CID does exist or not and return in a custom timeout `ctx`.

**Comment by lidel** [comment]
Github repository is for bugs and feature requests, for support questions please keep using discussion forums.

Continued in https://discuss.ipfs.tech/t/how-to-failfast-when-get-a-none-exists-cid/18470/2?u=lidel
