### ISSUE TITLE
go1.23 timers cause issues with libp2p connmgr and more

### ISSUE THREAD

**Issue by lidel** [ipfs/kubo#10501]
### Version

```Text
0.30.0-rc2
```

### Config

```json
default `ipfs init` + custom ports to run A/B test
```

## Bug 

0.30.0-rc2 switched to go1.23, and we experience an increased number of connections when running go-libp2p  + go-libp2p-kad-dht server, confirmed both by me, and [anecdotal evidence from discussion forums](https://discuss.ipfs.tech/t/kubo-v0-30-0-rc2-is-out/18450/4?u=lidel).

The problem seem to go away if running with forced go1.22 timer behavior `GODEBUG=asynctimerchan=1` (Ref. https://go.dev/wiki/Go123Timer)

### How to reproduce 

1. Run two instances of 0.30.0-rc2 with a public IP or UPnP, so they act as DHT servers and get a lot of connections from random peers. Run them with different env variables:
  - `GODEBUG=asynctimerchan=0` to force Go 1.23 timers
  - `GODEBUG=asynctimerchan=1` to force Go 1.22 timers
2. After a few hours, the one that runs with `GODEBUG=asynctimerchan=0`  will have significantly more connections (e.g. 6k vs 200)
3. Stopping with <kbd>ctl-C</kbd> does not work reliably  with `GODEBUG=asynctimerchan=0`, it sometimes takes a second time to correctly stop the daemon.

## Next steps

Short term, I will revert https://github.com/ipfs/kubo/pull/10486 and switch back to 1.22 for 0.30.0 release and keep it until go-libp2p and go-libp2p-kad-dht are compatible with 1.23.

**Comment by Jorropo** [comment]
golang/go#69186

**Comment by Stebalien** [comment]
I don't think we have any cases where we copy timers.

**Comment by lidel** [comment]
Seems its "the part where the timer channel will not have any stale reads after timer.Stop returns": https://github.com/quic-go/quic-go/pull/4659
