### ISSUE TITLE
Remove shebang from shell completions

### ISSUE THREAD

**Issue by kpcyrd** [ipfs/kubo#10514]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.tech](https://discuss.ipfs.tech/c/help/13).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

built from source

### Version

```Text
Kubo version: 0.30.0
Repo version: 16
System version: amd64/linux
Golang version: go1.23.1
```

### Description

hi!

I noticed the shell completions contain a shebang (`#!/...`) but shell completions are usually sourced instead of executed, so a shebang is not necessary.

For zsh it seems the completions are not working due to this:

```
% ipfs d<tab><tab>
(nothing happens)
```

**Comment by lidel** [comment]
@kpcyrd I am unable to reproduce, following https://github.com/ipfs/kubo/blob/master/docs/command-completion.md#zsh the `eval "$(ipfs commands completion zsh)"` works fine with zsh 5.9.

Perhaps you are using something else? IF so, why? Are there other docs related to this that we should update?

**Comment by kpcyrd** [comment]
I'm not sure if eval is the right way to test this, in my case the completions are loaded from `/usr/share/zsh/site-functions/_ipfs`.

The `_ipfs` file I use is `sha256:001becd85257c39b452858b2371680fcf936b587c94d845bd8fd2e7c17f2df21`.

**Comment by lidel** [comment]
@kpcyrd how are they loaded on your system? Who wrote the loader?

**Comment by kpcyrd** [comment]
They are generated with:

```sh
cmd/ipfs/ipfs commands completion bash > "$srcdir/ipfs-completion.bash"
cmd/ipfs/ipfs commands completion fish > "$srcdir/ipfs-completion.fish"
cmd/ipfs/ipfs commands completion zsh > "$srcdir/ipfs-completion.zsh"
```

https://gitlab.archlinux.org/archlinux/packaging/packages/kubo/-/blob/cdf59db01b3dc6241c55bbe4b57bbdd678037e51/PKGBUILD#L53

**Comment by lidel** [comment]
Triage notes:
- our understanding is that shebang may serve purpose in some context / package managers / deployments 
- it is unclear if there is any bug here, looks more like cosmetic
- we are not investing time into this, unless a reproducible bug is filled (feel free to fill new one, if you find it)
