### ISSUE TITLE
Accept symbolic links as mounting scripts in the Docker image

### ISSUE THREAD

**Issue by jesusvico** [ipfs/kubo#10519]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

Now, only regular files are accepted as valid mounting scripts in the Docker image.

```bash
# /kubo/bin/container_daemon

#...

find /container-init.d -maxdepth 1 -type f -iname '*.sh' -print0 | sort -z | xargs -n 1 -0 -r container_init_run
```

This could be fixed with the following change:
```bash
find /container-init.d -maxdepth 1 \( -type f -o -type l \) -iname '*.sh' -print0
```

When using Kubernetes, ConfigMaps are mounted as symbolic links. Because of this, I cannot easily use the mounting script functionality.

**Comment by lidel** [comment]
@jesusvico sounds sensible, as long links are resolvable. Mind submitting a PR?
