### ISSUE TITLE
Phishing subdomain deploy

### ISSUE THREAD

**Issue by Mariano-E-Pf** [ipfs/kubo#10573]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.tech](https://discuss.ipfs.tech/c/help/13).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

dist.ipfs.tech or ipfs-update

### Description

Hello Dev Team,
I had sent this abuse report to several of your addresses without getting an answer. How can be listening by your abuse team? We have a serious attack in progress and your response time is totally unacceptable. The following report was sent to [REDACTED TO AVOID EVEN MORE SPAM].
 
Please note that a phishing site registered through your service is being used to conduct a phishing attack. It is available at the following URL:
hxxps[:]//ipfs[.]io/ipfs/Qmd5sFNGFRzzrGnuZa6YSpBcZ2wPAUozsRWZKVsXZkshEW/
![phishing_domain](https://github.com/user-attachments/assets/f88ba690-1d12-4b01-93e0-1cf4348802d6)
[usecorn.com](http://usecorn.com/)

The attack consists of several domains impersonating our client (Usecorn) using their logo, brand name, and a typosquat in the domain. The sites have a captcha that after solving it redirects to this phishing page. In this way, threat actors manage to confuse crypto users and redirect them to this site. In this phishing site registered with you, we detected a multiwallet phishing kit, which is being used to drain users' savings.

Please assist us with shutting it down as soon as possible, we appreciate your swift response in this regard. If you require any additional information, please do not hesitate to contact us.

Thank you,
PhishFort Team

**Comment by lidel** [comment]
Thank you for reaching out, but this repository is for Kubo daemon, which is not related to service at `ipfs.io` nor https://badbits.dwebops.pub/.

The best course of action is to follow "Abuse Policy" listed at https://docs.ipfs.tech/concepts/public-utilities/#public-ipfs-gateways  and wait for report to be processed by respective takedown team behind https://badbits.dwebops.pub – that is the only group capable of triaging takedown requests, sending  emails to other mailing lists related to IPFS will not make things any faster.
