### ISSUE TITLE
protobufs as separate repo

### ISSUE THREAD

**Issue by daviddias** [ipfs/kubo#1483]
@whyrusleeping as we talked earlier, can we have the protobufs in a separate repo, so that we maintain only one version for both go-ipfs and node-ipfs? Avoiding the c&p dance :)

**Comment by jbenet** [comment]
:+1:

**Comment by RubenKelevra** [comment]
@daviddias has this been resolved or superseded by a different idea? Can this ticket be closed? :)

**Comment by Stebalien** [comment]
This has not been resolved, unfortunately.
