### ISSUE TITLE
Installing OSX FUSE (for Mac OS X)

### ISSUE THREAD

**Issue by jbenet** [ipfs/kubo#177]
### old version kernel panic warning

Older versions of OSX FUSE (for Mac OS X) may kernel panic (it's bitten multiple of us already). 
**If you're on OSX, please make sure you have OSX FUSE 2.7.0+**
## Installing OSX FUSE
- from binary distribution
- from `brew`
### from binary distribution
1. Go to http://osxfuse.github.io
2. Download + Install the package.

![](https://www.evernote.com/shard/s198/sh/b5c4511a-5efc-47b0-b0a5-ff1fa5a9f1bf/312eb5f28526b96f364c7d927ffc7749/deep/0/Home---FUSE-for-OS-X.png)
### from `brew`

Simply:

```
brew update && brew install osxfuse
```
### Note: conflicting installs with brew

If you receive the following error: 

```
osxfuse: osxfuse is already installed from the binary distribution and conflicts with this formula.
```

Uninstall OSX FUSE binary from System Preferences before attempting to `brew install osxfuse` again.

![](https://www.evernote.com/shard/s198/sh/2b3b234c-0650-4a96-895a-65bef5eb52df/55689e06b53055fd0c013ee910cef7cd/deep/0/System-Preferences.png)
![](https://www.evernote.com/shard/s198/sh/ba3c1053-d975-4a6f-be02-66aa1c6ef254/7dcd8988773bc5e935a4d883dcb00e44/deep/0/FUSE-for-OS-X-%28OSXFUSE%29.png)

**Comment by fisch0920** [comment]
On Mac OS 10.11.6, when I run `fuse mount`, I get the following:

```
Error: OSXFUSE version 3.5.3 not supported.

OSXFUSE versions <2.7.2 are known to cause kernel panics!
Please upgrade to the latest OSXFUSE version.
It is recommended you install it from the OSXFUSE website:
	http://osxfuse.github.io/

For more help, see:
	https://github.com/ipfs/go-ipfs/issues/177
```

This error message doesn't make any sense seeing as it acknowledges that I have the most recent version of fuse installed (3.5.3).

Here is the output of `fuse-version`:
```
OSXFUSE.FuseVersion: 29
OSXFUSE.AgentVersion: 3.5.3
OSXFUSE.AgentName: OSXFUSE
```

I'm guessing this is a common issue?

**Comment by VictorBjelkholm** [comment]
@fisch0920 seems the way we're checking that the version above 2.7.2 is not really proper, we just check so it starts with `2.8`

See here: https://github.com/ipfs/go-ipfs/blob/73cd8b3e98aba252f0eadcc625472103a2dd1d53/fuse/node/mount_darwin.go#L141

There seems to be a switch to turn of the version checking as well, but I don't have osx to see if it actually works for you.

**Comment by VictorBjelkholm** [comment]
For future readers, there was an issue created specifically for the version check here: https://github.com/ipfs/go-ipfs/issues/3410

**Comment by ejholmes** [comment]
FWIW, `brew install osxfuse` no longer works, since it was migrated to caskroom/cask. The following does work:

```console
$ brew tap caskroom/cask
$ brew update && brew cask install osxfuse
```

**Comment by eingenito** [comment]
@hatgit not at all. The go-ipfs implementation includes a command line interface that allows comprehensive use of IPFS features and is considered the "standard" way to add and get files (via the aptly named `add` and `get` commands). FUSE is an optional (neat) way of interacting with IPFS content.

**Comment by hatgit** [comment]
> @hatgit not at all. The go-ipfs implementation includes a command line interface that allows comprehensive use of IPFS features and is considered the "standard" way to add and get files (via the aptly named `add` and `get` commands). FUSE is an optional (neat) way of interacting with IPFS content. You can read about basic usage of the `ipfs` command line tool here:
> 
> https://docs.ipfs.io/introduction/usage/

Thanks @eingenito, I already have the daemon running and swarmed all peers (fully connected) and in the GUI http://localhost:5001/webui I see the files I uploaded but when I copy the hash of any of those files I still cannot view them online after appending to the end of this url: http://ipfs.io/ipfs/ 
nor using cloudflare's hosted url. I'm trying to troubleshoot why they aren't being served.

I've also tried the add and get methods and those only seem to work locally but still cannot view the file in a public url (shouldn't I be able to do that, assuming the files go to IPFS's gateway?)

In addition, while I did end up installing fuse and updating the config file, the two folders contained within OSXFUSE Volume 1 (ipfs) are empty (one is named local and the other is named after the ID hash).

**Comment by VictorBjelkholm** [comment]
> shouldn't I be able to do that, assuming the files go to IPFS's gateway?

Detail but still important: the files don't "go to the gateways" but rather the gateway fetches the content when it's being requested. You still need to be running your own go-ipfs daemon when you try to access your content via the gateways.

If you can fetch content that you don't have locally (like the kitten image) but other peers can't fetch content, you might have a firewall or something running, stopping go-ipfs from sending data. Try running `netcat $yourIP 4001` from some computer outside your network and see if you get `/multistream/1.0.0` as a reply, in that case, it should be working. If you cannot get the initial multistream response, it seems like something is blocking the outbound traffic from your go-ipfs node.

**Comment by hatgit** [comment]
Thanks @VictorBjelkholm, the config instructions listed here helped it finally work for me  https://webui.ipfs.io/#/welcome
