### ISSUE TITLE
Some API errors are not JSON

### ISSUE THREAD

**Issue by daviddias** [ipfs/kubo#1970]
Getting some errors from the HTTP API that are not valid JSON, breaking the js-ipfs-api expectations. I can "try/catch" on the API side, but it would be more clean if JSON was the preferred format for all of the errors.

```
commands/http/parse.go
109:            return nil, fmt.Errorf("File argument '%s' is required", requiredFile)
```

Related with the https://github.com/diasdavid/registry-mirror project

**Comment by jbenet** [comment]
> it would be more clean if JSON was the preferred format for all of the errors.

:+1:
