### ISSUE TITLE
`ipfs object stat` deduped size vs. real size

### ISSUE THREAD

**Issue by jbenet** [ipfs/kubo#2071]
currently, ipfs object stat shows:

```
> ipfs object stat QmbL23v6s8fysWrtXj1agBTsdr6xCZjsTNSLWhFBtAyrAt
NumLinks: 5
BlockSize: 352
LinksSize: 350
DataSize: 2
CumulativeSize: 34071652
```

it should also show `ObjectSize` (size serialized):

```
> ipfs object stat QmbL23v6s8fysWrtXj1agBTsdr6xCZjsTNSLWhFBtAyrAt
NumLinks: 5
BlockSize: 352
LinksSize: 350
DataSize: 2
ObjectSize: 352
CumulativeSize: 34071652
```

**Comment by jbenet** [comment]
nevermind, it's already there, `BlockSize`

**Comment by lgierth** [comment]
It maybe should have deduped size vs. real size though!

**Comment by jbenet** [comment]
yep, indeed! :+1:

**Comment by VictorBjelkholm** [comment]
Yeah, would be good to have. Currently, you cannot get the real size in anyway, without first downloading the file, which kind of defeats the purpose to be able to see the size.

**Comment by whyrusleeping** [comment]
@VictorBjelkholm you should be able to see the real size of a file by grabbing just the root block of it. The merkledag protobuf gives you the cumulative size, and if you decode its data segment as a [unixfs protobuf](https://github.com/ipfs/go-ipfs/blob/master/unixfs/pb/unixfs.proto) then the filesize field there will give you the info you need.

**Comment by VictorBjelkholm** [comment]
@whyrusleeping ah, sorry, meant directory. It's related to the deduped size vs the real size I'm betting on.

How these sizes are related?

```
➜  async git:(clean) ✗ ipfs object stat QmUV6jhcUWK8ghvUq7wU9q7sWajXu3UzJfBwKpx2Qm9PJF
NumLinks: 20
BlockSize: 1049
LinksSize: 1047
DataSize: 2
CumulativeSize: 672729
➜  async git:(clean) ✗ ipfs get QmUV6jhcUWK8ghvUq7wU9q7sWajXu3UzJfBwKpx2Qm9PJF
Saving file(s) to QmUV6jhcUWK8ghvUq7wU9q7sWajXu3UzJfBwKpx2Qm9PJF
770.00 KB 0
➜  async git:(clean) ✗ du -ah QmUV6jhcUWK8ghvUq7wU9q7sWajXu3UzJfBwKpx2Qm9PJF | tail -n1
1.1M	QmUV6jhcUWK8ghvUq7wU9q7sWajXu3UzJfBwKpx2Qm9PJF
```

672729 (672 KB, no?) vs 770.00 KB vs 1.1M

**Comment by whyrusleeping** [comment]
@VictorBjelkholm interesting. What is in that hash? When i do a similar thing, I get a valid looking result:
```
whyrusleeping@aredhel ~> ipfs add -r bin
added QmXkn1Fi5JS2pccanfxsWGEbBfJcpUbKZWtjLYzySSVzcy bin/colors                          
added QmeGPGz3ihr7edpwWT2FUwuYSHGQnWAA6emV8vhgCrrw54 bin/ngrok                           
added QmfJHLTjAxKU8M4qBkJK2u49vPJz7kg9Y7qFBqJtKod3Jh bin/pulls                           
added QmbXvCGEGev9UEKaQfkztea4MMN2PF2FBmgA9qxeafHeqS bin/wake-desktop                    
added QmZHYxfe2rbhMZpaBJqrfEqtnyEj85PqJVA2LMSpRvPEUn bin
whyrusleeping@aredhel ~> ipfs object stat QmZHYxfe2rbhMZpaBJqrfEqtnyEj85PqJVA2LMSpRvPEUn
NumLinks: 4
BlockSize: 205
LinksSize: 203
DataSize: 2
CumulativeSize: 14107659
whyrusleeping@aredhel ~> du -h bin
14M	    bin
```

**Comment by VictorBjelkholm** [comment]
@whyrusleeping it's the package `async`, built from source here: https://github.com/caolan/async

If you're interested in the contents of the hash: https://ipfs.io/ipfs/QmUV6jhcUWK8ghvUq7wU9q7sWajXu3UzJfBwKpx2Qm9PJF

I did try again with a different directory and got much closer results (ipfs object stat and ipfs add being identical but du showing different size)

```
➜  ipfs object stat QmbH7RYxZgLvrKyVcP1KBvcx4HpKq9cWagFEPM7LgiZaZQ
NumLinks: 5
BlockSize: 267
LinksSize: 265
DataSize: 2
CumulativeSize: 465750
➜  ipfs get QmbH7RYxZgLvrKyVcP1KBvcx4HpKq9cWagFEPM7LgiZaZQ
Saving file(s) to QmbH7RYxZgLvrKyVcP1KBvcx4HpKq9cWagFEPM7LgiZaZQ
465.00 KB 0
➜  du -h QmbH7RYxZgLvrKyVcP1KBvcx4HpKq9cWagFEPM7LgiZaZQ
320K	QmbH7RYxZgLvrKyVcP1KBvcx4HpKq9cWagFEPM7LgiZaZQ/public/fonts/roboto
112K	QmbH7RYxZgLvrKyVcP1KBvcx4HpKq9cWagFEPM7LgiZaZQ/public/fonts/roboto_mono
432K	QmbH7RYxZgLvrKyVcP1KBvcx4HpKq9cWagFEPM7LgiZaZQ/public/fonts
448K	QmbH7RYxZgLvrKyVcP1KBvcx4HpKq9cWagFEPM7LgiZaZQ/public
472K	QmbH7RYxZgLvrKyVcP1KBvcx4HpKq9cWagFEPM7LgiZaZQ
```

**Comment by VictorBjelkholm** [comment]
@whyrusleeping it's the package `async`, built from source here: https://github.com/caolan/async

If you're interested in the contents of the hash: https://ipfs.io/ipfs/QmUV6jhcUWK8ghvUq7wU9q7sWajXu3UzJfBwKpx2Qm9PJF

I did try again with a different directory and got much closer results (ipfs object stat and ipfs add being identical but du showing different size)

```
➜  ipfs object stat QmbH7RYxZgLvrKyVcP1KBvcx4HpKq9cWagFEPM7LgiZaZQ
NumLinks: 5
BlockSize: 267
LinksSize: 265
DataSize: 2
CumulativeSize: 465750
➜  ipfs get QmbH7RYxZgLvrKyVcP1KBvcx4HpKq9cWagFEPM7LgiZaZQ
Saving file(s) to QmbH7RYxZgLvrKyVcP1KBvcx4HpKq9cWagFEPM7LgiZaZQ
465.00 KB 0
➜  du -h QmbH7RYxZgLvrKyVcP1KBvcx4HpKq9cWagFEPM7LgiZaZQ
320K	QmbH7RYxZgLvrKyVcP1KBvcx4HpKq9cWagFEPM7LgiZaZQ/public/fonts/roboto
112K	QmbH7RYxZgLvrKyVcP1KBvcx4HpKq9cWagFEPM7LgiZaZQ/public/fonts/roboto_mono
432K	QmbH7RYxZgLvrKyVcP1KBvcx4HpKq9cWagFEPM7LgiZaZQ/public/fonts
448K	QmbH7RYxZgLvrKyVcP1KBvcx4HpKq9cWagFEPM7LgiZaZQ/public
472K	QmbH7RYxZgLvrKyVcP1KBvcx4HpKq9cWagFEPM7LgiZaZQ
```

**Comment by RubenKelevra** [comment]
I don't think there's an easy way to find the real size, as this would mean running through the whole tree searching m:n for duplicate CIDs.

**Comment by georgyo** [comment]
> I don't think there's an easy way to find the real size, as this would mean running through the whole tree searching m:n for duplicate CIDs.

This is a pretty important feature.... The cost of pinning something (either with filecoin or other pinning services) is based on the size of the storage. However CIDs that contain heavily duplicated data are charged at many times the actually storage requirements.

A heavily touted feature of IPFS is that it dedups data, it would be a shame if that doesn't actually result in cost savings for the end user.

**Comment by Jorropo** [comment]
`ipfs dag stat` now accepts N CIDs and computed similar information.
