### ISSUE TITLE
feat:request - ipfs files name publish <path>

### ISSUE THREAD

**Issue by daviddias** [ipfs/kubo#2133]
So that we can avoid doing 2 RTT (ipfs files stat <path> + ipfs name publish)

**Comment by whyrusleeping** [comment]
@diasdavid are you referring to a path in mfs? This might have to be done as a command within mfs or similar. The overlap there is currently a little weird

**Comment by diasdavid** [comment]
yep, so that it is easy to publish one of the paths through IPNS
