### ISSUE TITLE
files cp/mv of existing dirs

### ISSUE THREAD

**Issue by daviddias** [ipfs/kubo#2272]
I want to be able to do a `ipfs files cp /ipfs/hash /folder` or `ipfs files mv /ipfs/hash /folder` and it work independently of being a file or a folder. Currently, neither `cp` or `mv` have a `-r`. `cp` is able to copy the MerkleDAG node that represents a directory, but just once, on the second time I have to remove it first, and since it is a directory, it has to be removed with -r.

**Comment by whyrusleeping** [comment]
could you elaborate a little? i'm not sure what youre looking for here

**Comment by diasdavid** [comment]
Apologies for not being clear, what I want is to be able to replace an entire folder with another one in one  command

**Comment by whyrusleeping** [comment]
This doesnt map to any unix command that i know of. `mv A B` will put `A` inside of `B` if `B` exists and is a directory.

**Comment by diasdavid** [comment]
Right. This reminds me how having that command to merge dirs ( and therefore merkle dag nodes) would be so sweet :)

**Comment by whyrusleeping** [comment]
@diasdavid I could pretty easily add `ipfs object merge`. The underlying code for it is there, right alongside the code for diff (which is now a command). Do you want that?

**Comment by ajbouh** [comment]
@whyrusleeping did `ipfs object merge` ever get created? I'd like to stitch together directories that I don't have stored locally.

**Comment by ceez** [comment]
You should be able to use rsync -avP to do this.    Most don't realize that it does not have to be used with a remote src or target.   

There is --delete flag to clear the target before copying the src directory.
