### ISSUE TITLE
leaf unixfs nodes are being created with type 'file' instead of 'raw'

### ISSUE THREAD

**Issue by daviddias** [ipfs/kubo#2331]
I was debugging a js-ipfs go-ipfs interop issue for a while and in the end the difference was that if a file had to be chunked, my leaf data nodes would be created with type 'raw' (0 in the encoded protobuf), while go-ipfs does type 'files (2 in the encoded protobuf) for everything. Is this accurate and intended?

**Comment by diasdavid** [comment]
ipfs version 0.4.0 (latest master)

**Comment by Stebalien** [comment]
Status: Raw leaves *are* supported but still experimental. Currently, you have to request them with the `--raw-leaves` flag.

**Comment by diasdavid** [comment]
@Stebalien there are two things here, we have:

- The unixfs protobuf raw - https://github.com/ipfs/js-ipfs-unixfs/blob/master/src/unixfs.proto.js#L5 (this was before IPLD was shipped, see the date of my issue)
- The IPLD raw node - https://github.com/ipld/js-ipld-raw

js-ipfs can do --raw-leaves as in Raw IPLD nodes too, the question here is why the unixfs-engine in go doesn't create RAW type unixfs protobufs for chunks
