### ISSUE TITLE
Secure/Authenticated API access

### ISSUE THREAD

**Issue by Stebalien** [ipfs/kubo#2389]
Currently,
1. Anyone on a machine running IPFS can access the IPFS API over the HTTP interface. This means any user can, e.g., read any running daemon's private keys.
2. Anyone on a machine can run an IPFS server on the standard IPFS port and the IPFS client will blindly use it. This means that a malicious user could impersonate the IPFS server.

Solutions:
1. Use unix domain sockets. The daemon could expose the API over one or more unix domain sockets. If multiple sockets are used, administrators could control access to various APIs using standard unix permissions (this doesn't require multiple sockets but that might make implementation easier).
2. Use HTTP authentication and store some API key in the IPFS directory. With this method, care must be taken to authenticate both ways.

**Comment by hermanjunge** [comment]
We, at INFURA, really need to work on some kind of implementation for the API. This element, indeed, has a priority a little higher than developing `ipfs-cluster` 😬.

I know @jbenet you told me that _IPFS daemon is not meant that way_. But the need is there, to provide a daemon to people to upload and pin files. I had a quick conversation at DevCon2 with @whyrusleeping, and was suggested to build a specification, to discuss and implement.

So my question: Where do we move this conversation, so I can start a specification and implement it? In this repository? In `ipfs/specs`?

Thank you y gracias por la paciencia, los últimos meses han sido una locura!

HJ.-

**Comment by Kubuxu** [comment]
There is also https://github.com/ipfs/go-ipfs/issues/1532

**Comment by hermanjunge** [comment]
@Kubuxu Cool. @jbenet told me there was a more mature issue. So, that was it 😄 

Thanks!

**Comment by sebs** [comment]
I like this a lot.

**Comment by NotBad4U** [comment]
Any update on this ?

**Comment by Stebalien** [comment]
No. The current way to do this is to stick an NGINX proxy out in front of the API and authenticate with that.

**Comment by scanlime** [comment]
If I understand correctly, the current setup means anyone on localhost is privileged to interact with the API?

**Comment by OpenOS-Project-Creator-Founder** [comment]
Maybe this could help?

Making the entire Linux Kernel & Linux Kernel Based-Distros from head to toe & from power on state to power off state an entire IPFS Node + Cluster + Pinning Service + Gateway....?


https://github.com/cpg1111/ipos

**Comment by Jorropo** [comment]
> If I understand correctly, the current setup means anyone on localhost is privileged to interact with the API?

You can use unshare and cgroups to create multiple permissioned loopbacks (docker, lxd, ... give you thoses features available conviniently).

**Comment by Jorropo** [comment]
@OpenOS-Project-Creator-Founder 

> Maybe this could help?
> Making the entire Linux Kernel & Linux Kernel Based-Distros from head to toe & from power on state to power off state an entire IPFS Node + Cluster + Pinning Service + Gateway....?

No, asking peoples to run a custom kernel that ships with a bunch of extra features is a far too big ask and not pratical for this rather simple problem, using custom kernels with many cloud providers is really painfull.

I personally prefer people using reverse proxies, vpns or tunnels. I use ssh tunnels myself.

**Comment by OpenOS-Project-Creator-Founder** [comment]
> @OpenOS-Project-Creator-Founder 
> 
> > Maybe this could help?
> > Making the entire Linux Kernel & Linux Kernel Based-Distros from head to toe & from power on state to power off state an entire IPFS Node + Cluster + Pinning Service + Gateway....?
> 
> No, asking peoples to run a custom kernel that ships with a bunch of extra features is a far too big ask and not pratical for this rather simple problem, using custom kernels with many cloud providers is really painfull.
> 
> I personally prefer people using reverse proxies, vpns or tunnels. I use ssh tunnels myself.



Here are some resources...

Let's discuss possible implementations before shutting down the entire idea.

https://github.com/gopher-os/gopher-os

https://github.com/pmorjan/kmod

https://github.com/mediremi/rust-plus-golang

https://github.com/confio/go-rust-demo

https://github.com/rust-lang/rust-bindgen

https://github.com/rs-ipfs/rust-ipfs

https://github.com/ferristseng/rust-ipfs-api

https://opencollective.com/rs-ipfs

https://discuss.ipfs.tech/t/sharing-the-ipfs-data-directory-and-daemon-between-multiple-users/9312

https://github.com/ipfs/kubo/issues/2389

https://www.reddit.com/r/ipfs/comments/4xxpk6/user_vs_system_ipfs_daemon/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=2&utm_content=share_button

**Comment by OpenOS-Project-Creator-Founder** [comment]
Here are some resources of NodeJS & JavaScript Based Linux Distros.

Maybe merge them all into a new IPFS Linux Based Distro to be a rolling long-term support Distro for others to derive from...



https://github.com/eXtern-OS

https://link.medium.com/QrBhAFueyvb

https://github.com/Manjaro-WebDad/jde

https://github.com/ruslang02/atomos

https://github.com/NodeOS/NodeOS

**Comment by Jorropo** [comment]
@OpenOS-Project-Creator-Founder seems like you are intrested in making a new distro with various new features, this can be good but that is a different unrelated project, please don't post totally unrelated things on issues on github, this issue is about Authentication of the Kubo API, not creating NodeJS based Linux Distro.
