### ISSUE TITLE
`ipfs object patch add-link` doesn't throw error for invalid ref argument

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/kubo#2473]
```
🐕  ipfs object patch QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn add-link foo
Error: Argument 'ref' is required

Use 'ipfs object patch add-link --help' for information about this command
🐕  ipfs object patch QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn add-link foo ''
QmSt5pTDuoZ5xi1iqroo8W57Fvp4U23h5gXfj6X7rWLcbn
🐕  ipfs object patch QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn add-link foo kitten
Error: Post http://127.0.0.1:5001/api/v0/object/patch/add-link?arg=QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn&arg=foo&arg=kitten&encoding=json&stream-channels=true: EOF
```

The firs response makes sense. I'm not sure the second does - an empty argument shouldn't be allowed, I don't think. The third hangs in the HTTP API, but returns this strange inscrutable error in the CLI. 

Not sure what is going on here. Discovered as part of https://github.com/ipfs/http-api-spec/pull/32.

**Comment by RichardLitt** [comment]
Blocking https://github.com/ipfs/http-api-spec/pull/68.

**Comment by lidel** [comment]
Object API has been deprecated since 2021 (https://github.com/ipfs/kubo/issues/7936), we won't be fixing bugs related to it.
