### ISSUE TITLE
Feature request for repo hascontent command

### ISSUE THREAD

**Issue by slothbag** [ipfs/kubo#2836]
It would be handy to have a `hascontent` command that returns immediately with a true or false depending on if the local node has the specified content or not.  

Currently all API calls wait for a long time while the node attempts to obtain the content from the network. (Unless you shutdown the node, then it returns immediately)

It could sit under the Repo subcommand.

**Comment by lgierth** [comment]
Would `ipfs refs local | grep <hash>` do what you want?

**Comment by Kubuxu** [comment]
Yes it would but it is O(n) where n is local blocks. Just lookup would be O(1).

**Comment by lgierth** [comment]
We can do hash lookups in O(1)? Cool.

**Comment by Kubuxu** [comment]
We can check if the hash is available in faltfs, in theory it should be O(1), depends on underlying file system implementation.

**Comment by slothbag** [comment]
If the IPFS daemon is not running a `ipfs object get Qm12345` will return immediately with an answer if the content is in the repo or not.  But would be nice to have this functionality when the daemon is running.

**Comment by lidel** [comment]
These days this can be done via:
- single block: `ipfs block get CID --offline`
- entire dag: `ipfs dag stat CID --offline`
