### ISSUE TITLE
--unrestricted-api

### ISSUE THREAD

**Issue by daviddias** [ipfs/kubo#3058]
Now, CORS also requests the "Access-Control-Allow-Credentials" to be set to true.

Can we have the --unrestricted-api to add that flag as well? The full list is:

```
      "Access-Control-Allow-Origin": [
        "http://localhost:5001",
        "http://localhost:8888"
      ],
      "Access-Control-Allow-Methods": [
        "PUT",
        "GET",
        "POST"
      ],
      "Access-Control-Allow-Credentials": [
        "true"
      ]
```

//cc @whyrusleeping

**Comment by whyrusleeping** [comment]
I think that makes sense to do. That flag should really mean "let me do whatever i want with the API now"

**Comment by jbenet** [comment]
It probably should say --insecure-api to be super clear.

ipfs daemon --president-madagascar=false

**Comment by whyrusleeping** [comment]
`ipfs daemon --world-domination=true --do-that-one-thing-with-the-giraffe=false --redisenable-discombobulated-inhibitors`

Yeah, lets make things do what they say

**Comment by travisperson** [comment]
`ipfs --i-know-what-im-doing` because if you have to ask what it does, you probably shouldn't be using it.

**Comment by magik6k** [comment]
I'd like to avoid adding new flags to the daemon, but if this can be set through config, we may just add a config profile for this.
