### ISSUE TITLE
IPFS uses way too many threads

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/kubo#3064]
On linux (and likely on BSDs and OSX) ipfs uses way too many threads. This is caused by an improperly implemented [reuseport library](https://github.com/jbenet/go-reuseport). We should prioritize fixing this as it results in excess memory usage and greatly increases the number of kernel context switching.

**Comment by Kubuxu** [comment]
Here is IPFS using over 800 system threads: fs:/ipfs/QmQH3uwcpp9AEnNXnGTBhQ4oUahQXCvE2jSdFzY33q8Fm7

**Comment by pjz** [comment]
Will this be helped by #3093 (Move to requiring go1.7) ?

**Comment by whyrusleeping** [comment]
@pjz It might help a little,  but the primary problem is our poor use of epoll in go-reuseport.

**Comment by Jorropo** [comment]
Between newer releases of go and their runtime improvements, openssl support removed and fixes to reuse port I havn't seen this being an issue in a while.
On my 6c/12t machine it often stays at ~15 never breaking 30 so I would say it's good.
