### ISSUE TITLE
Extract gateway code to go-ipfs-gateway

### ISSUE THREAD

**Issue by ghost** [ipfs/kubo#3171]
The gateway code in the `core/corehttp` package should be moved out into its own repository, to ease further development, and specification of the gateway's semantics. The new repository is go-ipfs-gateway at https://github.com/ipfs/go-ipfs-gateway

If the gateway is to be separate, it _can't_ depend on go-ipfs internals as it does now, so it first needs to adopt the core-api interface.

Dependencies:
- [ ] #2876 Gateway uses minimal IPFS Core API

**Comment by BigLep** [comment]
Replaced by more recent item: https://github.com/ipfs/kubo/issues/8524
