### ISSUE TITLE
ipfs get: seed/pin file so other can get it

### ISSUE THREAD

**Issue by alphaCTzo7G** [ipfs/kubo#4084]
#### Description:
BTorrent typically get a file and automatically starts seeding the file. However, "ipfs get" doesnt have this sort of behavior. 

 IPFS seems similar to a two-sided market place and needs some kind of viral growth mechanism. Should this be the default behavior? "IPFS get" seems to be the simplest command to obtain files.

**Comment by Stebalien** [comment]
You have to run it as a daemon to get that behavior. By default, `ipfs get` starts up, downloads the file, and then shuts down. If you run it as a daemon in the background, it will continue serving the file (until it gets garbage collected).

**Comment by whyrusleeping** [comment]
I think this question has been answered, closing now. Please reopen if further clarification is needed.

**Comment by mitar** [comment]
Hm, should `get` have a `--pin` flag (maybe even on by default) so that it prevent garbage collection?

**Comment by Stebalien** [comment]
@mitar possibly although I wouldn't make it on by default as `get` is usually used when you want to move something from the network to your local disk (only incidentally caching it in ipfs). If you want something to *stay* in ipfs, I'd run `ipfs pin add ... && ipfs get ...`.

**Comment by Jorropo** [comment]
`ipfs get` now refuse to download from internet if blocks are missing from the local datastore.
If you run a daemon it does `O(-1)` reseeding.
