### ISSUE TITLE
Low Power Mode

### ISSUE THREAD

**Issue by jcgruenhage** [ipfs/kubo#4137]
#### Description:
IPFS on Android (with IPFSDroid) already works kinda well, but having the app running is currently not an option, because it sucks your battery empty in no time. Would it be possible, to implement an API call, that switches a node into low power (and possibly also into low bandwidth) mode, so that running this on mobile devices is more doable? Killing the node all the time would be another way, but that does kinda defeat the purpose of IPFS.

**Comment by Kubuxu** [comment]
First step would be probably running go-ipfs in DHT client mode:
`ipfs daemon --routing=dhtclient`

We are working on connection closing which should further reduce the number of connections thus bandwidth and power usage.

**Comment by jcgruenhage** [comment]
Thanks :)

**Comment by whyrusleeping** [comment]
Yeah, as @Kubuxu pointed out you probably want to use `--routing=dhtclient`. Its probably also worth turning off the reprovider with: `ipfs config Reprovider.Interval "0"` so your node doesnt rebroadcast all this things it has every 12 hours.

**Comment by Stebalien** [comment]
Note: Bitswap sessions (https://github.com/ipfs/go-ipfs/issues/3786) will help reduce background traffic significantly.

**Comment by jbshirk** [comment]
Cross ref
https://discuss.ipfs.io/t/sweet-ipfs-full-ipfs-node-for-android/3779/16

**Comment by Hazae41** [comment]
Sweet-IPFS 0.2.2 adds a "low power" mode by using this config
```
"Swarm": {
    "ConnMgr": {
      "LowWater": 20,
      "HighWater": 100,
      "GracePeriod": "80s"
    }
  }
```

**Comment by lidel** [comment]
`lowpower` [profile](https://github.com/ipfs/kubo/blob/master/docs/config.md#profiles)  was implemented a while ago. it is shutting down various things to decrease impact on battery:

https://github.com/ipfs/kubo/blob/6f730dc268c3712d65efb5b0ab251a714cb85ec4/config/profile.go#L171-L187

Future work would be to default to a pool of [gateways hosting blocks / CARs](https://docs.ipfs.tech/reference/http/gateway/#trustless-verifiable-retrieval) and starting up P2P/DHT only as a fallback.
