### ISSUE TITLE
Consider adding "Docs generation" on every release

### ISSUE THREAD

**Issue by daviddias** [ipfs/kubo#4163]
The [docs page on ipfs.io](https://ipfs.io/docs/api/) was really out of date. Can we add an item to the release checklist to ensure that it gets done on every release? 

@hsanjuan made a tool that is really simple to use - https://github.com/ipfs/http-api-docs

PS: I searched for the Release Checklist document to update it directly, but couldn't find it in this repo neither in the ipfs/community. Does it even exist or the release checklist is just a c&p from the previous release? (I think it does exist, I remember that @mishmosh updated it once but maybe it was just an update to the js-ipfs one??!)

**Comment by Kubuxu** [comment]
https://github.com/ipfs/go-ipfs/blob/master/docs/releases.md

**Comment by diasdavid** [comment]
cool, PR here: https://github.com/ipfs/go-ipfs/pull/4165
