### ISSUE TITLE
Run tests of every http client library (that is feature complete) on pre-release and notify devs of changes

### ISSUE THREAD

**Issue by daviddias** [ipfs/kubo#4164]
There is a awesome set of http client libraries that were built by the community. It would be really helpful if the tests on those libraries were run on pre release, it will help us find regressions and also inform the owners of those packages that they need to update them.

Discussion issue - https://github.com/ipfs/ipfs/issues/83

**Comment by whyrusleeping** [comment]
We need an easy way to run all of these at once. Maybe some meta repo that pulls all these different libs down and runs their test against a given daemon
