### ISSUE TITLE
Add changelog to GitHub releases

### ISSUE THREAD

**Issue by baimafeima** [ipfs/kubo#4217]
Could you make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by whyrusleeping** [comment]
@baimafeima we already generate our changelogs from github PRs. Do you have links to docs on how to add the changelogs to the releases page?

**Comment by whyrusleeping** [comment]
Ah, found it: https://github.com/ipfs/go-ipfs/releases/new

**Comment by Jorropo** [comment]
We now post changelog in the github releases.
