### ISSUE TITLE
Integration testing with Peergos

### ISSUE THREAD

**Issue by ianopolous** [ipfs/kubo#4346]
#### Version information:
all

#### Type:
Enhancement

#### Severity:
Low

#### Description:
After discussion with @whyrusleeping I've setup the ipfs specific unit tests for peergos so that they can be integrated into your unit testing. 

The requirements are java 8, and ipfs running on localhost on the usual port. Currently there are 24 tests and they take about 6 minutes to run. 

How does the following sound? 
Checkout, build and run the tests directly from our repo (This will require ant and the jdk as well). For this we would probably create a special branch for you which is more stable than master. 
If that sounds okay, then I'll write up the commands necessary.

**Comment by lgierth** [comment]
cc @VictorBjelkholm 

Also @whyrusleeping I guess Peergos would be good to test the commands refactoring against?

**Comment by whyrusleeping** [comment]
@lgierth I *think* @ianopolous has tested against that branch and been successful. 

@ianopolous mind trying that again just to be sure?

**Comment by ianopolous** [comment]
Yep I had previously tested feat/commands2.0. I'm trying to build the latest on it, and it always hangs trying to get the first dependency in make install:
[get ] [fetch]   go-ipfs-cmds             QmTb4KszUHSdLPhwNyCX3aX6ugezhkhZe2b9Cf4YbMWBuj
[0 / 166] 480s....

**Comment by whyrusleeping** [comment]
@keks did you pin the latest package?

**Comment by keks** [comment]
Whoops! I did now.

**Comment by ianopolous** [comment]
I can confirm all our tests pass on feat/commands2.0/7d2039a3d

**Comment by ianopolous** [comment]
Here are the commands to run our tests (assumes java8 and ant are installed, and a local ipfs daemon is running):
```
git clone https://github.com/Peergos/Peergos.git
cd Peergos
ant ipfs_tests
```
And this will produce output like the following:`

```
Buildfile: /home/ian/Peergos/build.xml

clean:
   [delete] Deleting directory /home/ian/Peergos/build
   [delete] Deleting directory /home/ian/Peergos/dist

init:
    [mkdir] Created dir: /home/ian/Peergos/build

compile:
    [javac] Compiling 189 source files to /home/ian/Peergos/build
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.

dist:
    [mkdir] Created dir: /home/ian/Peergos/dist/lib
     [copy] Copying 6 files to /home/ian/Peergos/dist/lib
      [jar] Building jar: /home/ian/Peergos/dist/PeergosServer.jar
     [copy] Copying 1 file to /home/ian/Peergos

ipfs_tests:

execute.test:
    [junit] Running peergos.server.tests.IpfsUserTests
    [junit] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 395.849 sec

BUILD SUCCESSFUL
Total time: 6 minutes 44 seconds
```
It also creates a more detailed log in test.reports/TEST-peergos.server.tests.IpfsUserTests.xml

**Comment by jacobheun** [comment]
In js-ipfs we do run some external test suites in CI. It would ideal to do this here as well to help reduce the testing cycle of future releases.

**Comment by ianopolous** [comment]
Closing this as we use [ipfs-nucleus](https://github.com/peergos/ipfs-nucleus/) now.
