### ISSUE TITLE
IPNS broken?

### ISSUE THREAD

**Issue by The-Soulless** [ipfs/kubo#4984]
#### Version information:
ipfs version 0.4.14

#### Type:
Bug

#### Description:
I installed ipfs yesterday and things were going great, but certain websites weren't working (Loading for a long time and then spitting out an error), I just thought that they were broken for the time being, then today I noticed that only websites that are using ipns are broken, the error messages they spit out are
`ipfs resolve -r /ipns/(hash) Could not resolve name.`
This happens too when using the terminal.

Images:
https://a.uguu.se/UvEuqpimV31s_tmp.m5xtiMRmPy.png
https://a.uguu.se/VJpMlGcGMyQq_tmp.uE9Aiy7PZN.png

**Comment by FingerLiu** [comment]
Same here when I try to run command in READEME  `ipfs cat /ipns/dist.ipfs.io/go-ipfs/versions
 `
