### ISSUE TITLE
/api/v0/get documentation out of date

### ISSUE THREAD

**Issue by tdiesler** [ipfs/kubo#5242]
#### Version information:

go-ipfs version: 0.4.16-
Repo version: 7
System version: amd64/darwin
Golang version: go1.10.2

#### Type:

Question, Documentation

#### Description:

The docs for [/api/v0/get](https://ipfs.io/docs/api/#apiv0get) says

```
On success, the call to this endpoint will return with 200 and the following body:

This endpoint returns a `text/plain` response body.
```

However, for this call ...

```
curl "http://localhost:5001/api/v0/get?arg=/ipfs/QmUD7uG5prAMHbcCfp4x1G1mMSpywcSMHTGpq62sbpDAg6"
```

I get 

```
QmUD7uG5prAMHbcCfp4x1G1mMSpywcSMHTGpq62sbpDAg60000644000000000000000000000005413323150346017022 0ustar0000000000000000The quick brown fox jumps over the lazy dog.
```

Please advice how to decode this and perhaps also fix the related docs.

**Comment by tdiesler** [comment]
Related to: https://github.com/ipfs/java-ipfs-api/issues/78

**Comment by ianopolous** [comment]
The start looks like it is a Multihash pointing to the raw file contents, which are themselves at the end. After multihash it looks like file permissions, and modification dates. I'm not aware of convenient documentation of the format, but I believe it is protobuf. Why do you need the raw protobuf? Can you use the _ipfs cat_ call instead?

**Comment by tdiesler** [comment]
Yes, ipfs cat works in java-ipfs-api. Now trying with cat and how this plays out with directories ...

**Comment by Stebalien** [comment]
It returns a tarfile by default.

**Comment by Dendiom** [comment]
So, is there any way to get the origin file through http api?

**Comment by Stebalien** [comment]
@Dendiom `api/v0/cat/Qm...` will return a single file literally.

**Comment by Dendiom** [comment]
@Stebalien  Thank you for your response! But when I try this api in my browser，it just returns the file content and doesn't save it into a file like api/v0/get. Is there anything wrong with my operation？Thank you.

**Comment by Stebalien** [comment]
`api/v0/get` saves it to a file because it returns a content type your browser can't display. `api/v0/cat` is returning a content type your browser *can* display so your browser won't open a save dialog. You'll have to manually save the file (right click, click save).

**Comment by Dendiom** [comment]
@Stebalien Thank you very much!

**Comment by tdiesler** [comment]
out-of-date
