### ISSUE TITLE
HTTPHeaders don't have an updated version

### ISSUE THREAD

**Issue by makew0rld** [ipfs/kubo#5882]
#### Version information:

```
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.4
```

#### Type:

bug

#### Description:

I ran `ipfs config API.HTTPHeaders` and this was the response:
```
{
  "Server": [
    "go-ipfs/0.4.17"
  ]
}
```
But as you can see above, my IPFS version is 0.4.18. I'm guessing this is just a simple bug, where someone forgot to update the headers?

**Comment by Stebalien** [comment]
These should not be written to the config file so I'm not sure what's going on. However, we override this at runtime so that config setting shouldn't change runtime behavior.

**Comment by Stebalien** [comment]
Ah. It looks like we *used* to write this to the config but we stopped doing this (and started applying them at runtime).

You can safely remove that config option.

**Comment by makeworld-the-better-one** [comment]
So I inited before this update, so maybe the bug is now that the config isn't automatically removed? It's a bit misleading now. Thanks for the explanation though.

**Comment by Stebalien** [comment]
Yeah, we should remove this config entry. However, we *usually* do stuff like this in repo migrations which we try to avoid.

Let's leave this open and try to remember to fix this the next time we need to write a migration.

**Comment by lidel** [comment]
No longer relevant, use `/api/v0/version` these days.
