### ISSUE TITLE
AutoRelay not working in private network

### ISSUE THREAD

**Issue by suutaku** [ipfs/kubo#6327]
`ipfs version 0.4.21-dev`
in our private network.
I have 6 bootstrap peers with public IP address and set the option:
`    "EnableAutoNATService": true,
    "EnableAutoRelay": true,
    "EnableRelayHop": true
`
About 400 peers in different network behind NAT (don't have public IP address), peers can connect to peers who is in the same local work. but peers in different local work can not connect to each other. Peers have set ` "EnableAutoRelay"` in value `true`.

I think this is why  download always failed.
how can I make all peers can connect to other?

**Comment by vyzo** [comment]
Are the relays being discovered through the DHT?
See also https://github.com/libp2p/go-libp2p/issues/612

**Comment by vyzo** [comment]
Also note that there is a 15min advertising delay.

**Comment by suutaku** [comment]
> Are the relays discovered through the DHT?
Ah, I think so. but only in same local network.  I got this:
```
JohnSuus-MacBook-Pro-4:build john$ ipfs --debug daemon 2>&1 | grep "relay"
17:34:26.164  INFO      relay: new relay stream from: Qmex3jtLqNYRaXcCXwJwWDF5N1EHqQhPtGJKed6UuE2oQ2 relay.go:251
17:34:26.172  INFO      relay: new relay stream from: QmS4ayDwQEkSj4FbXkQFfBsr1srwNFvjKqjTGUpQe4qHg1 relay.go:251
17:34:26.528  INFO      relay: new relay stream from: QmTNrbi8W2JNntDS7qavvx9AThW26vEGkkpwMbwkD1L5Cy relay.go:251
17:34:26.770  INFO      relay: new relay stream from: QmRpN9CN3ufdHbz3eZq3T1cf7W8j4ca9oZC7vbNZKRzrxx relay.go:251
```
all of them are in the same local work of my device.

**Comment by suutaku** [comment]
by the way. p2p-circuit can reach other peer behind NAT. but not going to connect automatically. 
I mean my  
```
"HighWater": 900,
 "LowWater": 200,
```
but my device only get 6-7 peers connected(by running` ipfs swarm peers`). why not 100 or more? it's normal ?

**Comment by suutaku** [comment]
@vyzo 
After open all flags on peers both internet peers and NATed peers and restart daemon. I got this message:
```
13:44:35.258 DEBUG      relay: dialing peer QmTNrbi8W2JNntDS7qavvx9AThW26vEGkkpwMbwkD1L5Cy through relay Qmex3jtLqNYRaXcCXwJwWDF5N1EHqQhPtGJKed6UuE2oQ2 relay.go:138
```

looks like internet peers can relay  internet peers to NATed peers( makes no sense,  all peers can connect them without relay) but local peers relay still not working.

**Comment by vyzo** [comment]
Are the local peers in the same local network as the relay?

**Comment by suutaku** [comment]
> Are the local peers in the same local network as the relay?

I've tried make all peers in local network
```
"EnableAutoNATService": true, "EnableAutoRelay": true, "EnableRelayHop": true
```
but still not working. They just connected  through local IP.
```
/ip4/192.168.0.176/tcp/61859/ipfs/QmVHJcEMJuQDq8PD9QFNBwev2xn8QCKTq8oa92B5w1hVHd
```

**Comment by vyzo** [comment]
That's kind of expected, if they can connect to each other in the local network they will.

**Comment by suutaku** [comment]
ok.....
but I can not connect peers in different network.
if I switch my device to different network (mobile WIFI etc.) and I only get 6 boostrap peers! there are total 400+ peers in my private ipfs network!

**Comment by vyzo** [comment]
Is the DHT actually working on your private network? Autorelay can't work without it currently (but I am working on an improvement that would allow it to see known relays from passive discovery).

**Comment by suutaku** [comment]
Some log info.
```
16:59:51.458 DEBUG      relay: error opening relay stream to QmUuyn8b1kBwMN6hCpjpFrRBo3Bg5miGjVebnbEwZh4naD: no usable connection to peer relay.go:305
16:59:51.458 WARNI      relay: relay error: HOP_NO_CONN_TO_DST (260) relay.go:465
16:59:52.293 DEBUG       mdns: starting mdns query mdns.go:129
16:59:52.295 DEBUG       mdns: Handling MDNS entry: 192.168.0.179:4001 QmZCuEvVZt5X3SdRGnrf2vUtk6nwcEsJTUjaEZ1puPhcz9 mdns.go:155
16:59:52.295 DEBUG       mdns: got our own mdns entry, skipping mdns.go:163
16:59:52.430 DEBUG       mdns: Handling MDNS entry: 192.168.0.140:4001 Qmex3jtLqNYRaXcCXwJwWDF5N1EHqQhPtGJKed6UuE2oQ2 mdns.go:155
16:59:52.430 DEBUG       mdns: Handling MDNS entry: 192.168.0.198:4001 QmS4ayDwQEkSj4FbXkQFfBsr1srwNFvjKqjTGUpQe4qHg1 mdns.go:155
16:59:52.430 DEBUG       mdns: Handling MDNS entry: 127.0.0.1:4001 QmVHJcEMJuQDq8PD9QFNBwev2xn8QCKTq8oa92B5w1hVHd mdns.go:155
16:59:52.430 WARNI    p2pnode: trying peer info:  {Qmex3jtLqNYRaXcCXwJwWDF5N1EHqQhPtGJKed6UuE2oQ2: [/ip4/192.168.0.140/tcp/4001]} discovery.go:23
16:59:52.430 WARNI    p2pnode: trying peer info:  {QmVHJcEMJuQDq8PD9QFNBwev2xn8QCKTq8oa92B5w1hVHd: [/ip4/127.0.0.1/tcp/4001]} discovery.go:23
16:59:52.430 WARNI    p2pnode: trying peer info:  {QmS4ayDwQEkSj4FbXkQFfBsr1srwNFvjKqjTGUpQe4qHg1: [/ip4/192.168.0.198/tcp/4001]} discovery.go:23
16:59:52.440 DEBUG  bootstrap: QmZCuEvVZt5X3SdRGnrf2vUtk6nwcEsJTUjaEZ1puPhcz9 core bootstrap skipped -- connected to 5 (> 4) nodes bootstrap.go:131
16:59:53.652 DEBUG  basichost: protocol negotiation took 854.387µs basic_host.go:274
16:59:53.652 DEBUG        dht: QmZCuEvVZt5X3SdRGnrf2vUtk6nwcEsJTUjaEZ1puPhcz9 adding QmS4ayDwQEkSj4FbXkQFfBsr1srwNFvjKqjTGUpQe4qHg1 as a provider for 'QmUKhuMXYswGcMsZv1NeHYNRqteWAVtV5t2rCepTX3Rdqx'
 handlers.go:351
16:59:53.652 DEBUG        dht: received provider QmS4ayDwQEkSj4FbXkQFfBsr1srwNFvjKqjTGUpQe4qHg1 for QmUKhuMXYswGcMsZv1NeHYNRqteWAVtV5t2rCepTX3Rdqx (addrs: [/ip4/127.0.0.1/tcp/4001 /ip4/192.168.0.198/tcp/4001 /ip6/::1/tcp/4001]) handlers.go:368
16:59:57.295 DEBUG       mdns: mdns query complete mdns.go:142
17:00:02.292 DEBUG       mdns: starting mdns query mdns.go:129
17:00:02.293 DEBUG       mdns: Handling MDNS entry: 192.168.0.179:4001 QmZCuEvVZt5X3SdRGnrf2vUtk6nwcEsJTUjaEZ1puPhcz9 mdns.go:155
17:00:02.293 DEBUG       mdns: got our own mdns entry, skipping mdns.go:163
17:00:02.297 DEBUG       mdns: Handling MDNS entry: 192.168.0.198:4001 QmS4ayDwQEkSj4FbXkQFfBsr1srwNFvjKqjTGUpQe4qHg1 mdns.go:155
17:00:02.297 DEBUG       mdns: Handling MDNS entry: 127.0.0.1:4001 QmVHJcEMJuQDq8PD9QFNBwev2xn8QCKTq8oa92B5w1hVHd mdns.go:155
17:00:02.297 DEBUG       mdns: Handling MDNS entry: 192.168.0.140:4001 Qmex3jtLqNYRaXcCXwJwWDF5N1EHqQhPtGJKed6UuE2oQ2 mdns.go:155
17:00:02.297 WARNI    p2pnode: trying peer info:  {Qmex3jtLqNYRaXcCXwJwWDF5N1EHqQhPtGJKed6UuE2oQ2: [/ip4/192.168.0.140/tcp/4001]} discovery.go:23
17:00:02.297 WARNI    p2pnode: trying peer info:  {QmS4ayDwQEkSj4FbXkQFfBsr1srwNFvjKqjTGUpQe4qHg1: [/ip4/192.168.0.198/tcp/4001]} discovery.go:23
17:00:02.297 WARNI    p2pnode: trying peer info:  {QmVHJcEMJuQDq8PD9QFNBwev2xn8QCKTq8oa92B5w1hVHd: [/ip4/127.0.0.1/tcp/4001]} discovery.go:23
17:00:07.295 DEBUG       mdns: mdns query complete mdns.go:142
17:00:12.292 DEBUG       mdns: starting mdns query mdns.go:129
17:00:12.293 DEBUG       mdns: Handling MDNS entry: 192.168.0.179:4001 QmZCuEvVZt5X3SdRGnrf2vUtk6nwcEsJTUjaEZ1puPhcz9 mdns.go:155
17:00:12.293 DEBUG       mdns: got our own mdns entry, skipping mdns.go:163
17:00:12.356 DEBUG       mdns: Handling MDNS entry: 192.168.0.140:4001 Qmex3jtLqNYRaXcCXwJwWDF5N1EHqQhPtGJKed6UuE2oQ2 mdns.go:155
17:00:12.356 DEBUG       mdns: Handling MDNS entry: 192.168.0.198:4001 QmS4ayDwQEkSj4FbXkQFfBsr1srwNFvjKqjTGUpQe4qHg1 mdns.go:155
17:00:12.356 DEBUG       mdns: Handling MDNS entry: 127.0.0.1:4001 QmVHJcEMJuQDq8PD9QFNBwev2xn8QCKTq8oa92B5w1hVHd mdns.go:155
17:00:12.356 WARNI    p2pnode: trying peer info:  {QmVHJcEMJuQDq8PD9QFNBwev2xn8QCKTq8oa92B5w1hVHd: [/ip4/127.0.0.1/tcp/4001]} discovery.go:23
17:00:12.356 WARNI    p2pnode: trying peer info:  {QmS4ayDwQEkSj4FbXkQFfBsr1srwNFvjKqjTGUpQe4qHg1: [/ip4/192.168.0.198/tcp/4001]} discovery.go:23
17:00:12.356 WARNI    p2pnode: trying peer info:  {Qmex3jtLqNYRaXcCXwJwWDF5N1EHqQhPtGJKed6UuE2oQ2: [/ip4/192.168.0.140/tcp/4001]} discovery.go:23
17:00:13.153 DEBUG  basichost: protocol negotiation took 72.719µs basic_host.go:274
17:00:13.153  INFO      relay: new relay stream from: QmS4ayDwQEkSj4FbXkQFfBsr1srwNFvjKqjTGUpQe4qHg1 relay.go:229
17:00:13.153 DEBUG     swarm2: [QmZCuEvVZt5X3SdRGnrf2vUtk6nwcEsJTUjaEZ1puPhcz9] opening stream to peer [QmUuyn8b1kBwMN6hCpjpFrRBo3Bg5miGjVebnbEwZh4naD] swarm.go:280
17:00:13.153 DEBUG      relay: error opening relay stream to QmUuyn8b1kBwMN6hCpjpFrRBo3Bg5miGjVebnbEwZh4naD: no usable connection to peer relay.go:305
17:00:13.153 WARNI      relay: relay error: HOP_NO_CONN_TO_DST (260) relay.go:465
17:00:17.294 DEBUG       mdns: mdns query complete mdns.go:142

```
And config 
```
 "Routing": {
    "Type": "dht"
  },
```

**Comment by vyzo** [comment]
The `HOP_NO_CONN_TO_DST` errors you get mean that the target peer was not connected to the relay.

**Comment by suutaku** [comment]
> The `HOP_NO_CONN_TO_DST` errors you get mean that the target peer was not connected to the relay.

Yes,it is. 
Even peer connected to relay noting different and today, maybe I found another bug in dht. this my local device can not get object from peers either  in local work or bootstrap randomly. I mean A,B was connected to each other, A add a object and run 
```
ipfs get <hash>
```
some times it's hanging, nothing return.
 it's some kind of dht delay?
I'm so sorry to make so many troubles to your guys everyday. >.<

**Comment by Wenlong0913** [comment]
@suutaku @vyzo  Hey, I'm facing the same issue when trying the private ipfs network. 
In my case, the bootstrap nodes were hosted in aws ec2 instances with public IP (let's call it **env1**), other machines are hosted in my home and currently sharing the same public IP (let's call it **env2**). The PCs in my local environment are able to connect to the bootstrap nodes and the other nodes in the same network.

The question is, when I use a third device to connect to my private network, e.g., my mobile which is working on a different network (i.e., not in sharing my home's public ip, not in aws ec2 instances, the have its own public ip, let's call it env3), it can only discover the bootstrap nodes.

When I add a file from **env2**, the file can only be accessed by the nodes in **env1**，however, in **ev3**, there is no response.

The private network is established under this [guideline](https://github.com/ipfs/go-ipfs/blob/ce78064335c9923abb6540dc7a3cd512672a62bc/docs/experimental-features.md#private-networks).

**Comment by lidel** [comment]
Closing as we've removed Relays V1 from Kubo and replaced them with [Circuit Relay v2](https://github.com/libp2p/specs/blob/master/relay/circuit-v2.md).

**Comment by ldhios** [comment]
> Wenlong0913

hi， i have same issue with  private network.  how do you fix it?
