### ISSUE TITLE
Patch Releases

### ISSUE THREAD

**Issue by Stebalien** [ipfs/kubo#6405]
Currently, all go-ipfs releases are "patch" releases. IIRC, this was because we decided to bump to 0.5.0 when we hit beta. Unfortunately, this means we can't issue _actual_ patch releases and means that issues like https://github.com/ipfs/go-ipfs/issues/6254.

Proposal:

1. Start cutting 0.x.0 releases starting with 0.5.0.
2. Create patch releases as-needed that cherry-pick specific changes/commits.

These patch releases:

* Would _not_ go through the full release process.
* Would only contain specific fixes for specific _regressions_.
* Would not contain complicated fixes for complicated issues.
* Would be issued on an as-need basis based on impact

cc @ipfs/wg-go-core

**Comment by b5** [comment]
as a project with go-ipfs as a dependency, this would be lovely. _Especially_ now that gomod.

**Comment by Stebalien** [comment]
Note: We have no intention (yet) to _backport_ fixes to previous versions.

**Comment by momack2** [comment]
Excited for this! @Stebalien - can we open an issue for 0.5.0 - the next minor release - and start giving early visibility into things that will be changing (esp any changes to "default" behavior!)? This gives a master view of the checklist of features planned for this release - which is really important for coordination and expectation-setting given the number of things on the list!

**Comment by Jorropo** [comment]
We now bump the minor on each release and publish release worthy patches as patch releases,
For example [`v0.19.2`](https://github.com/ipfs/kubo/releases/tag/v0.19.2)
