### ISSUE TITLE
`ipfs daemon --offline` is not listed when calling `ipfs daemon --help`

### ISSUE THREAD

**Issue by eugene-babichenko** [ipfs/kubo#6639]
#### Location

`ipfs daemon --help`

#### Description

IPFS daemon has the `--offline` flag, which is very useful for the development purposes. However, this flag is not listed under the `ipfs daemon --help` command and I have found it accidentally while looking through the `--allow-offline` issues.

**Comment by eugene-babichenko** [comment]
Thanks for clarifying on that. I think I might be able to work on that in the next few days.

**Comment by Stebalien** [comment]
Awesome! Thanks!
