### ISSUE TITLE
Prioritize connection via /ip4/ over /p2p-circuit/

### ISSUE THREAD

**Issue by wngr** [ipfs/kubo#6755]
We're running a private swarm, where the nodes are usually within the same LAN. However, we provide a common bootstrap node, especially to connect from e.g. dev machines to those machines in a common LAN, behind a NAT.

We tried experimenting with https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#autorelay, which seems to work well. However, nodes within the same LAN started now being connected to through the `p2p-circuit` rather than a direct connection.

```
bash-4.4# ipfs swarm peers | grep QmY2XuqnpUNEmL9FPWk9eQYMEjAcUUCFhSnX6A7wTZYzwn
/ipfs/QmaWM8pMoMYkJrdbUZkxHyUavH3tCxRdCC9NYCnXRfQ4Eg/p2p-circuit/ipfs/QmY2XuqnpUNEmL9FPWk9eQYMEjAcUUCFhSnX6A7wTZYzwn
bash-4.4# ipfs dht findpeer QmY2XuqnpUNEmL9FPWk9eQYMEjAcUUCFhSnX6A7wTZYzwn
/ip6/::1/tcp/4001
/ip4/127.0.0.1/tcp/4001
/ip4/172.26.200.207/tcp/4001
bash-4.4# ipfs swarm connect /ip4/172.26.200.207/tcp/4001/ipfs/QmY2XuqnpUNEmL9FPWk9eQYMEjAcUUCFhSnX6A7wTZYzwn
connect QmY2XuqnpUNEmL9FPWk9eQYMEjAcUUCFhSnX6A7wTZYzwn success
bash-4.4# ipfs swarm peers | grep QmY2XuqnpUNEmL9FPWk9eQYMEjAcUUCFhSnX6A7wTZYzwn
/ipfs/QmaWM8pMoMYkJrdbUZkxHyUavH3tCxRdCC9NYCnXRfQ4Eg/p2p-circuit/ipfs/QmY2XuqnpUNEmL9FPWk9eQYMEjAcUUCFhSnX6A7wTZYzwn
bash-4.4# ipfs swarm disconnect /ipfs/QmaWM8pMoMYkJrdbUZkxHyUavH3tCxRdCC9NYCnXRfQ4Eg/p2p-circuit/ipfs/QmY2XuqnpUNEmL9FPWk9eQYMEjAcUUCFhSnX6A7wTZYzwn
disconnect QmY2XuqnpUNEmL9FPWk9eQYMEjAcUUCFhSnX6A7wTZYzwn success
bash-4.4# ipfs swarm peers | grep QmY2XuqnpUNEmL9FPWk9eQYMEjAcUUCFhSnX6A7wTZYzwn
bash-4.4# ipfs swarm connect /ip4/172.26.200.207/tcp/4001/ipfs/QmY2XuqnpUNEmL9FPWk9eQYMEjAcUUCFhSnX6A7wTZYzwn
connect QmY2XuqnpUNEmL9FPWk9eQYMEjAcUUCFhSnX6A7wTZYzwn success
bash-4.4# ipfs swarm peers | grep QmY2XuqnpUNEmL9FPWk9eQYMEjAcUUCFhSnX6A7wTZYzwn
/ip4/172.26.200.207/tcp/4001/ipfs/QmY2XuqnpUNEmL9FPWk9eQYMEjAcUUCFhSnX6A7wTZYzwn
```

Now I basically have two issues here:
* The peers rather connect via the p2p-circuit than the ip4 to each other
* When explicitly running `swarm connect`, the existing p2p-circuit connection is not replaced by the ip4 connection (probably because the relevant peer id is already connected and the command exits quickly)

I propose to introduce some sort of quality index for the different channels – or maybe there is already a feature for it?

Let me know if you need more info.

**Comment by Stebalien** [comment]
Agreed. There was effort underway in https://github.com/libp2p/go-libp2p-swarm/pull/122 but it's currently stalled.

**Comment by agowa338** [comment]
Please don't forget `/ipv6/`, we've an IPv6 only network ;-)

**Comment by Stebalien** [comment]
We should filter out IPv4 addresses when there's no way that dialing
them will work. However, if you have an IPv6 only network, all IPv4
dials will fail immediately anyways so it won't really matter.

**Comment by Jorropo** [comment]
Happens now with go-libp2p `v0.29.0` and smart dialling:

https://github.com/ipfs/kubo/blob/release-v0.22.0/docs/changelogs/v0.22.md#go-libp2p-v0290-update-with-smart-dialing
