### ISSUE TITLE
Coalescing the go-ipfs project repos

### ISSUE THREAD

**Issue by daviddias** [ipfs/kubo#6862]
Back in Jan 13, me, @Stebalien and @hsanjuan sat down and discussed a potential endeavor to decrease the repo surface area of go-ipfs. The result was a lit of repos and action items for each (merge into another repo, move to another org and/or deprecated)

The list is here:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/1211152/73647817-e1840180-46ae-11ea-9fa5-752888377991.png">
<img width="458" alt="image" src="https://user-images.githubusercontent.com/1211152/73647825-e6e14c00-46ae-11ea-9b7a-5a1d74961624.png">

Next steps is for @hsanjuan to take a new look at this list from the eyes of the new developer experience special interest group.

**Comment by Stebalien** [comment]
Note: this isn't happening till 0.5.0 is out.

**Comment by daviddias** [comment]
libp2p has started https://github.com/libp2p/go-libp2p/issues/829

**Comment by rvagg** [comment]
I wouldn't mind some (or all) of the go-ipld repos across to the ipld org. In particular I'm working on some btc, zcash and eth stuff at the moment and would like to work on those libraries. We already have js-ipld-* versions in the ipld org so the Go ones may as well move too unless someone's particularly attached to them here.

**Comment by hsanjuan** [comment]
@rvagg ack, will do.

**Comment by hsanjuan** [comment]
We had a convo and are probably going to merge go-block-format into go-ipld-format (not immediately, but soon).

**Comment by Stebalien** [comment]
Please be careful. Moving libraries in go is not trivial because import paths need to be updated. See what I did for https://github.com/ipfs/go-car/.

**Comment by hsanjuan** [comment]
> Please be careful. Moving libraries in go is not trivial because import paths need to be updated. See what I did for https://github.com/ipfs/go-car/.

Correct, will move and alias to avoid breakage.

**Comment by Stebalien** [comment]
Something we forgot: We need to:

1. Re-extract the gateway to https://github.com/ipfs/go-ipfs-gateway/. At this point, the gateway code takes a CoreAPI so it should be easy to extract.
2. Move https://github.com/ipfs/dir-index-html into the gateway code.

**Comment by momack2** [comment]
Is the gateway extraction something @thattommyhall could implement?

otherwise, is it safe to assume this migration work is on-hold for now?

**Comment by Stebalien** [comment]
The gateway extraction should be simple, I think.

**Comment by Jorropo** [comment]
This has essentially more or less happend with the [`boxo`](https://github.com/ipfs/boxo) monorepo

**Comment by Jorropo** [comment]
Did not meant to close, there is stuff inside Kubo that could be worth moving.
