### ISSUE TITLE
http://127.0.0.1:5001/api/v0/object/get not support CIDv1 ?

### ISSUE THREAD

**Issue by garyng2000** [ipfs/kubo#7384]
this is what I get "expected protobuf dag node" 

if I add using cid-version=1(getback the base32 hash) and feed to the api end point

**Comment by garyng2000** [comment]
yet the command line 'ipfs object get <cidv1hash>' works. forget to say v0.5.1 on windows

**Comment by garyng2000** [comment]
further testing shows that this is just a corner case not handled.

I deliberately added a 0 length file using cid-version=1 which would cause the problem. If I turn off raw-leave at the same time, it is fine. 

So to summarize :

cid-version=1&raw-leaves=true with empty file(0 length) would choke the object/get and a few other calls.

I have turned raw-leaves=false for now.

**Comment by Stebalien** [comment]
You're correct, the issue is with raw leaves. The `object` commands are designed for the dag-pb IPLD format and only work with this format. However, raw leaves use the _raw_ IPLD format.

I've filed an issue for fixing the documentation: https://github.com/ipfs/go-ipfs/issues/7396
