### ISSUE TITLE
Improve DNSLink lookup for domains starting with www. prefix

### ISSUE THREAD

**Issue by leochan007** [ipfs/kubo#7700]
domain name with ".com" works well.   i can access to the website with url "xxxx.com"
but if i use a new domain name with ".asia" suffix show resolve error in browser.

"ipfs resolve -r /ipns/xxxxxxx.asia/: could not resolve name"

but i can access to the website with url "ipfs.io/ipns/xxxxx.asia"

e.g. these urls point to the same hash on ipfs network.
ipfs.com    ------------ok
https://gateway.pinata.cloud/ipns/ic-markets.asia/ ---------ok
ic-markets.asia ----------failed.

![1](https://user-images.githubusercontent.com/1071537/94408313-3416ae80-01a7-11eb-8656-67fa6a223855.png)
![2](https://user-images.githubusercontent.com/1071537/94408324-37119f00-01a7-11eb-8c27-40531a1cbdbe.png)

**Comment by aschmahmann** [comment]
@leochan007 this seems like it may be related to your local machine's configuration. Perhaps your DNS provider is blocking you from receiving the records (perhaps try Google's 8.8.8.8 or Cloudflare's 1.1.1.1).

As you've noted it works on the public gateways and FWIW it works on my machine too.

```
❯ ipfs resolve -r /ipns/ic-markets.asia
/ipfs/QmQVrSrUTmPDZ9atNRgoKR6bcVYkTxdhU6SdkQw5EiexZf
❯ ipfs name resolve /ipns/ic-markets.asia
/ipfs/QmQVrSrUTmPDZ9atNRgoKR6bcVYkTxdhU6SdkQw5EiexZf
❯ ipfs ls /ipns/ic-markets.asia
QmfUitRhmTFSnk8enNwC9voSRR5wkpAi5eDQyTfDP3kfVe -    assets/
QmXNUSHfzBZwXoEw61tR1rJMgk4NS3ggpKa92xxtqYESxs 1150 favicon.ico
QmWT3Yg3wpzmoFEcjvSuizWjJ71hjrzdbrUYdDfpQvFfNJ -    img/
Qmd331YWj6YEPL5hA5mikYgL3Sv4wWYY4yC8oaxuqWuhtB 2333 index.html
QmU9oPFmdmWRkgUdWF2bYdsrk9hgdvxPQT8q4o3tFWccdg 435  manifest.json
QmURdei4Wpwvx39zn2r7MNC8H2bZ3u1Ssky2oS7fRebJNc 24   robots.txt
```

**Comment by leochan007** [comment]
@aschmahmann thx for reply. but i mean this error shown on browser. it works on cmd.
i CANNOT access the website with url "www.ic-markets.asia". 

![3](https://user-images.githubusercontent.com/1071537/94510544-a049ee80-0249-11eb-8ea5-eaeffe4a032a.png)
![4](https://user-images.githubusercontent.com/1071537/94510546-a2ac4880-0249-11eb-8939-b17275d51706.png)

**Comment by leochan007** [comment]
www.ipfsol.com is ok.
![5](https://user-images.githubusercontent.com/1071537/94510664-e3a45d00-0249-11eb-9419-5f0188f6b7ad.png)

**Comment by leochan007** [comment]
@aschmahmann btw this website served on a public ipfs pinning service. not on my own laptop.

**Comment by aschmahmann** [comment]
@leochan007 works fine for me if you leave out the `www` (i.e. ic-markets.asia instead of www.ic-markets.asia) I suspect this is because you do not have a DNSLink specified for www.ic-markets.asia, but only for ic-markets.asia.

I suspect you could have `_dnslink.www.ic-markets.asia` have `dnslink=/ipns/ic-markets.asia` and that would work.

**Comment by lidel** [comment]
Additional context: some browser vendors add "www." if user types host without scheme:

- https://support.mozilla.org/en-US/questions/1183187
- https://www.thewindowsclub.com/browser-automatically-adds-www-to-url
- https://superuser.com/q/965229

For the sake of improved interop in browser context, I propose we special-case hostnames starting with `www.`:
1. detect DNSLink lookup for hostname that starts with www
2. if DNS TXT record is missing, make additional lookup for fqdn without www. prefix

This would remove need for setting up additional TXT record, and fix the problem on every website.

**Comment by leochan007** [comment]
one more requirement:  i wanna make sub domain name point to different hash path.

e.g. one ipfs hash path 1 -> www.xxxx.com
and another ipfs hash path 2 -> path2.xxxx.com
and hash path 3 -> path3.xxxx.com ?

how to set up thiz to cloudflare dns resolver ?

anybody can help?  thx a lot. 
@aschmahmann @lidel

**Comment by lidel** [comment]
@leochan007 you need to add DNSLink TXT record for each subdomain:
- `_dnslink.www.xxxx.com` for `www.xxxx.com`
- `_dnslink.path2.xxxx.com` for `path2.xxxx.com`
- `_dnslink.path3.xxxx.com` for `path3.xxxx.com`

**Comment by lidel** [comment]
DNSLink should remain a simple protocol to only look for `_dnslink` subdomain of the requested hostname.

People who want `www.` to work and don't want to update two TXT records in two places can `CNAME` `_dnslink.www.example.com` to point at `_dnslink.example.com`.

This way, only `_dnslink.example.com` needs to be updated.


Closing as there is no additional work to be done here. 
Up-to-date docs are at https://docs.ipfs.tech/concepts/dnslink/
