### ISSUE TITLE
Removing support for X-Ipfs-Gateway-Prefix

### ISSUE THREAD

**Issue by lidel** [ipfs/kubo#7702]
###  Probably not(?)

I searched [gh projects](https://github.com/search?q=%22X-Ipfs-Gateway-Prefix%22&type=code) and when this header is mentioned it is set to empty string "just in case" (or a repo is a fork of go-ipfs).

Looks like an old, long time dead feature, and that is for a reason: it was introduced in 2016 (https://github.com/ipfs/go-ipfs/pull/1971) and AFAIK the only use for it was displaying blog under `ipfs.io/blog`, which we stopped doing in 2018 (https://github.com/ipfs/blog/pull/182). 

### Why we stopped using it?

Since 2016 we realized nesting multiple gateway types under single Origin on the web is too complex and brittle. 
IPFS community moved towards dedicated Origins, which are much easier to isolate and reason about (we moved `ipfs.io/blog` to subdomain at `blog.ipfs.io`) and the need for `X-Ipfs-Gateway-Prefix` went away.

## Proposal: remove support for `X-Ipfs-Gateway-Prefix` 

Existence of this header makes gateway code harder to maintain, and suggests risky deployment decisions. Right now the header is already ignored in various places, but nobody seems to care to fill a bug report ;-) 

Instead of fixing it I'd like to remove it from `docs/config.md` and gateway code to decrease complexity, avoid origin-related bugs in the future, and make it more clear that one should mount only one DNSLink per Origin.

If someone is still depending on this header, please comment below describing your use case. 
A better way most likely exists.

## "But I AM using it!"

If you are using it, please comment below and describe your use case. 
Most likely there is a better/safer way to serve your use case these days.

**Comment by jbenet** [comment]
**this may be different, but:**
- I've seen problems on sites hosted with dns in some places where directory listings link to `$domain/ipfs/$hash/$path` instead of `$domain/$path`.
- recently i recall running into this with fleek. 

- example: https://slingshot.filecoin.io/media/logos/
- these should link to `https://slingshot.filecoin.io/media/logos/$filename` but instead link to `https://slingshot.filecoin.io/ipfs/QmZ33q4sWmnFXer6UMyAmx3J85ZhwarjXuRnDTzBp1auvG/media/logos/$filename` which ofc doesn't work.
- not sure if this is a misconfigured gateway or what.

**Comment by lidel** [comment]
@jbenet yes, it is different.

- it looks like a problem caused by additional revproxy/middleware on Fleek's end and the lack of DNSLink
- if they used DNSLink support directly, then the header would say:
  `Index of /ipns/slingshot.filecoin.io/media/logos/`

Will reach out and help them with solving this.

**Comment by Stebalien** [comment]
Deprecation proposal:

1. Print big warnings for the next release cycle with a request to open an issue. We should be able to see this in the config (I think?) and log/print on daemon start.
2. Remove it in the release cycle after that and refuse to start if it's configured.

**Comment by lidel** [comment]
Deprecation plan sgtm, with one note:
- This header is opt-in, comes from a reverse proxy like Nginx (it is not something one sets in go-ipfs config), so all we need to do is to print warning when header is present in a gateway request.

**Comment by BigLep** [comment]
@lidel : is the next step "Remove it in the release cycle after that and refuse to start if it's configured"?  Is this a good candidate for @schomatis ?
