### ISSUE TITLE
Failed 10-to-11 repo migration

### ISSUE THREAD

**Issue by gmasgras** [ipfs/kubo#7867]
#### Version information:
go-ipfs version: 0.9.0-dev-6d76c6e
Repo version: 11
System version: amd64/linux
Golang version: go1.14.4

#### Description:
The process fails to start due to an error in the migration. 
```
Jan 15 19:44:53 gateway-bank1-dc13 ipfs[3814732]: Initializing daemon...
Jan 15 19:44:53 gateway-bank1-dc13 ipfs[3814732]: go-ipfs version: 0.9.0-dev-6d76c6e
Jan 15 19:44:53 gateway-bank1-dc13 ipfs[3814732]: Repo version: 11
Jan 15 19:44:53 gateway-bank1-dc13 ipfs[3814732]: System version: amd64/linux
Jan 15 19:44:53 gateway-bank1-dc13 ipfs[3814732]: Golang version: go1.14.4
Jan 15 19:44:53 gateway-bank1-dc13 ipfs[3814732]: Found outdated fs-repo, migrations need to be run.
Jan 15 19:44:53 gateway-bank1-dc13 ipfs[3814732]:   => Looking for suitable fs-repo-migrations binary.
Jan 15 19:44:53 gateway-bank1-dc13 ipfs[3814732]:   => None found, downloading.
Jan 15 19:44:54 gateway-bank1-dc13 ipfs[3814732]:   => Running: /tmp/go-ipfs-migrate856570887/fs-repo-migrations -to 11 -y
Jan 15 19:44:54 gateway-bank1-dc13 ipfs[3814796]: Found fs-repo version 10 at /data/.ipfs
Jan 15 19:44:54 gateway-bank1-dc13 ipfs[3814796]: ===> Running migration 10 to 11...
Jan 15 19:44:54 gateway-bank1-dc13 ipfs[3814796]: applying 10-to-11 repo migration
Jan 15 19:44:54 gateway-bank1-dc13 ipfs[3814796]: locking repo at "/data/.ipfs"
Jan 15 19:44:54 gateway-bank1-dc13 ipfs[3814796]: > Upgrading pinning to use datastore
Jan 15 19:44:54 gateway-bank1-dc13 ipfs[3814796]:   - opening datastore at "/data/.ipfs"
Jan 15 19:44:55 gateway-bank1-dc13 ipfs[3814796]:   - importing from ipld pinner
Jan 15 19:44:55 gateway-bank1-dc13 ipfs[3814796]: ERROR: failed to convert ipld pin data into datastore
Jan 15 19:44:55 gateway-bank1-dc13 ipfs[3814796]: ERROR: failed to transfer pins: cannot find pinning root object: merkledag: not found
Jan 15 19:44:55 gateway-bank1-dc13 ipfs[3814796]: ipfs migration:  migration 10 to 11 failed: cannot find pinning root object: merkledag: not found
Jan 15 19:44:55 gateway-bank1-dc13 ipfs[3814732]:   => Failed: /tmp/go-ipfs-migrate856570887/fs-repo-migrations -to 11 -y
Jan 15 19:44:55 gateway-bank1-dc13 ipfs[3814732]: The migrations of fs-repo failed:
Jan 15 19:44:55 gateway-bank1-dc13 ipfs[3814732]:   migration failed: exit status 1
Jan 15 19:44:55 gateway-bank1-dc13 ipfs[3814732]: If you think this is a bug, please file an issue and include this whole log output.
Jan 15 19:44:55 gateway-bank1-dc13 ipfs[3814732]:   https://github.com/ipfs/fs-repo-migrations
Jan 15 19:44:55 gateway-bank1-dc13 ipfs[3814732]: Error: migration failed: exit status 1
Jan 15 19:44:55 gateway-bank1-dc13 systemd[1]: ipfs.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by gammazero** [comment]
The root pinning object, that the datastore thinks should be present, is missing from the block store.  Currently, the theory is that this is corruption that may have resulted from a forced OS restart and a filesystem with sync writes turned off.

**Comment by kylesmith63** [comment]
Facing same issue.

If i run image tag v.0.7.0 everything runs fine, as soon as i got to v0.8.0 or higher and it fails with the same error message as already mentioned.

**Comment by aschmahmann** [comment]
@kylesmith63 what happens when you run `ipfs pin ls` on v0.7.0?

**Comment by kylesmith63** [comment]
`ipfs pin ls` gives no output, I assume thats because nothing is pinned on my node right now. 

I probably should've mentioned also this is running in docker so not sure if I would be able to run ipfs-ds

**Comment by aschmahmann** [comment]
@kylesmith63 my guess is that like in the case above what happened is that somehow your empty pinset got corrupted (the above case had an empty pinset too). Running ipfs-ds would help with debugging, but you may be able to resolve this by just running go-ipfs v0.7.0 and pinning anything at all (e.g. QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn, the empty UnixFS directory).

**Comment by kylesmith63** [comment]
Looks like that solved the issue for me, Thanks!

**Comment by axelsimon** [comment]
Worked for me too. For anyone who needs more detailed instructions, this means running the following command:
`ipfs pin add QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn`

**Comment by SgtPooki** [comment]
this issue is useful for troubleshooting purposes, but since the issue has a workaround, i'm closing it.
