### ISSUE TITLE
Use go 1.16's new "embed" feature for embedding assets

### ISSUE THREAD

**Issue by Stebalien** [ipfs/kubo#7918]
Currently, we use an external bindata package but [Go 1.16](https://golang.org/pkg/embed/) will support this out of the box. We should switch over when Go 1.16 has been out for long enough to depend on it.

**Comment by FledgeXu** [comment]
Update to 1.16 is a good idea and also can close #7849.

**Comment by hacdias** [comment]
This was done in 9210c08fa69c454e14fc183b5d4237ddecbf3550
