### ISSUE TITLE
Gateway.APICommands configuration is ignored

### ISSUE THREAD

**Issue by lidel** [ipfs/kubo#8059]
This one slipped between our fingers: 

## Problem

`Gateway.APICommands`  is ignored, go-ipfs 0.8.0 uses hardcoded list of commands:
([cmd/ipfs/daemon.go#L669](https://github.com/ipfs/go-ipfs/blame/v0.8.0/cmd/ipfs/daemon.go#L669) → [core/commands/root.go#L166-L198](https://github.com/ipfs/go-ipfs/blob/ef866a1400b3b2861e5e8b6cc9edc8633b890a0a/core/commands/root.go#L166-L198)

## Why this matters

This is blocking our users from running their own delegated routing service without additional nginx magic as noted in https://github.com/libp2p/js-libp2p/pull/371:

>  We were trying to use `Gateway.APICommands` in context of https://github.com/ipfs/js-ipfs/issues/2155#issuecomment-505005256 but it did not work, and @mburns  had to redirect to API port at Nginx level. 

## How to fix it?

Unsure, needs more analysis.
I see two ways to resolve this:

### (A) keep implicit safelist, extend it with values added to `APICommands`

A backward-compatible way to fix this is to keep current implicit defaults from [core/commands/root.go#L166-L198](https://github.com/ipfs/go-ipfs/blob/ef866a1400b3b2861e5e8b6cc9edc8633b890a0a/core/commands/root.go#L166-L198) when `Gateway.APICommands` is empty, but  if we do this, how can gateway operator disable `/api/v0` entierely  if they wish to do so?

### (B) no `/api/v0` by  default, only explicit opt-in safelist via `APICommands`

Perhaps we should make a breaking change and disable `/api/v0` by default on  Gateways, unless user explicitly safelisted commands via  `Gateway.APICommands`  ? <del>This feels like a way safer default. </del> We have some features that depend on `/api/v0` and `/ipfs/` endpoint does not provide replacement for them yet, so better to avoid this (eg. we don't want user to safelist `dht/put` but break `refs` as a side effect)

--- 

It always felt to me  like something that should be opt-in, but would appreciate feedback if someone thinks otherwise.

**Comment by aschmahmann** [comment]
We're going to go with option A here.

**Comment by schomatis** [comment]
Yes, assigning.

**Comment by schomatis** [comment]
@lidel Working on this, do we want an extra config for
> how can gateway operator disable /api/v0 entierely if they wish to do so?

?

**Comment by schomatis** [comment]
@lidel Looking at `APICommands`, this option is an array of strings. How should they work? Do we expect the user to provide the name of `ipfs` subcommands (which we would search by reflection I imagine), would they provide more specialized subcommands, like `block.get` or `block.stat`, for example, to only select the read variants of a subcommand?

I'm temporarily blocking this issue on getting some simple and concrete examples since I don't see any documentation around the option that we need to implement.

**Comment by lidel** [comment]
@schomatis   yes, we want to allow safelisting of a specific subcomand  so people don't expose too much.
Cosmetic note: using `/` as a separator may be a better idea, as `cmd/subcmd` maps to `/api/v0/cmd/subcmd` URL paths better than `.`

**Comment by schomatis** [comment]
We're definitely not prepared to select only a subset of subcommands. This will likely require some reworking of the commands library.

**Comment by schomatis** [comment]
The simplest approach seems to add a function to prune the commands root given a list of whitelisted commands. The code would use similar logic to the [subcommand resolution.](https://github.com/ipfs/go-ipfs-cmds/blob/e9b38676e7353f9ffdbc366af4fac3698091fce3/command.go#L192-L211)

We should use a single hardcoded "master" root: 

https://github.com/ipfs/go-ipfs/blob/25cc85fa9359f907f348e0c2139f2b535313c56c/core/commands/root.go#L122-L126

from which all the other subsets like the hardcoded read-only variant

https://github.com/ipfs/go-ipfs/blob/25cc85fa9359f907f348e0c2139f2b535313c56c/core/commands/root.go#L174-L182

would instead be generated on-the-fly through a list of strings (just as the `APICommands` one the user would provide in its config file) using this new logic.

-----------------------------

> re "how can gateway operator disable /api/v0 entierely if they wish to do so?" – what we want is to remove all implicitly exposed /api/v0 endpoints from the gateway port, and expose only things that user explicitly added to the APICommands array.

I still can't detect a clear answer to this. When `APICommands` is empty do we want to use the read-only list (shown above) or nothing (allow no command)?

--------------------------------

@lidel Blocking until getting confirmation on the proposed approach.

**Comment by schomatis** [comment]
Blocked on landing https://github.com/ipfs/go-ipfs-cmds/pull/231.

**Comment by hacdias** [comment]
@lidel considering the current goal of removing `/api/v0` from the gateway port completely, I would suggest just removing the configuration.

**Comment by lidel** [comment]
@hacdias yep, it is not even documented at `docs/config.md`, let's remove it.

**Comment by hacdias** [comment]
@lidel there you have it #10309
