### ISSUE TITLE
Deploy latest go-ipfs binaries to gateway staging nodes automatically

### ISSUE THREAD

**Issue by BigLep** [ipfs/kubo#8251]
**Done criteria:** 

- [x] New code deployed daily to gateways
    - [x] Merge https://github.com/ipfs/go-ipfs/pull/8142
    - [ ] Wait on https://github.com/protocol/bifrost-infra/issues/1222

**Why important:** 
Performing this whenever a binary is created (or on a ~daily cadence) catches issues with our code before we are in the middle of a full release.  Identifying/addressing issues in advance increases that our release will happen according to schedule.

**Customer:** 
go-ipfs core developers

**Notes:** 
1. go-ipfs binaries are going to be built automatically as part of #8250.  Even before this though, we can be deploying the latest go-ipfs release.
2. This work is dependent on #8119 completing.
3. The specific PL infra that should be running the latest binaries is TBD.  Plans need to be made here with PL infrastructure teams.

**Comment by guseggert** [comment]
See https://github.com/protocol/bifrost-infra/issues/1222

**Comment by BigLep** [comment]
Goal is to get rid of the "Infrastructure Testing" steps in https://github.com/ipfs/go-ipfs/blob/ef866a1400b3b2861e5e8b6cc9edc8633b890a0a/docs/RELEASE_ISSUE_TEMPLATE.md

 Deploy new version to a subset of Bootstrappers
 Deploy new version to a subset of Gateways
 Deploy new version to a subset of Preload nodes
 Collect metrics every day. Work with the Infrastructure team to learn of any hiccup

@guseggert : lets update the issue text on the done criteria, how shadow fleets fit in, link to any infra issues, etc.

**Comment by BigLep** [comment]
@guseggert : what are the next steps here?

**Comment by guseggert** [comment]
I've scoped this down to focus on just gateway nodes, and split off the following issues for bootstrap & preload nodes:

* https://github.com/ipfs/go-ipfs/issues/8328
* https://github.com/ipfs/go-ipfs/issues/8329

**Comment by BigLep** [comment]
We're going to close this out once https://github.com/protocol/bifrost-infra/issues/1222 is resolved, but we are meeting the goal of deploying nighties to our infrastructure automatically now.

**Comment by BigLep** [comment]
@guseggert : is this just waiting on https://github.com/protocol/bifrost-infra/issues/1222 to be resolved?  Are we still deploying nightlies to staging automatically?

**Comment by BigLep** [comment]
Closing since related items were completed.
