### ISSUE TITLE
`ipfs add` option to sort `Unixfs` entries in a certain order 

### ISSUE THREAD

**Issue by Artoria2e5** [ipfs/kubo#8353]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

The XKCD archive QmdmQXB2mzChmMeKY47C43LxUdg1NDJ5MWcKMKxDu7RgQm is currently quite hard to browse through as the filenames are sorted lexicographically instead of numerically. It might be a good idea to allow user some control over `ipfs add` to prevent this sort of thing from happening, using one of the two options:

* A new `--sort` feature to define a sorting method (lexicographic, numeric, version...). This may... get out of hand (see the bunch of sorting-methods [`sort(1)`](https://www.mankier.com/1/sort) accepts), so as an alternative:
* A way to let `ipfs add` accept piped filenames similar to the Unix [`cpio`](https://www.mankier.com/1/cpio) command and use the stdin-given order. The command-line `<path>...` option may be useful for mockups, but command-line length limit is a very real thing when we are talking about doing `--recursive` on our own to maintain a sorted order.

**Comment by Jorropo** [comment]
It's not possible, the unixfs spec (probably sadly) require lexicographic sorting.

I already broke estuary <-> boost transfers by using (base32) numerical sorting in [Linux2ipfs](https://github.com/Jorropo/linux2ipfs) so this has real impacts.
(see https://github.com/filecoin-project/boost/issues/673 for more details)
