### ISSUE TITLE
Dose the writeable gateway API support authentication system?

### ISSUE THREAD

**Issue by badkk** [ipfs/kubo#8362]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

Like the writeable API `/api/v0/add`, can we easily config the public gateway with customized authentication service like remote pinning service?

**Comment by guseggert** [comment]
No, but you can use a forwarding proxy that adds auth which is a common pattern.
