### ISSUE TITLE
Add more information to gateway error responses

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [ipfs/kubo#8365]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

is it possible to show if the hash does not point to any object like "hash deleted since no pin after 24h"
or something like that? it will improve the user experience thanks

**Comment by guseggert** [comment]
So your example text isn't technically correct, but we would like to improve the error message on 404 to include more information about why the request failed.

**Comment by lidel** [comment]
Some work on making errors more friendly was done in https://github.com/ipfs/boxo/pull/298 
If more needs to be done, feel free to open a new issue with suggested UX.
