### ISSUE TITLE
Create a public 2022 roadmap

### ISSUE THREAD

**Issue by BigLep** [ipfs/kubo#8620]
## Done Criteria
There is a publicly viewable roadmap for the work that PL go-ipfs engineers plan to invest in for 2022.  It is not too brittle that it can be updated on a periodic (quarterly if not sooner) basis as new information as learned.

## Why Important
1. Give community visibility into our plans so they can plan accordingly and have an opportunity to influence.
2. Ensure PL engineering resources are being thoughtfully directed.

## Notes
The location/form is still TBD.

**Comment by BigLep** [comment]
I'm working on getting the recording from the 2021-10-28 meeting.

In terms of next steps, the PL go-ipfs engineers will be working more on 2022 plans in general when we all return from break in January.  Certainly a key thrust will be around the gateway usecases with some of the items that Lidel has already discussed previously around creating specs for gateway behavior and some compliance test suite that anyone could run to ensure their gateway works as expected.  This should enable the creation of gateway-specific software by the community.

The [manifest/redirect work](https://github.com/ipfs/specs/issues/257) and content filtering are also being anticipated as those understandably emerged as top needs in the 2021-10-28 meeting.  Creating a public roadmap for go-ipfs in general is being tracked [here](https://github.com/ipfs/go-ipfs/issues/8620), which should include these items.

**Comment by tinytb** [comment]
See https://github.com/ipfs/roadmap/issues/102
