### ISSUE TITLE
Progress are not supported in api calls

### ISSUE THREAD

**Issue by godcong** [ipfs/kubo#8651]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

api docs: https://docs.ipfs.io/reference/http/api/#api-v0-pin-add
The httpapi in the documentation can use the progress parameter

but https://github.com/ipfs/go-ipfs-http-client/blob/434ac969c653f7c4781144aaa2834b5f8828ce22/pin.go#L43 can only used recursive

I want to add the progress support and change the `Add` api to chan output
But this requires changes to some common interfaces
`github.com/ipfs/interface-go-ipfs-core/options`

Does the ipfs team want a PR for this feature？

**Comment by Jorropo** [comment]
All of the underlying APIs work at the block level, we cannot report smaller than block progress without extremely heavy and breaking refactor which are not intrested in taking part of.

We are not sure to understand what you want, would like pin add to report a single 1 block progress once direct blocks are pinned for consistency or do you want more granular progress ?

**Comment by godcong** [comment]
@Jorropo 
When Pinning a large file, the progress of the block is returned periodically.
Instead of thinking it's stuck? Isn't it?

**Comment by Jorropo** [comment]
@godcong a file is breaken up in ~256KiB blocks, I havn't checked recently but what should happen is that you get progress info after each block.
That already a thing.

AFAIT you want progress in smaller increments than block, which we don't want to do because this would break too much stuff in the code.

**Comment by godcong** [comment]
@Jorropo 
The command supports `progress`, but the api does not.
So api and command are not separated?
