### ISSUE TITLE
Add Plugin's Config default configuration interface

### ISSUE THREAD

**Issue by godcong** [ipfs/kubo#8701]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

Adding the Plugin's Config default configuration interface is to write the Plugin's default configuration to the config file at init time.

**Comment by BigLep** [comment]
PR for this issue: https://github.com/ipfs/go-ipfs/pull/8702
