### ISSUE TITLE
Move off CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by BigLep** [ipfs/kubo#8804]
## Done Criteria
Integration tests run from GitHub actions rather than GitHub Actions

## Why Important
1. CircleCI becomes one more piece of infrastructure we need to manage and be aware of
2. Most everything else has moved to GitHub actions.  Relates to the above.  Narrow the toolchain and have consistency.
3. Makes it easier for forks to run tests

## User/Customer
Contributors and maintainers

## Notes

**Comment by BigLep** [comment]
Another added benefit is we should get better test output for debugging test failures.  Copied in discussion about CircleCI from [Discord](https://discord.com/channels/806902334369824788/954520767125684316).

From @lidel about what we have to do in CircleCI:

```
you can get the name of sharness test file from sharnessLinux.t0043-add-w  → then you run that specific test locally, in debug mode  ./t0043-add-w.sh -v 

if the output does not tell you much, add && cat actual && cat expected &&   in the middle  scripts to print  compared values.

Not sure if there is a better way, but thats what I've been doing.
```

**Comment by guseggert** [comment]
We'd need to setup self-hosted runners for this, as we use the 2xlarge CircleCI resource class which is 16 vCPUs and 32 GB RAM, whereas GH Actions hosted runners only provide 2 vCPUs and 7 GB RAM, which would slow down the build time by an unacceptable amount.

**Comment by galargh** [comment]
Current status: I managed to successfully run all the workflows from CircleCI in GitHub Actions. Tracked in https://github.com/galargh/go-ipfs/tree/github-actions

Next steps: set up self-hosted runners to boost performance. 30m+ builds are not acceptable.

**Comment by BigLep** [comment]
@galargh : I see circle ci mentioned in https://github.com/ipfs/kubo/blob/master/docs/RELEASE_ISSUE_TEMPLATE.md .  Is that getting removed in a PR somewhere?

**Comment by galargh** [comment]
@BigLep not as part of this issue as it's only mentioned in the context of CI setups in ipfs-distributions and ipfs-docs. It should be easier to migrate these two to GHA though. We could look into it after IPFS Thing.

**Comment by BigLep** [comment]
Ack - make sense - thanks!
