### ISSUE TITLE
Propogating intermittant failures for Datastores

### ISSUE THREAD

**Issue by Ericson2314** [ipfs/kubo#8906]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

It is possible for an intermittent error to occur during a datastore operation. With "Get", for example, it would nice to distinguish "we don't have this yet" from "intermittent failure trying to get". This potentially allows caching failures with less risk of cache poisoning.

This came up while working on the Software Heritage IPFS bridge in https://sympa.inria.fr/sympa/arc/swh-devel/2022-04/msg00032.html (see the part about "5xx errors"). In this case, rate limiting is quite important: we *don't* want IPFS to overwhelm the archive, which is supposed to be storage of last resort, and instead want the network to act as a CDN preferring other nodes that have e.g. popular items as much as possible.

To that end, propagating especially rate limit failures failures from our datastore plugin to the IPFS node seems like a necessary (if not sufficient) step for all sorts of "back pressure" strategies.

Perhaps this case is especially important for bridges, but even local disk IO could be overwhelmed so seems at least somewhat relevant for all datastore plugins alike.

**Comment by guseggert** [comment]
What specific behavioral changes do you want for Kubo? It sounds like you could achieve this by implementing your backpressure strategies in the custom datastore?

**Comment by Ericson2314** [comment]
A data store cannot implement back preassure by itself; this is a question of interfaces not implementations. It depends on how IPFS handles errors and delay from the datastore layer.

**Comment by Ericson2314** [comment]
Perhaps this also would be better tackled at the blockstore level.

**Comment by Jorropo** [comment]
> A data store cannot implement back preassure by itself; this is a question of interfaces not implementations. It depends on how IPFS handles errors and delay from the datastore layer.

What do you mean ? You can use a simple token channel for example.
This should be trivial concurrency.

**Comment by Ericson2314** [comment]
What is on the other end of this token channel?

**Comment by Jorropo** [comment]
> What is on the other end of this token channel?

Your own code, example:
```go
type throtledDatastore struct{
  tokens chan struct{}
  wrapped datastore.Datastore
}

func New(wrapped datastore.Datastore, concurrentLimit int) datastore.Datastore {
  return &throtledDatastore{make(chan struct, concurrentLimit), wrapped}
}

func (d *throtledDatastore) Get(...) ... {
  d.tokens <- struct{}{} // take token
  defer func(){
    <-d.tokens // return token
  }()
  return d.wrapped.Get(...)
}

// ... do other methods the same way
```

**Comment by Ericson2314** [comment]
That can make calls block longer, but it doesn't give Kubo any information beyond that. For example in the original post with the 5xx errors one could just retry and keep Kubo waiting, but one cannot return the error for Kubo to use for additional decision making.

I am fine sitting on this until we have a more concrete performance issue to solve, but I doubt mere blocking will be very satisfactory.

**Comment by Jorropo** [comment]
First it's gonna make consumers code more complex.

But more importantly I don't know what extra decision would be done. The best I can think is just a for loop and retry until it succeed which you could do in the datastore like you pointed.

Do you have some ideas about how Kubo would handle transient errors better ?
