### ISSUE TITLE
Investigate why /ipfs/{invalid cid} returns different Status Code now

### ISSUE THREAD

**Issue by lidel** [ipfs/kubo#8924]
`curl -v http://127.0.0.1:8080/ipfs/2329.png` returned:
-  returned `400 Bad Request` in 0.12.2
- now returns  `404 Not Found` (master @ 25cc85fa9359f907f348e0c2139f2b535313c56c)

IIUC this a low impact change, and we should be ok with 404 (comment below if you think otherwise), but would be useful to understand how it happened.

Potential causes:
-  ErrNotFound changes from https://github.com/ipfs/go-ipfs/pull/8838
- refactors like https://github.com/ipfs/go-ipfs/pull/8855
- ?

**Comment by aschmahmann** [comment]
It was https://github.com/ipfs/go-ipfs/pull/8885. In particular we don't check validity of the /ipfs namespace anymore and instead end up relying on the path resolution to fail https://github.com/ipfs/go-ipfs/commit/e07baf5835f646352df14fa21ed641053cd0f81b#diff-427f4a268b11d614e7c3b3fdf35040496dd19492e325e3b1bd4bdaa4f8bf8e66R950. Previously we checked validity earlier https://github.com/ipfs/go-ipfs/commit/e07baf5835f646352df14fa21ed641053cd0f81b#diff-427f4a268b11d614e7c3b3fdf35040496dd19492e325e3b1bd4bdaa4f8bf8e66L381.

Not sure if there are other ramifications of the refactor there.

**Comment by lidel** [comment]
Indeed.

This is a low priority and low impact bug, but we should restore old behavior – missing content root identifier is a Bad Request.
