### ISSUE TITLE
Offer a gemini gateway in addition to http

### ISSUE THREAD

**Issue by kallisti5** [ipfs/kubo#8926]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

ipfs offers a HTTP gateway over 8080.     In addition to this, it would be nice (tm) if ipfs offered a optional [gemini](https://en.wikipedia.org/wiki/Gemini_(protocol)) gateway as well.

Gemini is a low-bandwidth web protocol (positioned somewhere between gopher and http).  It serves gemdoc's which are static markdown-style documents in a standardized way.

The specification is published here:
https://gemini.circumlunar.space/docs/specification.gmi

There's a wide selection of browsers and servers available.   Gemini gateway support would be a good fit as publishing gemini sites fits well over the ipfs model.

More technical information including software:
https://gemini.circumlunar.space

Here's a few example sites and some resources...

![lofi](https://user-images.githubusercontent.com/100110/166249899-fb8cea50-5cb9-4cef-82c9-8efaa5c318f8.png)
![windle](https://user-images.githubusercontent.com/100110/166250431-8658e59f-3011-43d4-9c46-08cff735f41c.png)
![sourcehut](https://user-images.githubusercontent.com/100110/166250439-96a9adac-392e-4bfc-8fdb-08557f578b8d.png)

**Comment by guseggert** [comment]
This sounds like a good candidate for a plugin. We can't take on the burden of maintaining this. Feel free to reach out if you have any questions about how to integrate this as a plugin or some external module. If this gets built, please create a discussion post at https://discuss.ipfs.tech and we can find ways to promote it.
