### ISSUE TITLE
AcceleratedDHTClient needs more resources than the ResourceManager has by default

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/kubo#8945]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.io

### Version

```Text
go-ipfs version: 0.13.0-rc1
Repo version: 12
System version: amd64/windows
Golang version: go1.18.1
```

### Config

```json
Abridged:
{
  "Experimental": {
    "AcceleratedDHTClient": true,
  },
  "Internal": {
    "Bitswap": {
      "EngineBlockstoreWorkerCount": null,
      "EngineTaskWorkerCount": null,
      "MaxOutstandingBytesPerPeer": null,
      "TaskWorkerCount": null
    }
  },
  "Routing": {
    "Type": "dhtclient"
  },
  "Swarm": {
    "AddrFilters": null,
    "ConnMgr": {
      "GracePeriod": "20s",
      "HighWater": 100,
      "LowWater": 50,
      "Type": "basic"
    },
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "RelayClient": {},
    "RelayService": {},
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  }
}
```

### Description

Running with the AcceleratedDHTClient enabled results in bursty connections (e.g. on startup) that result in the routing table being very small (compared to running without the resource manager enabled) and as a result not particularly functional.

Enabling debug logging on the resource manager shows that we're out of available outbound connections.

Some analysis here is still need, however AFAICT the reasons for this are:
- We now have enforceable connection limits
- The accelerated DHT client makes lots of connections in a short period of time. While it doesn't need to keep them open for very long it can't really close the connections in case they're in use (e.g. for Bitswap requests) and so it has to rely on the garbage collection on the host which also means waiting for the grace period.

Some options here include:
1. Increase the resource limits, particularly for outbound connections and some overall limits like connections and file descriptors. Given that outbound connections are largely controlled by user behavior (e.g. turning on the AcceleratedDHTClient, making lots of API or gateway requests, etc.) this might not be so bad
2. Make the AcceleratedDHTClient consume fewer resources - some examples include
    - Reduce (the default) amount of concurrent work the AcceleratedDHTClient does when doing routing table initialization or maintenance
    - More aggressively return resources to the system. Could be having the AcceleratedDHTClient call `Trim()` or manually calling close on unprotected connections it recently used.
    - Have go-libp2p give the application layer more control over how dialing is done (e.g. for expensive but not latency-critical operations have the client only dial WAN peers and try different transports serially rather than in parallel)
3. Emitting louder errors to users of the AcceleratedDHTClient when insufficient resources are available to maintain the routing tables. At the extremes we could have hard coded errors in go-ipfs telling users to bump their limits or errors emitted from the AcceleratedDHTClient based on checking the error types received

Looking for feedback here on other ideas or preferences for how to handle this. My initial reaction is to go with increasing limits and have the AcceleratedDHTClient log errors when its routing table won't update properly due to resource starvation. Without the logs getting people to report issues properly will likely be difficult, and increasing the limits vs reducing the resource consumption is something we can then more easily tune over time (i.e. lower the limits as we reduce resource consumption)

**Comment by BigLep** [comment]
2022-05-05 conversation: 
1. We need errors to know when this situation occurs
2. Lets understand how limits were set.  
 - For example, do we need a limit on outbound connections
 - Capture how this was chosen

Current plan:
1. Add errors
2. Raise outbound/global limits

We're not tackling bigger items like:
1. Being able to hand resources back to libp2p
2. Optimizing resource consumption in common code paths

**Comment by BigLep** [comment]
Exit criteria:

``ipfs stats dht | wc -l`` 

Should be ~equal with and or without resource manager enabled.

**Comment by Nate158digimon** [comment]
`nate` [https://discuss.ipfs.io/t/greetings/14328?u=nate158digimon](url)

**Comment by ThomasFreedman** [comment]
I just upgrated a very large repo from v7 to v12 which succeeded according to the info reported. However I see error messages continually occurring like:

```
2022-11-26T10:08:04.655-0600    ERROR   resourcemanager libp2p/rcmgr_logging.go:57      Consider inspecting logs and raising the reso
urce manager limits. Documentation: https://github.com/ipfs/kubo/blob/master/docs/config.md#swarmresourcemgr
2022-11-26T10:08:14.656-0600    ERROR   resourcemanager libp2p/rcmgr_logging.go:53      Resource limits were exceeded 332 times with
error "system: cannot reserve inbound connection: resource limit exceeded".

```

I can find no information on the process by which the logs are analyzed and changes are made to the config file to remove these repetitive error messages. The link provided in the error message is of little help in how to resolve the errors.

**Comment by BigLep** [comment]
@ThomasFreedman : you mentioned v12.  Did you mean v0.17 (latest Kubo release)?

**Comment by ThomasFreedman** [comment]
Yes, that probably correct since I was upgrading to that. I just copied what was printed in the output.
My apologies if I hijacked this topic. My issue is directly related.

I'm still without a clue how to resolve the problem and stop the log from filling up due to these messages.

Should I file a separate bug report?
