### ISSUE TITLE
Public gateway performance

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/kubo#8998]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.io

### Version

```Text
unknown
```

### Config

```json
unknown
```

### Description

I noticed the last day (at least) very poor gateway performance. This is true for pinata, Cloudflare and ipfs.io.

I tried two internet providers in two different cities in Germany and mostly got `504 Gateway Time-out` from ipfs.io for content readily available on multiple nodes PLUS pinned for a day on pinata.

A locally running node on the other hand had no issues locating the content within 1-2 seconds via `ipfs dht findprovs`.

If ipfs.io respond I get an `curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)` while downloading a files with less than 20 MByte very regularily.

Pinata's public gateway just closes the TCP connection. I've asked about this in the Matrix chat like 12h ago.

Not sure if that's related to a specific change in go-ipfs, but I'm pretty sure the gateways all use go-ipfs and I suspect for example the new accelerated DHT to have some issues (if in use).

Could please someone from the infrastructure team have a look at this?

**EDIT**

I tried starting my server with accelerated-dht activated and (after waiting 15 minutes) I retried finding the content. It worked perfectly.

So I guess there's an issue with the compatibility of "regular" dht-servers and accelerated-dht-servers?

**Comment by BigLep** [comment]
@RubenKelevra : is this still an issue?  If so, please open the issue at https://github.com/protocol/netops/issues/new/choose.  That will get you in contact with the owners of the ipfs.io gateway.

I unfortunately can't transfer the issue because it's a different github organization.
