### ISSUE TITLE
RelayClient takes a while to retrieve public multiaddress

### ISSUE THREAD

**Issue by Winterhuman** [ipfs/kubo#9043]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.io

### Version

```Text
go-ipfs version: 0.13.0
Repo version: 12
System version: amd64/linux
Golang version: go1.18.3
```

### Config

```json
{
  "API": {
    "HTTPHeaders": {}
  },
  "Addresses": {
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Announce": [],
    "AppendAnnounce": [],
    "Gateway": "/ip4/127.0.0.1/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic",
      "/ip6/::/udp/4001/quic"
    ]
  },
  "AutoNAT": {},
  "Bootstrap": [
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
    "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.131.131.82/udp/4001/quic/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
  ],
  "DNS": {
    "Resolvers": {}
  },
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "10GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 10
    }
  },
  "Experimental": {
    "AcceleratedDHTClient": false,
    "FilestoreEnabled": false,
    "GraphsyncEnabled": false,
    "Libp2pStreamMounting": false,
    "P2pHttpProxy": false,
    "StrategicProviding": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": false,
    "PathPrefixes": [],
    "PublicGateways": null,
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "12D3KooWQBnnUZKS3PjuTLPyhDdxQtfwmPnuSkuZuAZCmFunbqxa"
  },
  "Internal": {},
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Migration": {
    "DownloadSources": [],
    "Keep": ""
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Peering": {
    "Peers": null
  },
  "Pinning": {
    "RemoteServices": {}
  },
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {
    "Interval": "12h",
    "Strategy": "all"
  },
  "Routing": {
    "Type": "dht"
  },
  "Swarm": {
    "AddrFilters": null,
    "ConnMgr": {
      "GracePeriod": "20s",
      "HighWater": 900,
      "LowWater": 600,
      "Type": "basic"
    },
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "RelayClient": {},
    "RelayService": {},
    "ResourceMgr": {},
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  }
}
```

### Description

When `RelayClient.Enabled` is true (the new default), `ipfs id` and the WebUI don't present public multiaddresses for a long while (I originally thought it never resolves and had to change the issue), this might give users the false impression that `RelayClient` isn't working when it's actually just loading.

Perhaps the WebUI or daemon output should mention that it can take a while to retrieve a public multiaddress when `RelayClient` is enabled?

**Comment by BigLep** [comment]
2022-07-01 triage conversation: like with UPnP, we agree that we should give signal that this can takes seconds/minutes and that it would be ideal to have it in the documentation.  

@Winterhuman do you want to:
1. Add documentation note about this (i.e., "If you enable RelayClient is may take seconds...")
2. Expose the current state from a command like ``ipfs diag network``.   @aschmahmann will find the existing PR or issue.

**Comment by aschmahmann** [comment]
PR that started on a network diagnostics command https://github.com/ipfs/go-ipfs/pull/7068

**Comment by Winterhuman** [comment]
@BigLep Adding a mention in the docs, as well as a `ipfs diag network` command, would be helpful, however, I don't think that would solve the issue fully. The user expectation is that if `ipfs daemon` is successful, and you can access the WebUI with no indication of any problems, you should be publicly accessible; a new user won't know that you need to wait a few minutes if nothing tells the user as such.

Ideally, the `ipfs daemon` output (which https://github.com/ipfs/go-ipfs/issues/8485#issuecomment-934048430 covers) and the WebUI should state that public multiaddresses aren't immediately available because RelayClient is still working on it, then once public multiaddresses are found the indication disappears or is corrected by a later output.

**Comment by aschmahmann** [comment]
> a new user won't know that you need to wait a few minutes if nothing tells the user as such.

This is more than just addresses. Generally speaking the reason people want to be reachable is because they're trying to serve data, but as mentioned in the #8485 you may care about advertising as well.

Note: these sorts of things aren't just on startup, depending on your machine and network setup its possible your reachability status could change over time. In particularly bad cases (e.g. your internet is out for a day) even your content advertising could go from "everything is advertised" to "not everything is advertised", and of course if you run some command that gets data into the node (e.g. `ipfs add` or `ipfs pin`) it could take some time between when all your data is downloaded and when it's advertised. All this is to say that having a pollable endpoint seems pretty sensible here (and sure WebUI can poll the endpoint for updates periodically and update some icon), and that there's more things that effect a user than just if they are behind a NAT but have a relay to make them reachable.

**Comment by Winterhuman** [comment]
Agreed, feedback on connectivity and DHT status would be very useful. Should I close this issue as a duplicate since https://github.com/ipfs/go-ipfs/issues/8485 is technically the same and would close this issue if completed?

**Comment by aschmahmann** [comment]
I'm fine repurposing this to just handle the connectivity via something like `ipfs diag network`. Dealing with advertisements is going to be a whole other mess, `ipfs diag network` shouldn't be too bad though.

**Comment by Winterhuman** [comment]
@aschmahmann Hold on, I've just realised something. It isn't that getting the public multiaddresses is taking a while, it's probably because the **Status** page of the WebUI doesn't refresh the multiaddresses until you refresh the page. I'll open an issue in the `ipfs-webui` repo; the original reason for this issue might not be true

**Comment by Winterhuman** [comment]
Oh, what input's needed?

**Comment by BigLep** [comment]
2022-07-22: closing this since https://github.com/ipfs/kubo/pull/7068 captures what we want here: a command to get the current network diagnostics for determining status of various services.  This allows things like webui to display different visual indications based on low-level states.
