### ISSUE TITLE
Improve Garbage Collector Algorithm

### ISSUE THREAD

**Issue by luanet** [ipfs/kubo#9078]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

GC is not working well for large number of cids, because of the algorithm is not designed well: It load all pinned cids to memory and run a loop over all cids in `blocks` to figure out which cid is not pinned and then remove.

I suggest another algorithm for GC:
1. Implement another `dsindex.Indexer` to save the cached or unpinned cids, key is CID and value is timestamp indicate how long this key is expired and will be removed from `blocks`.
2. All CIDs added by `cat` or `get` command will be added to this indexer automatically, expired time is configurable.
3. All CIDs unpinned will be added to this indexer with the expired time is zero, mean that it will be removed immediately when GC run.
4. GC start and get all (or a fixed number of expired cids) expired cids in this indexer and then check to see if this CID is still pinning or not for that last time by calling `IsPinned` function, then remove.

By this algorithm, we will reduce memory usage and time to block the datastore of GC. Very good for other datastore like `go-ds-s3`, `go-ds-gcs`, `go-ds-b2`.....

**Comment by BigLep** [comment]
@luanet : are you sure this isn't covered in other issues listed here:
https://github.com/ipfs/kubo/issues?q=is%3Aissue+gc
https://github.com/ipfs/kubo/issues?q=is%3Aissue+garbage+collection

Maintainers agree that GC should be improved and that it would be good to consolidate more of the issues.  It would help though not to create more here.
