### ISSUE TITLE
Docker: can't start with badgerds

### ISSUE THREAD

**Issue by johnrichardrinehart** [ipfs/kubo#9104]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.io/#kubo) or have an issue updating.

### Installation method

built from source

### Version

```Text
/ # ipfs version --all
go-ipfs version: 0.13.1-8ffc7a8
Repo version: 12
System version: amd64/linux
Golang version: go1.18.3
```

### Config
```json
/ # ipfs config show
{
  "API": {
    "HTTPHeaders": {}
  },
  "Addresses": {
    "API": "/ip4/0.0.0.0/tcp/5001",
    "Announce": [],
    "AppendAnnounce": [],
    "Gateway": "/ip4/0.0.0.0/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic",
      "/ip6/::/udp/4001/quic"
    ]
  },
  "AutoNAT": {},
  "Bootstrap": [
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
    "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.131.131.82/udp/4001/quic/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ"
  ],
  "DNS": {
    "Resolvers": {}
  },
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "24h",
    "HashOnRead": false,
    "Spec": {
      "child": {
        "path": "badgerds",
        "syncWrites": false,
        "truncate": true,
        "type": "badgerds"
      },
      "prefix": "badger.datastore",
      "type": "measure"
    },
    "StorageGCWatermark": 80,
    "StorageMax": "6TB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 10
    }
  },
  "Experimental": {
    "AcceleratedDHTClient": false,
    "FilestoreEnabled": false,
    "GraphsyncEnabled": false,
    "Libp2pStreamMounting": false,
    "P2pHttpProxy": false,
    "StrategicProviding": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": false,
    "PathPrefixes": [],
    "PublicGateways": null,
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "12D3KooWJK4otiieLKw3ikmnbjbs2n3GgxzxbhZ6FwkngnhD7YrM"
  },
  "Internal": {},
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Migration": {
    "DownloadSources": [],
    "Keep": ""
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Peering": {
    "Peers": null
  },
  "Pinning": {
    "RemoteServices": {}
  },
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {
    "Interval": "12h",
    "Strategy": "all"
  },
  "Routing": {
    "Type": "dht"
  },
  "Swarm": {
    "AddrFilters": null,
    "ConnMgr": {
      "GracePeriod": "20s",
      "HighWater": 900,
      "LowWater": 600,
      "Type": "basic"
    },
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "RelayClient": {},
    "RelayService": {},
    "ResourceMgr": {},
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  }
}
```

### Description
The `docker` build/run context is provided below as well as some of the different configurations that were tried and the results.

# `Dockerfile`
```Dockerfile
FROM ipfs/go-ipfs:v0.13.1

COPY ./Datastore.Spec.json /container-init.d/Datastore.Spec.json
COPY ./config.sh /container-init.d/config.sh
```

# `config.sh`
```shell
#!/bin/sh

ipfs config --json Datastore.StorageMax '"6TB"'
ipfs config --json Datastore.GCPeriod '"24h"'
ipfs config --json Datastore.StorageGCWatermark 80

ipfs config --json Datastore.Spec "$(cat /container-init.d/Datastore.Spec.json)"
```

# `Datastore.Spec.json`
```json
{
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "type": "badgerds",
            "path": "datastore",
	    "syncWrites": false,
	    "truncate": true
          },
          "mountpoint": "/",
          "prefix": "badgerds.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
}
```

```bash
$ docker run --rm --name ipfs_host -v /tmp/ipfs:/data/ipfs -p 4001:4001 -p 127.0.0.1:8080:8080 -p 127.0.0.1:5001:5001 jpg-ipfs:latest
Changing user to ipfs
ipfs version 0.13.1
generating ED25519 keypair...done
peer identity: 12D3KooWNQTDhkDtetGcQZXsuZ4xoChdvFpH2nHzwbQeM3REMQ8T
initializing IPFS node at /data/ipfs
to get started, enter:

	ipfs cat /ipfs/QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc/readme

Executing '/container-init.d/config.sh'...
Initializing daemon...
go-ipfs version: 0.13.1-8ffc7a8
Repo version: 12
System version: amd64/linux
Golang version: go1.18.3

Error: datastore configuration of '{"mounts":[{"mountpoint":"/blocks","path":"blocks","shardFunc":"/repo/flatfs/shard/v1/next-to-last/2","type":"flatfs"},{"mountpoint":"/","path":"datastore","type":"levelds"}],"type":"mount"}' does not match what is on disk '{"mounts":[{"mountpoint":"/blocks","path":"blocks","shardFunc":"/repo/flatfs/shard/v1/next-to-last/2","type":"flatfs"},{"mountpoint":"/","path":"datastore","type":"badgerds"}],"type":"mount"}'
```

`/tmp/ipfs` is initially non-existent, so `docker`/`kubo` is provisioning it. I would expect since that I could configure the `Datastore.Spec` from a fresh install without having the configuration fail to match what's on disk. The error message seems to imply that the disk format is what I had wanted.

I tried setting `IPFS_PROFILE` to `badger` both with and without using my `Datastore.Spec.json`. So, I was running
```bash
$ docker run --rm --name ipfs_host -v /tmp/ipfs:/data/ipfs -p 4001:4001 -p 127.0.0.1:8080:8080 -p 127.0.0.1:5001:5001 --env IPFS_PROFILE=badgerds jpg-ipfs:latest
```
But, the results were similarly bad. I've seen in the documentation that https://github.com/ipfs/ipfs-ds-convert exists, but I don't think it should be necessary to convert if this is a fresh install.

I'm also not clear on the need for the `blocks` mount which comes by default using `docker`. `IPFS_PROFILE=badgerds` simplifies the `Datastore.Spec` configuration significantly from the default of
```json
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
   ```
to 
```json
    "Spec": {
      "child": {
        "path": "badgerds",
        "syncWrites": false,
        "truncate": true,
        "type": "badgerds"
      },
      "prefix": "badger.datastore",
      "type": "measure"
    },
 ```
And, it's not clear to me if I need the two children mounts as comes by default and/or if the latter `Datastore.Spec` will give me what I want (an instance of IPFS using the `badgerds` filesystem driver), since there is no `blocks` mount.

**Comment by Jorropo** [comment]
@johnrichardrinehart

I belive the issue is not the with config.
The issue is that after the config you need to convert the datastore on your disk.

To do that you can run this tool that convert the underlying files on disk to badger.
https://dist.ipfs.io/#fs-repo-migrations (which we havn't updated for Kubo 0.12 yet afaik)

But have you tried `ipfs init --profile badgerds` instead of manually configuring it ? (that will initialize with badger to start with)

**Comment by johnrichardrinehart** [comment]
> @johnrichardrinehart
> 
> I belive the issue is not the with config.
> The issue is that after the config you need to convert the datastore on your disk.

But, isn't the config used to establish the initial datastore?

> To do that you can run this tool that convert the underlying files on disk to badger.
> https://dist.ipfs.io/#fs-repo-migrations (which we havn't updated for Kubo 0.12 yet afaik)

In my above I mentioned that

> I've seen in the documentation that https://github.com/ipfs/ipfs-ds-convert exists, but I don't think it should be necessary to convert if this is a fresh install.

Is `fs-repo-migrations` different than `ipfs-ds-convert`? If so, how?

Also, I am running `kubo` Docker image tagged as v0.13.1. Did you mean `0.12` because that version introduced breaking changes in the storage/disk formats or did you mean `0.13`?

> But have you tried `ipfs init --profile badgerds` instead of manually configuring it ? (that will initialize with badger to start with)

I tried providing `IPFS_PROFILE=badgerds` to the container but I didn't try that `init` in my `config.sh`. Are those two approaches different? The environment variable wiped out the `mount` type and the children mounts that come by default if the profile isn't changed. And, I'm worried to lose the other child mount.

Also, I'm pretty sure `ipfs init` runs in the `kubo` image already, before I can call it. My `config.sh` is changing particular values after the first `ipfs init` is ran, already, in the parent image. Is it safe/fine to run it more than once?

**Comment by Jorropo** [comment]
> But, isn't the config used to establish the initial datastore?

Yes, but the initial data is created when `ipfs init` runs not the first time you do `ipfs daemon`.

> Is `fs-repo-migrations` different than `ipfs-ds-convert`? If so, how?

Yes pls ignore my comment, I meant `ipfs-ds-convert`. (repo migration runs version migrations, for this is what you run when you want to update your datastore to a new layout)

> I've seen in the documentation that https://github.com/ipfs/ipfs-ds-convert exists, but I don't think it should be necessary to convert if this is a fresh install.

(sorry didn't saw that comment first)

That true but the install is created when you do `ipfs init` not `ipfs daemon`, so in your case it's not a fresh install, since something else inited already.

> Did you mean `0.12` because that version introduced breaking changes in the storage/disk formats or did you mean `0.13` ?

In `0.12` we introduced a new more efficient datastore layout (multihash keying instead of CID keying) which allows for better things to happen.

And AFAIK no one got arround to fixing `ipfs-ds-convert` to support the "new" `0.12` format (which `0.13` uses, we didn't changed the datastore format in between).

> I tried providing IPFS_PROFILE=badgerds to the container but I didn't try that init in my config.sh. Are those two approaches different?

In theory no (since it's just forwarding to the creation script):
```
bin/container_daemon:  ipfs init ${IPFS_PROFILE:+"--profile=$IPFS_PROFILE"}
```

> Also, I'm pretty sure ipfs init runs in the kubo image already, before I can call it. My config.sh is changing particular values after the first ipfs init is ran, already, in the parent image. Is it safe/fine to run it more than once?

I have no idea, I'm not very well familiar with docker and our dockerfiles. I know that in the past we used to have issues where the docker image was configure to reset itself everytime you started it or something like that.

**Comment by johnrichardrinehart** [comment]
> > But, isn't the config used to establish the initial datastore?
> 
> Yes, but the initial data is created when `ipfs init` runs not the first time you do `ipfs daemon`.

I see. And this is already set to run before `/container-init.d/*.sh` runs. So, that's the source of the problem.
 
> > Is `fs-repo-migrations` different than `ipfs-ds-convert`? If so, how?
> 
> Yes pls ignore my comment, I meant `ipfs-ds-convert`. (repo migration runs version migrations, for this is what you run when you want to update your datastore to a new layout)

Ah, no problem. Thanks.

> > I've seen in the documentation that https://github.com/ipfs/ipfs-ds-convert exists, but I don't think it should be necessary to convert if this is a fresh install.
> 
> (sorry didn't saw that comment first)
> 
> That true but the install is created when you do `ipfs init` not `ipfs daemon`, so in your case it's not a fresh install, since something else inited already.

I feel like the `docker` flow is strange. From my perspective, `/container-init.d/` seems like it should affect the `ipfs init` command before it's ever run (from fresh).

> > Did you mean `0.12` because that version introduced breaking changes in the storage/disk formats or did you mean `0.13` ?
> 
> In `0.12` we introduced a new more efficient datastore layout (multihash keying instead of CID keying) which allows for better things to happen.

Ah, okay. Thanks!

> And AFAIK no one got arround to fixing `ipfs-ds-convert` to support the "new" `0.12` format (which `0.13` uses, we didn't changed the datastore format in since).

Haha, so if I want to use `badgerfs` in `docker` _and_ keep the `children` mounts then I'm out of luck, it seems, since `--profile=badgerds` wipes out the `blocks` mount.

> > I tried providing IPFS_PROFILE=badgerds to the container but I didn't try that init in my config.sh. Are those two approaches different?
> 
> In theory no (since it's just forwarding to the creation script):
> 
> ```
> bin/container_daemon:  ipfs init ${IPFS_PROFILE:+"--profile=$IPFS_PROFILE"}
> ```

I see. Thanks for pointing me to that.
 
> > Also, I'm pretty sure ipfs init runs in the kubo image already, before I can call it. My config.sh is changing particular values after the first ipfs init is ran, already, in the parent image. Is it safe/fine to run it more than once?
> 
> I have no idea, I'm not very well familiar with docker and our dockerfiles. I know that in the past we used to have issues where the docker image was configure to reset itself everytime you started it or something like that.

It seems like `ipfs init` runs before I have a chance to call it. Okay, I think I'm going to run `ipfs` as a normal process outside of `docker`. The configuration process and the use of plugins with `docker` seems like a massive pain, haha.
