### ISSUE TITLE
Prevent IPFS daemon from scanning rfc1819 addresses

### ISSUE THREAD

**Issue by hampa** [ipfs/kubo#9115]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

I was running IPFS daemon on a dedicated server in a hosting center. Machine got disabled when IPFS daemon was scanning local addresses.
root     ipfs                 2378480  tcp4   xx.xx.xx.xx:4001        192.168.1.17:33397        SYN_SENT
root     ipfs                 2378480  tcp4   xx.xx.xx.xx:4001        192.168.0.11:36981        SYN_SENT

I assume that is not needed, I tried to find a way to disable it.

**Comment by Jorropo** [comment]
@hampa do `ipfs config profile apply server` then restart your node.
