### ISSUE TITLE
send a hint to daemon on getting files

### ISSUE THREAD

**Issue by itsabgr** [ipfs/kubo#9119]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

add a feature to be able to send an optional field named hint on getting files.
that filed contains a multi-addr of node user shares a CID to another user where it can find the content first.

**Comment by Jorropo** [comment]
How is that différent from `ipfs swarm connect` ?

**Comment by itsabgr** [comment]
it is quicker than finding a peer
on the block\get command it tries to ask the file from the peer even before knowing the peer.

**Comment by Jorropo** [comment]
@itsabgr `ipfs swarm connect` connect you directly to the peer without having to find it.

As far I can tell, You want to directly connect to a peer to skip the discovery step, `ipfs swarm connect` do that, i would like to know if you had more in mind.

**Comment by itsabgr** [comment]
with swarm/connect ipfs connects to the peer and in searches as the order of xor and may not ask for the provided peer at first. but when we send a hint daemon can ask the peer before any DHT search.
mean when we send a hint to the daemon tell the daemon to ask for the content from that peer at first.

**Comment by Jorropo** [comment]
> with swarm/connect ipfs connects to the peer and in searches as the order of xor and may not ask for the provided peer at first

Sorry but that just false, bitswap broadcast the wantlist to anyone you connect to.

Xor distance is the DHT.

**Comment by BigLep** [comment]
2022-07-22 maintainer note: given there is ``ipfs swarm connect`` if operating at the CLI level, we're not going to add this extra convenience method to avoid the maintenance burden.
