### ISSUE TITLE
run the daemon without networking

### ISSUE THREAD

**Issue by Jorropo** [ipfs/kubo#9174]
There are many cases where you want to run a no network daemon.
1. exchanging `.car` files Out-Of-Band and then serving them over gateway.
2. running concurrent CLI commands but without sharing files.

This would need a `nonet` (profile too).

**Comment by aschmahmann** [comment]
`ipfs daemon --offline`?

**Comment by Jorropo** [comment]
wait that a thing ?

**Comment by Jorropo** [comment]
It works but is poorly documented.
```
$ ipfs daemon --help | grep offline
```
gives nothing.
