### ISSUE TITLE
IPFS RepoSize grows periodically even though no files are added and pinned

### ISSUE THREAD

**Issue by arganjava** [ipfs/kubo#9183]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.io/#kubo) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.io

### Version

```Text
Kubo version: 0.14.0
Repo version: 12
System version: amd64/linux
Golang version: go1.18.3
```

### Config

```json
{
  "API": {
    "HTTPHeaders": {
      "Access-Control-Allow-Methods": [
        "PUT",
        "GET",
        "POST"
      ],
      "Access-Control-Allow-Origin": [
        "https://example.com
      ]
    }
  },
  "Addresses": {
    "API": "/ip4/{privateIp}/tcp/5001",
    "Announce": [],
    "AppendAnnounce": [],
    "Gateway": "/ip4/{privateIp}/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic",
      "/ip6/::/udp/4001/quic"
    ]
  },
  "AutoNAT": {},
  "Bootstrap": [
    "/ip4/{ip}/tcp/4001/ipfs/{ipfsOtherPeerId}"
  ],
  "DNS": {
    "Resolvers": {}
  },
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "950GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true
    }
  },
  "Experimental": {
    "AcceleratedDHTClient": false,
    "FilestoreEnabled": false,
    "GraphsyncEnabled": false,
    "Libp2pStreamMounting": false,
    "P2pHttpProxy": false,
    "StrategicProviding": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": false,
    "PathPrefixes": [],
    "PublicGateways": null,
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "${peerID}"
  },
  "Internal": {},
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Migration": {
    "DownloadSources": [],
    "Keep": ""
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Peering": {
    "Peers": null
  },
  "Pinning": {
    "RemoteServices": {}
  },
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {
    "Interval": "12h",
    "Strategy": "all"
  },
  "Routing": {
    "Routers": null,
    "Type": "dht"
  },
  "Swarm": {
    "AddrFilters": null,
    "ConnMgr": {
      "GracePeriod": "20s",
      "HighWater": 900,
      "LowWater": 600,
      "Type": "basic"
    },
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "RelayClient": {},
    "RelayService": {},
    "ResourceMgr": {},
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  }
}
```

### Description

RepoSize grows periodically even though no files are added and pinned, if it continues like this the storage will explode, so how to prevent it?

here type to check the ipfs repo stat

**root@myIp:/home/ubuntu# ipfs repo stat**
NumObjects: 556829
RepoSize:   136535039831
StorageMax: 950000000000
RepoPath:   /root/.ipfs
Version:    fs-repo@12
**root@myIp:/home/ubuntu# ipfs repo stat**
NumObjects: 556829
RepoSize:   136535112357
StorageMax: 950000000000
RepoPath:   /root/.ipfs
Version:    fs-repo@12
root@myIp:/home/ubuntu#

**Comment by Jorropo** [comment]
@arganjava are you downloading files using `ipfs get` or the gateway ?

**Comment by aschmahmann** [comment]
`136535112357 - 136535039831 = 72526`, so this is <75 KB of data over an unspecified interval. However, if you're running a DHT server (looks like you are) you'll end up storing some data (IPNS records and provider records) on behalf of the network. Should be fairly small in comparison to any actual data you may be storing though.

Also as @Jorropo mentioned other operations than pinning (and `ipfs add` which implicitly pins) can also result in stored data due to the you asking the node to download the data.

**Comment by arganjava** [comment]
hi @aschmahmann @Jorropo thanks for reply,  the case is I setting up the 3 nodes, the prior files are stored in first node then the second node connected to first then the third node connected to second node via swarm and finally connected it altogether with ipfs cluster, i synced 2 nodes through command `ipfs-cluster-ctl add pin` and also `ipfs repo gc` impact remove unpin cid but RepoSize still growth without `ipfs add` command, is there any solution how to prevent auto growth reposize?

**Comment by arganjava** [comment]
Hi i am monitor for a while look the RepoSize increase and decrease automatically and it looks no problem, thanks

**Comment by Jorropo** [comment]
@arganjava then it's fine closing this issue ?
