### ISSUE TITLE
Indeterminism of CID when using MFS 'files write' RPC

### ISSUE THREAD

**Issue by ywk248248** [ipfs/kubo#9193]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

ipfs-desktop

### Version

```Text
Kubo version: 0.14.0-e0fabd6
Repo version: 12
System version: amd64/linux
Golang version: go1.18.3
```

### Config

```json
{
  "API": {
    "HTTPHeaders": {}
  },
  "Addresses": {
    "API": "/ip4/0.0.0.0/tcp/5001",
    "Announce": [],
    "AppendAnnounce": [],
    "Gateway": "/ip4/0.0.0.0/tcp/8080",
    "NoAnnounce": [
      "/ip4/10.0.0.0/ipcidr/8",
      "/ip4/100.64.0.0/ipcidr/10",
      "/ip4/169.254.0.0/ipcidr/16",
      "/ip4/172.16.0.0/ipcidr/12",
      "/ip4/192.0.0.0/ipcidr/24",
      "/ip4/192.0.2.0/ipcidr/24",
      "/ip4/192.168.0.0/ipcidr/16",
      "/ip4/198.18.0.0/ipcidr/15",
      "/ip4/198.51.100.0/ipcidr/24",
      "/ip4/203.0.113.0/ipcidr/24",
      "/ip4/240.0.0.0/ipcidr/4",
      "/ip6/100::/ipcidr/64",
      "/ip6/2001:2::/ipcidr/48",
      "/ip6/2001:db8::/ipcidr/32",
      "/ip6/fc00::/ipcidr/7",
      "/ip6/fe80::/ipcidr/10"
    ],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic",
      "/ip6/::/udp/4001/quic"
    ]
  },
  "AutoNAT": {},
  "Bootstrap": [
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
    "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.131.131.82/udp/4001/quic/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa"
  ],
  "DNS": {
    "Resolvers": {}
  },
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "10GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": false
    }
  },
  "Experimental": {
    "AcceleratedDHTClient": false,
    "FilestoreEnabled": false,
    "GraphsyncEnabled": false,
    "Libp2pStreamMounting": false,
    "P2pHttpProxy": false,
    "StrategicProviding": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": false,
    "PathPrefixes": [],
    "PublicGateways": null,
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "12D3KooWEg2mAJ7pTGWdYsc9F5a8fBkz11eoskrHCu4xCQAVhJvw"
  },
  "Internal": {},
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Migration": {
    "DownloadSources": [],
    "Keep": ""
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Peering": {
    "Peers": null
  },
  "Pinning": {
    "RemoteServices": {}
  },
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {
    "Interval": "12h",
    "Strategy": "all"
  },
  "Routing": {
    "Routers": null,
    "Type": "dht"
  },
  "Swarm": {
    "AddrFilters": [
      "/ip4/10.0.0.0/ipcidr/8",
      "/ip4/100.64.0.0/ipcidr/10",
      "/ip4/169.254.0.0/ipcidr/16",
      "/ip4/172.16.0.0/ipcidr/12",
      "/ip4/192.0.0.0/ipcidr/24",
      "/ip4/192.0.2.0/ipcidr/24",
      "/ip4/192.168.0.0/ipcidr/16",
      "/ip4/198.18.0.0/ipcidr/15",
      "/ip4/198.51.100.0/ipcidr/24",
      "/ip4/203.0.113.0/ipcidr/24",
      "/ip4/240.0.0.0/ipcidr/4",
      "/ip6/100::/ipcidr/64",
      "/ip6/2001:2::/ipcidr/48",
      "/ip6/2001:db8::/ipcidr/32",
      "/ip6/fc00::/ipcidr/7",
      "/ip6/fe80::/ipcidr/10"
    ],
    "ConnMgr": {
      "GracePeriod": "20s",
      "HighWater": 900,
      "LowWater": 600,
      "Type": "basic"
    },
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": true,
    "RelayClient": {
      "Enabled": true
    },
    "RelayService": {},
    "ResourceMgr": {},
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  }
}
```

### Description

- What you were doing when you experienced the bug.
I'm hosting 2 ipfs nodes and want to "ipfs files write" the same content  on both.(a folder with 6000+ small files with total 600MB in size)

- Any error messages you saw, where you saw them, and what you believe may have caused them (if you have any ideas).
After completing writing both nodes successfully, I use "ipfs files stat" for directory and get different CIDs.
However, when I inspect CIDs, I find CID info are identical despite CID are different....

QmS6KwZHWXkfK573u5Zyno4J7YYn597MsH9nr7yzXPzAdX
base58btc - cidv0 - dag-pb - sha2-256~256~37C3652DEAB168D8007A17D7EC6531D9F801565DFB1C5912AB7C77CE58C79DD2

QmZSoDTktCjtpiJFrXn8H8MmqNeUdi6vH6D1bmwJQgqrzJ
base58btc - cidv0 - dag-pb - sha2-256~256~37C3652DEAB168D8007A17D7EC6531D9F801565DFB1C5912AB7C77CE58C79DD2

I wonder how to generate a deterministic CID....

**Comment by ywk248248** [comment]
By using object diff...I find the leaf causing CID diff on DAG root, but it's still confusing

ipfs ipfs cat QmeXZfgNsJ1ysbAz9GjMedty71HHqJcDSUw2YqhHiXAXGS > log1
ipfs ipfs cat QmZ96Shy1wme95WR6tAmruRfydveNutXobMhrLcNoaxCDR > log2

they are identical!

**Comment by Jorropo** [comment]
@ywk248248 we don't promise any determinism.
and IMO relying on that is using ipfs wrong. (you should exchange IPLD blocks, probably using a car file, `ipfs dag export` & `ipfs dag import` or `ipfs pin add`).

The MFS do incremental updates of the files, it would be uselessly hard to make that deterministic.

> I'm hosting 2 ipfs nodes and want to "ipfs files write" the same content on both.(a folder with 6000+ small files with total 600MB in size)

You should instead `ipfs files write` on one and then `ipfs pin add` & `ipfs files cp /ipfs/CID /path` in the second.
I use https://ipfscluster.io/ which is really good and synchronise pins accross my nodes.

---

I'll leave open for other maintainers to give their opinion but IMO that a WONTFIX.

**Comment by ywk248248** [comment]
Thanks a lot @Jorropo for the kind suggestions.

We evaluated to use IPFS cluster directly but seems it mean to be self-contained and there's no way to use public gateway(ipfs.io) to access CIDs in cluster (is that correct?)

But we would definitely try to use "write + pin" to make it.

**Comment by Jorropo** [comment]
> We evaluated to use IPFS cluster directly but seems it mean to be self-contained and there's no way to use public gateway(ipfs.io) to access CIDs in cluster (is that correct?)

This is incorrect.

IPFS cluster does not run IPFS, IPFS cluster just manage the "pinset", it then do API calls to Kubo nodes which host the data.
IPFS cluster only takes a role of manager (which yes is more or less closed, you can open it read only following the cluster collabs config templates)
And the the data is hosted by Kubo, which can be private **or not**.
For example my cluster is private but my Kubo nodes are public, so only I can add / remove things to the cluster pins, but anyone can download them (including the gateway).

**Comment by ywk248248** [comment]
@Jorropo You just saved me from building the wheels!

Tried IPFS cluster today and it works like magic in our cloud, successfully pinned the 6000+ files total ~1GB directory to 3 IPFS nodes in few minutes!
