### ISSUE TITLE
Table of context links in v0.14.0 release notes do not work

### ISSUE THREAD

**Issue by olizilla** [ipfs/kubo#9196]
### Checklist

- [X] I am reporting a documentation issue in this repo, not https://docs.ipfs.tech.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Location

https://github.com/ipfs/kubo/releases/tag/v0.14.0

### Description

In previous releases it was possible to use the Table of Contents to grab a link for a specific highlight when referring to it from other issues.

In the current release the headers are a different heading level, and the links are not working.

**Comment by Jorropo** [comment]
Fck me why did I added emojies to IPFS ?

**Comment by Jorropo** [comment]
Thx it's now fixed.
