### ISSUE TITLE
Create `ipfs repo ls` alias for `ipfs refs local`

### ISSUE THREAD

**Issue by Winterhuman** [ipfs/kubo#9205]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

Users wanting to list all objects in their repo need to run `ipfs refs local`, however, most users look under `ipfs repo` because of it's name; `ipfs refs` isn't intuitively located. Additionally, `ipfs refs` only has one subcommand which doesn't feel necessary.

So, I've opened this issue to discuss. I propose `ipfs repo refs`, with `ipfs refs local` becoming `ipfs repo refs -l/--local`.

**Comment by Jorropo** [comment]
I am not in favor of moving all of `ipfs refs`, just `ipfs refs local` => `ipfs repo ls`.

**Comment by Winterhuman** [comment]
That could work as well, an alias would be a lot easier than removing `ipfs refs` (and it would be more backwards compatible as well)

**Comment by Winterhuman** [comment]
After looking at `ipfs refs`'s functionality closer, moving the whole thing under `ipfs repo` would make no sense. I think Jorropo's idea is the best moving forward

**Comment by BigLep** [comment]
2022-08-26 triage conversation: add an alias from ``ipfs repo ls`` → ``ipfs refs local``.

**Comment by BigLep** [comment]
@Winterhuman : do you want to take this one?

**Comment by Winterhuman** [comment]
@BigLep I wouldn't have a clue unfortunately

**Comment by Zanda256** [comment]
@BigLep  I'm giving it a try. I'll ping you for review of my pr.

**Comment by susarlanikhilesh** [comment]
@BigLep https://github.com/ipfs/kubo/pull/9320
Do you think this is good enough for the alias? 
Or am I breaking any code rules?

Thank you

**Comment by Winterhuman** [comment]
https://github.com/ipfs/kubo/pull/9320 is now merged, closing issue. Thanks @susarlanikhilesh!
