### ISSUE TITLE
Should not return 416 for empty files when `Range` includes 0 

### ISSUE THREAD

**Issue by thattommyhall** [ipfs/kubo#9238]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.tech

### Version

```Text
Kubo version: 0.15.0
Repo version: 12
System version: amd64/linux
Golang version: go1.18.5
```
```


### Config

```json
default
```

### Description

@aschmahmann reported seeing this on our public gateway

```
curl https://dweb.link/ipfs/bafkqaaa  
invalid range: failed to overlap
``` 

It seems that the error is induced by us having enabled fragment caching and therefore adding a header `"Range: bytes=0-1048575"` to any requests that dont already have them (which is [common practice](https://www.nginx.com/blog/smart-efficient-byte-range-caching-nginx/#cache-slice))

We can induce the behaviour locally with:

```
❯ curl localhost:8080/ipfs/bafkqaaa -H "Range: bytes=0-1048575"
invalid range: failed to overlap

❯ curl -IL localhost:8080/ipfs/bafkqaaa -H "Range: bytes=0-1048575"
HTTP/1.1 416 Requested Range Not Satisfiable
...
```

My reading of [the spec](https://httpwg.org/specs/rfc7233.html#status.416), particularly 

> "For byte ranges, failing to overlap the current extent means that the first-byte-pos of all of the byte-range-spec values were greater than the current length of the selected representation"

(if it means strictly greater than and not greater than or equal) is that was more correct to serve a 203 or maybe 200 there?

**Comment by Jorropo** [comment]
IMO This is an issue with go and null files should just always be 200 (because handling the range is more expensive that just giving me the file): https://github.com/golang/go/issues/54794

I'll implement an override inside kubo while we wait to see how https://github.com/golang/go/issues/54794 develop.
