### ISSUE TITLE
How to add a CID to the 'ipfs bitwap wantlist' list of other nodes

### ISSUE THREAD

**Issue by dengxmenglihua** [ipfs/kubo#9255]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

How to add a CID to the 'ipfs bitwap wantlist' list of other nodes

**Comment by Jorropo** [comment]
@dengxmenglihua for HOW TO questions please use https://discuss.ipfs.io/
