### ISSUE TITLE
v0.15.0 / Bitswap v0.9.0 make it impossible to add Tracer

### ISSUE THREAD

**Issue by mrd0ll4r** [ipfs/kubo#9256]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

built from source

### Version

```Text
git tag v0.15.0
```

### Description

I'm maintaining the [ipfs-metric-exporter](https://github.com/trudi-group/ipfs-metric-exporter) plugin we use to analyze Bitswap traffic in real time.
For that, we implement `PluginDaemonInternal` and used to apply [`bitswap.WithTracer`](https://github.com/ipfs/go-bitswap/blob/v0.7.0/tracer.go#L16) to the Bitswap instance of the running node.

The rework in Bitswap v0.9.0 has encapsulated and unexported the function-type option and made it such that this can now only be supplied to and applied by `bitswap.New`.
Logically, I tried to inject this option using the new `fx` type plugins, but to no avail.

AFAI can see, Bitswap is initialized via [`core.node.OnlineExchange`](https://github.com/ipfs/kubo/blob/v0.15.0/core/node/bitswap.go#L27), which does not allow me to inject any options.

What am I missing here? How can I, as a plugin author, apply the [`WithTracer`](https://github.com/ipfs/go-bitswap/blob/v0.9.0/options.go#L72)  option to the Bitswap implementation of a kubo node?

**Comment by Jorropo** [comment]
@mrd0ll4r I see this indeed is an issue.
I don't want to revert to the old behaviour, it's racy and I don't like it.

But it probably make sense to add more customization inside kubo.
I don't know FX well but my guess is that we could add some optional `bitswap.Option` type to the `OnlineExchange` factory:
https://github.com/ipfs/kubo/blob/3ae52a41e39ec95aacc48d67b2882c9baeabc2ff/core/node/bitswap.go#L28

Then you could just provide thoses bitswap Options. Similar to how we do with libp2p.

As a more adhoc way you could also use the fx plugin to override the exchange factory and just add your options.

**Comment by BigLep** [comment]
@mrd0ll4r : @ajnavarro is going to link to a sample code change you could make here.  After he has done so, can you please make the PR

**Comment by Jorropo** [comment]
@mrd0ll4r I actually messed up the type in go-bitswap.
I sent a pr fix here: https://github.com/ipfs/go-bitswap/pull/583

**Comment by Jorropo** [comment]
I fixed it in go-bitswap `v0.10.1`, this will bumped in https://github.com/ipfs/kubo/pull/9244

**Comment by mrd0ll4r** [comment]
> we can do something similar as we did with routers here https://github.com/ipfs/kubo/blob/master/core/node/libp2p/routing.go#L58 and here https://github.com/ipfs/kubo/blob/master/core/node/libp2p/routing.go#L135 collect all `bitswap.Option` into a list and inject that into `OnlineExange`

Hmm. I've been staring at this for a while, but not too sure how it applies. I don't know fx, or how IPFS is constructed, really... Do you want me to do something like this:

1. `Provide` something via fx that (takes a Config and) produces `[]bitswap.Option`, e.g.
```go
func Foo(cfg *config.Config, provide bool) interface{} {
	return func() []bitswap.Option {
            ...
}}
...
fx.Provide(Foo(cfg,provideFlag))
```
3. `Provide` something via fx like this:
```go
func(mctx helpers.MetricsCtx, lc fx.Lifecycle, host host.Host, rt irouting.TieredRouter, bs blockstore.GCBlockstore, opts ...bitswap.Option) exchange.Interface
```

And then I could `fx.Decorate` (or `fx.Supply`, adding the defaults?) the `bitswap.Option`s with my own, and those would magically end up in the call to construct the `exchange.Interface`?

**Comment by ajnavarro** [comment]
@mrd0ll4r yeah, if we add `opts ...bitswap.Option` param to the Kubo function creating the exchange, then we can inject really easily specific options using the fx plugin depending on the use case.

**Comment by BigLep** [comment]
I remove the stale label since a PR was submitted: https://github.com/ipfs/kubo/pull/9258
