### ISSUE TITLE
feature: initialization to generate Plugin's Config and customize config handling

### ISSUE THREAD

**Issue by godcong** [ipfs/kubo#9259]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

1. I checked the code, Plugin does not use any of its own Config.
2. Plugin does not write the initial configuration to Config during initialization.

I think these 2 pieces can be strengthened.

**Comment by guseggert** [comment]
What's your use case for changing the parsing behavior?

**Comment by godcong** [comment]
@guseggert 
1. I made a plugin with some audio and video hashes and access to their information, which made it necessary to configure some link information and some other personalized configurations at startup.
2. map[strng]any is not easy to read. Every time you need to get a value you need v,ok:=maps and then convert to v.(string) or whatever.
If you skip the parsing of the plugin field at parsing time and only transfer the original string, you can ensure that the plugin can be parsed into its own config. so that each plugin can configure its own behavior without breaking the system's original action.

**Comment by Jorropo** [comment]
AFAIT we forgot to remove the tag

**Comment by godcong** [comment]
Only the Config section needs to be changed to json.RawMessage.
like this:
```
  "Plugins": {
    "Plugins": {
      "some_plugins": {
        "Disabled": false, //no change
        "Config": {//plugin custom config}
     }
```
Because in most cases it is very troublesome to iterate through `map[string]interfaces`.
This way the Plugin can read the Config values directly according to its own definition.

Each Plugin can have different settings.
It can be a map[string]interface or a struct{}

and in this way the settings of the Plugin can be reflected in the Config file instantly.
