### ISSUE TITLE
Update workflow for CodeQL Actions from V1 to V2

### ISSUE THREAD

**Issue by samperfect** [ipfs/kubo#9263]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

Update workflow for CodeQL Actions from V1 to V2. 

According to CodeQL docs

```
All users of GitHub code scanning (which by default uses the CodeQL analysis engine) on GitHub Actions on the following platforms should update their workflow files:
- GitHub.com (including open source repositories, users of GitHub Teams and GitHub Enterprise Cloud)
- GitHub AE
- GitHub Enterprise Server (GHES) 3.5 and later
Users of the above-mentioned platforms should update their CodeQL workflow file(s) to refer to the new v2 version of the CodeQL Action.
```

**Comment by Jorropo** [comment]
> All users of GitHub code scanning (which by default uses the CodeQL analysis engine) on GitHub Actions on the following platforms should update their workflow files:
> - GitHub.com (including open source repositories, users of GitHub Teams and GitHub Enterprise Cloud)
> - GitHub AE
> - GitHub Enterprise Server (GHES) 3.5 and later
> Users of the above-mentioned platforms should update their CodeQL workflow file(s) to refer to the new v2 version of the CodeQL Action.

:thinking: 

@samperfect can you link this documentation please ?

**Comment by samperfect** [comment]
Sure...@Jorropo here's the [link to the changelog](https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/)
