### ISSUE TITLE
Webui not correctly linking to local gateway when running over LAN at .local domain

### ISSUE THREAD

**Issue by chrisguida** [ipfs/kubo#9288]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

built from source

### Version

```Text
# ipfs version --all
Kubo version: 0.15.0
Repo version: 12
System version: arm64/linux
Golang version: go1.18.5
```

### Config
`# ipfs config show`
```json
{
  "API": {
    "HTTPHeaders": {
      "Access-Control-Allow-Methods": [
        "PUT",
        "POST"
      ],
      "Access-Control-Allow-Origin": [
        "https://djnofp2u5mvjsewk7anxsj4iep3n5uvez362lek4ixjysgeefk5esxyd.local", #api/webui domain
        "http://localhost:3000",
        "http://127.0.0.1:5001",
        "https://webui.ipfs.io",
        "http://ipfs.embassy:5001",
        "https://rfu6pj36capximdisyvwxyjnhlwyeovf4gcmz4hvuptaetwduslav3id.local", #gateway domain
        "https://0.0.0.0:8080"
      ]
    }
  },
  "Addresses": {
    "API": "/ip4/0.0.0.0/tcp/5001",
    "Announce": [],
    "AppendAnnounce": [],
    "Gateway": "/ip4/0.0.0.0/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic",
      "/ip6/::/udp/4001/quic"
    ]
  },
  "AutoNAT": {},
  "Bootstrap": [
    "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.131.131.82/udp/4001/quic/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt"
  ],
  "DNS": {
    "Resolvers": {}
  },
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "10GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 10
    }
  },
  "Experimental": {
    "AcceleratedDHTClient": false,
    "FilestoreEnabled": false,
    "GraphsyncEnabled": false,
    "Libp2pStreamMounting": true,
    "P2pHttpProxy": false,
    "StrategicProviding": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": false,
    "PathPrefixes": [],
    "PublicGateways": {
      "localhost": null,
      "rfu6pj36capximdisyvwxyjnhlwyeovf4gcmz4hvuptaetwduslav3id.local": {
        "Paths": [
          "/ipfs",
          "/ipns"
        ]
      }
    },
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "12D3KooWPCNH8gBqGuuCxerv3wLEjBEEWHYJXxa8eUcsNSjLS6cm"
  },
  "Internal": {},
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Migration": {
    "DownloadSources": [],
    "Keep": ""
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Peering": {
    "Peers": null
  },
  "Pinning": {
    "RemoteServices": {}
  },
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {
    "Interval": "12h",
    "Strategy": "all"
  },
  "Routing": {
    "Type": "dht"
  },
  "Swarm": {
    "AddrFilters": null,
    "ConnMgr": {
      "GracePeriod": "20s",
      "HighWater": 900,
      "LowWater": 600,
      "Type": "basic"
    },
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "RelayClient": {
      "Enabled": true
    },
    "RelayService": {},
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  },
  "Transports": {
    "Network": {
      "Relay": true
    }
  }
}
```

### Description

I am trying to package IPFS for [embassy-os](https://github.com/Start9Labs/embassy-os). See [this discussion forum post](https://discuss.ipfs.tech/t/cannot-access-gateway-over-mdns-local/15199) for some background on embassy-os.

1) Run `kubo` v0.15.0 in a docker container on a raspberry pi on my home network using https://github.com/chrisguida/ipfs-wrapper. The Dockerfile here is pretty much the same as the Dockerfile included in the `kubo` repo, with some slight modifications to adapt it to .
2) configure `kubo` as in [this entrypoint](https://github.com/chrisguida/ipfs-wrapper/blob/master/docker_entrypoint.sh).
3) In the webui, go to the "Files" tab and select any file to view it. The `ipfs.io` public gateway sometimes displays the file after a long wait. Other times, if I open the browser console I can see this error:

<img width="647" alt="Screen_Shot_2022-09-20_at_3 05 31_PM" src="https://user-images.githubusercontent.com/7445670/191531046-a1bc89eb-ec3d-48cb-b5ce-64648330be1f.png">

(As you can see, the browser does not like that the request to `http://0.0.0.0:8080` is cleartext HTTP, while the domain I'm viewing the webui through is HTTPS ("https://djnofp2u5mvjsewk7anxsj4iep3n5uvez362lek4ixjysgeefk5esxyd.local" in the above example config). Actually, I'm not even sure what `http://0.0.0.0:8080` is supposed to me. I do know that if I run `kubo` locally on my laptop, this request succeeds. How firefox is able to resolve this URL, ever, is beyond me.)

But since the point of embassy-os is to self-host, we want to avoid "public" gateways and use the gateway on our own device, which responds much faster anyway. If I go to the webui "Settings" tab and enter in my gateway address ("https://rfu6pj36capximdisyvwxyjnhlwyeovf4gcmz4hvuptaetwduslav3id.local" in the example config) into the "public gateway" field, clicking on files now works, and sends the files through my local gateway properly.

Issue #1: I would like to be able to configure this setting programmatically, ie in `docker_entrypoint.sh`. Requiring the user to manually find their gateway domain and input it into this settings field adds a lot of friction to the UX. However, that can be worked around for now if it's the only way. The real bug is below:

Issue #2: When I click "Download" on any file, *even after manually setting the gateway in the webui*, the browser still requests `http://0.0.0.0:8080`, rather than the local gateway I've configured. This of course results in an error. This makes it so that the user cannot download a file through the UI. The bizarre thing is that if I manually alter the download URL to replace `http://0.0.0.0:8080` with the local gateway URL ("https://rfu6pj36capximdisyvwxyjnhlwyeovf4gcmz4hvuptaetwduslav3id.local" in the example config), the file can be viewed through the browser just fine. For some reason, the webui is unable to simply link the user directly to the local gateway, *even when it is specifically configured in the webui*.

It's possible I'm missing a config value somewhere, as I'm fairly new to `kubo`, but this definitely seems like at least a documentation issue, and probably a bug in the webui.

Please let me know how I can help debug/fix this, as our community is asking for access to IPFS on embassy-os!

Thanks in advance,

--Chris

**Comment by Jorropo** [comment]
See our discussion on discord, this isn't a setup we support.

The best quick win that would solve your problem is webui trying `$API/ipfs/` to see if it's a valid IPFS gateway.

**Comment by chrisguida** [comment]
@Jorropo I don't understand what you're saying. You literally told me to open an issue about this in our Discord converation:

<img width="736" alt="Screen Shot 2022-09-22 at 4 19 36 PM" src="https://user-images.githubusercontent.com/7445670/191853057-555607e9-c948-4ad7-a6f6-b38b3e44779f.png">

What do you mean "webui trying `$API/ipfs/`? I don't know what that means. Please explain.

**Comment by chrisguida** [comment]
Also, if I can't solve this, then that means embassy-os users will be unable to use IPFS. I am willing to contribute a PR to fix this if needed. Please don't just dismiss this.

**Comment by lidel** [comment]
I am moving this to ipfs-webui repo :-) 

@chrisguida I am not familiar with embassy-os, so apologies if some suggestions are not feasible, or you already know these things, but here are some quick thoughts (jump to :point_right:  for potential fix):

- ipfs-webui is designed to talk to local Kubo node via  `/api/v0` RPC, within the same origin and use gateway on the same box
- `/api/v0` endpoint  grants  ADMIN level permissions to your IPFS daemon, and the only officially upported Origin in browser context is `localhost`
  - (this is to say, you have very custom setup that maintainers have no bandwidth to support, but read ideas below)
- is running on `*.local` a hard requirement?
  - I see you have TLS cert, so i guess you don't care or don't have mixed-content issues, but the usual advice for people who want to access API and webui remotely is SSH tunneling of API and  gateway ports both looks like `localhost` – it  solves all issues in browser context, and may be more future-proof   than using custom LAN hostnames.
  - For a browser, the "listen on all interfaces" `0.0.0.0` is turned into `127.0.0.1` (loopback IP, same as localhost) – that is why it works  locally in your Firefox :)
  - any reason why you disabled subdomains on `locahost` by setting it to `null` in `PublicGateways`?  you may want to remove that line, just so you are not suprised if you ever need it.
- ipfs-webui will try to use local gateway before resorting to public one
  - It [reads the first item from `Addresses.Gateway` in the config](https://github.com/ipfs/ipfs-webui/blob/5011e120e59bb5b07bc28bdfb60ed6a5128fc525/src/bundles/config.js#L97-L111)  (this field can be either a String, or an array of strings) and tries to use it instead of public gateway (which is used only as last resort).
    - :point_right:  Your `Addresses.Gateway` is `"/ip4/0.0.0.0/tcp/8080"`, and ipfs-webui parses that as  localhost (which is what 99,9% use cases want), but that is not the behavior your custom setup requires. 
      - Potential fix here is to change `Addresses.Gateway` to array and put your  an explicit address there first, so ipfs-webui picks it up and uses it instead of `0.0.0.0` 
      - If your gateway is at `https://ipfsgw.local` or LAN IP `A.B.C.D` then try seting `Addresses.Gateway` to one of the arrays below and see if any of them works (you need to reboot daemon for the config to be applied):
         - `["/dns4/ipfsgw.local/tcp/443", "/ip4/0.0.0.0/tcp/8080"]`
         - `["/ip4/A.B.C.D/tcp/443", "/ip4/0.0.0.0/tcp/8080"]`
