### ISSUE TITLE
Enable WebTransport by default

### ISSUE THREAD

**Issue by Jorropo** [ipfs/kubo#9292]
# Done criteria
1. libp2p's WebTransport transport is enabled by default.
2. There are corresponding docs that describe how/why to use this.

# Background
With #9289 Kubo added opt-in webtransport support.  This is covered more in [the spec](https://github.com/libp2p/specs/pull/404), but WebTransport provides a performant way for browsers (Chromium currently) to connect with the rest of the libp2p network.  We want to enable browser nodes to be able to communicate easily with other nodes in the network.  To accomplish this we need a good amount of nodes in the network to have webtransport listen addresses.  Getting Kubo nodes having WebTransport listening by default is a good way to increase the number of nodes that browser nodes can connect to.

# Preconditions
1. go-libp2p WebTransport transport has shown to be stable.  This will come from WebTransport being used in the wild, including enabling it on some of PL's infra per https://github.com/protocol/bifrost-infra/issues/2114 .  (Additional tracking of go-libp2p's WebTransport work is in https://github.com/libp2p/go-libp2p/issues/1717 or will be linked from there.)
2. webtransprot and quic can listed on the same port in go-libp2p: https://github.com/libp2p/go-libp2p/issues/1759
   - https://github.com/libp2p/go-libp2p/issues/1766
   - https://github.com/ipfs/kubo/issues/9410

# Notes about the work involved
1. This does involve a config migration
2. Documenting the browser/Kubo communication story is covered https://github.com/ipfs/ipfs-docs/issues/1286

**Comment by marten-seemann** [comment]
Here's the go-libp2p tracking issue for everything that needs to be done before we can consider WebTransport "done".

**Comment by BigLep** [comment]
2022-12-08 conversation: 
- [ ] first blocked on the libp2p 0.24 upgrade: https://github.com/ipfs/kubo/pull/9423
- [ ] there is a small code change to do in Kubo
- [ ] needs config.md update
- [ ] needs changelog
