### ISSUE TITLE
IPfs Editor Markdown

### ISSUE THREAD

**Issue by fanhai** [ipfs/kubo#9296]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

我觉得作为分布式存储和共享文件的网络传输协议的ipfs，应该具备直接编辑和显示内容的入口，类似markdown，将图片视频信息编码后存入ipfs，并在显示时自动解码
I think that as a network transmission protocol for distributed storage and file sharing, ipfs should have an access to directly edit and display content, similar to markdown, which encodes pictures and videos into ipfs and automatically decodes them when they are displayed

**Comment by Stebalien** [comment]
This is a good idea but not really relevant to kubo specifically. It's a project that would be built on top of it.

I suggest making a post on [discuss.ipfs.io](https://discuss.ipfs.io). You may also be interested in some of the projects listed in https://ecosystem.ipfs.tech/. My favorate project in this category is anytype.
