### ISSUE TITLE
File path in *.sha512 should not be absolute path

### ISSUE THREAD

**Issue by suzuki-shunsuke** [ipfs/kubo#9323]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

third-party binary

### Description

The content of [kubo_v0.16.0_darwin-arm64.tar.gz.sha512](https://github.com/ipfs/kubo/releases/download/v0.16.0/kubo_v0.16.0_darwin-arm64.tar.gz.sha512) is wrong.

Expected content

```
62f84350d3c3ccbb29f9cb0b21d437c1d21be6ad8127343bd7920fabb219779d9d3c961b64c879608ad9485aca116e8f9884d252a340c702d58686764195582a  kubo_v0.16.0_darwin-arm64.tar.gz
```

Actual content

```
62f84350d3c3ccbb29f9cb0b21d437c1d21be6ad8127343bd7920fabb219779d9d3c961b64c879608ad9485aca116e8f9884d252a340c702d58686764195582a  /Users/runner/work/distributions/distributions/releases/kubo/v0.16.0/kubo_v0.16.0_darwin-arm64.tar.gz
```

I guess this is the absolute path in GitHub Actions, but I think this should be only a file name.

ref. https://github.com/ipfs/kubo/blob/199fa47e51149fa24ff2b38a198ed3c72951725b/.github/workflows/sync-release-assets.yml#L24-L128

**Comment by hsanjuan** [comment]
Possible fix here: https://github.com/ipfs/distributions/pull/1108

**Comment by lidel** [comment]
Confirmed the fix works. 

Reopening here as this will be applied to Kubo 0.32 so we need to wait until https://github.com/ipfs/kubo/issues/10547 is closed.
