### ISSUE TITLE
README.md: Scoop command needs updating

### ISSUE THREAD

**Issue by redactedscribe** [ipfs/kubo#9325]
### Checklist

- [X] I am reporting a documentation issue in this repo, not https://docs.ipfs.tech.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Location

https://github.com/ipfs/kubo#scoop

### Description

go-ipfs manifest no longer exists at: https://github.com/ScoopInstaller/Extras/blob/master/bucket/go-ipfs.json

It has been renamed to kubo and now resides in the Main bucket: https://github.com/ScoopInstaller/Main/blob/master/bucket/kubo.json

The new README.md steps should read (no need to add any bucket):

```powershell
PS> scoop install kubo
```

**Comment by guseggert** [comment]
We don't actively maintain "unofficial" packages, so we can't really help here. You should reach out to whomever maintains the scoop package.
