### ISSUE TITLE
Error while using the bootstrap

### ISSUE THREAD

**Issue by stanlypalathingal** [ipfs/kubo#9329]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.tech

### Version

```Text
go-ipfs version: 0.14.0-rc1
Repo version: 12
System version: amd64/linux
Golang version: go1.18.3
```

### Description

I can access and add file to bootstrap nodes using the command-line, ie, "ipfs add file" add file to the bootstrap nodes and i can access it in those terminal as well.

But while using it with through the example given in  https://github.com/ipfs/kubo/tree/master/docs/examples/kubo-as-a-library    
gives the following error 

2022/10/05 12:10:07 failed to connect to 12D3KooWBCesoUHUGM19ztUF84DCnAdChawTafAuRE3pewHYsGWx: failed to dial 12D3KooWBCesoUHUGM19ztUF84DCnAdChawTafAuRE3pewHYsGWx:
  * [/ip4/54.82.186.217/tcp/4001] failed to negotiate security protocol: incoming message was too large
2022/10/05 12:10:07 failed to connect to 12D3KooWH4QZVZXt65UFCvCYfTdbL5sCWRHc5JLtRYaGECF18gJM: failed to dial 12D3KooWH4QZVZXt65UFCvCYfTdbL5sCWRHc5JLtRYaGECF18gJM:
  * [/ip4/3.80.214.188/tcp/4001] failed to negotiate security protocol: incoming message was too large

I checked swarm keys given are correct since it works well with commandline option

**Comment by guseggert** [comment]
Can you upgrade to the latest version of kubo and see if you still have this issue?
