### ISSUE TITLE
Remove Chocolatey releases

### ISSUE THREAD

**Issue by galargh** [ipfs/kubo#9341]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

Similarly to https://github.com/ipfs/kubo/issues/8688, let's consider removing Kubo from Chocolatey: https://community.chocolatey.org/packages/go-ipfs

**Comment by lidel** [comment]
I think it would be nice to nudge people away from removed distribution channels, so they are not stuck on old versions.

My vote is to create a binary that exits with error code 1 and prints a message that informs the user to use official binaries from https://dist.ipfs.tech#kubo (or https://hub.docker.com/r/ipfs/kubo/). 
It would be then published to chocolatey and snap (https://github.com/ipfs/kubo/issues/8688)

**Comment by galargh** [comment]
I agree that creating such a binary provides a much better UX. With the creds you gave me I should be able to do that for `snap` now and I plan to use creds set up in https://github.com/ipfs/choco-go-ipfs to do the same for chocolatey.

**Comment by galargh** [comment]
Here's the plan for completing this issues:
- [ ] Disable automatic Chocolatey releases (https://github.com/ipfs/choco-go-ipfs/pull/3)
- [ ] Prepare workflow which can produce a binary with information about Chocolatey deprecation (https://github.com/galargh/kubo/actions/workflows/dist.yml)
- [ ] Update download paths in the Chocolatey releaser (https://github.com/ipfs/choco-go-ipfs/blob/main/go-ipfs/update.ps1#L27-L28)
- [ ] Wait for the Kubo v0.17.0 release
- [ ] Build Kubo "v0.17.0" which only prints information about Chocolatey deprecation (https://github.com/galargh/kubo/actions/workflows/dist.yml)
- [ ] Release to Chocolatey
- [ ] Archive https://github.com/ipfs/choco-go-ipfs 


Here's the proposed deprecation text:
```
Kubo is not distributed through Chocolatey anymore (https://github.com/ipfs/kubo/issues/9341).
Please download Kubo from https://dist.ipfs.tech/#kubo.
```
