### ISSUE TITLE
Windows arm64 native support

### ISSUE THREAD

**Issue by mihaiplesa** [ipfs/kubo#9365]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

Would be nice for every release to include arm64 artifacts for Windows just like for Linux and macOS do now.

**Comment by guseggert** [comment]
This sounds like a great idea, we will pick this up soon.
