### ISSUE TITLE
Add optional Pubsub.SeenMessagesTTL to Kubo config

### ISSUE THREAD

**Issue by smrz2001** [ipfs/kubo#9371]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

As discussed in [this](https://filecoinproject.slack.com/archives/C025ZN5LNV8/p1661459082059149) Slack thread, this is a feature request to make `Pubsub.SeenMessagesTTL` configurable in Kubo's Pubsub [config](https://github.com/ipfs/kubo/blob/master/docs/config.md#pubsub):

> - Kubo uses https://github.com/libp2p/go-libp2p-pubsub/ which has [default TimeCacheDuration set to 120 seconds](https://github.com/libp2p/go-libp2p-pubsub/blob/4f56e8f0a75b06aff68ae79717915ebadc1698f6/pubsub.go#L30-L32).   This is how long it will remember "already seen message IDs".
>   - This is the [same as in JS implementation](https://github.com/ChainSafe/js-libp2p-gossipsub/blob/6bf0693f924785abd933c9ee37332ab00ce947d0/src/constants.ts#L217) (which was bumberd from 30s to 2m to match GO)
> There is no configuration option in Kubo to increase this duration atm, but we could expose one in future version (we release ~every 5 weeks)
>    - go-libp2p-pubsub supports custom initialization via  `WithSeenMessagesTTL`  but it is not wired up in Kubo's config yet
>     - If you find this useful, please open feature request to add optional  `Pubsub.SeenMessagesTTL`  to [Kubo's config](https://github.com/ipfs/kubo/blob/master/docs/config.md#pubsub) (https://github.com/ipfs/kubo/issues/)  

Support for this option is now available in `go-libp2p-pubsub` [v0.7.0](https://github.com/libp2p/go-libp2p-pubsub/releases/tag/v0.7.0) onwards.

As explained in that thread, we would very much like to be able to use this option to adjust the duration for which pubsub messages can remain active on the network.

**Comment by lidel** [comment]
Exposing this as [optionalDuration](https://github.com/ipfs/kubo/blob/master/docs/config.md#optionalduration) in the config sounds sensible.  

If someone wants this feature and is willing to submit a PR, we are happy to review.
