### ISSUE TITLE
Automate Kubo release process

### ISSUE THREAD

**Issue by galargh** [ipfs/kubo#9441]
### Description

Kubo release process contains a lot of steps. This issue is about identifying the steps that could be automating and automating them in a way that can be performed both by the CI and developers.

Things to consider for the automation:
- might be nice to use Go for automation scripts
- some steps might require user input
- possibly, not all the steps can be automated
- it should be possible to run the automation locally and in CI
- _stretch_: it would be great if it didn't require a single person to perform all the steps
- how can we edit the automated steps?

**Comment by BigLep** [comment]
@galargh : what are you thoughts here?  It seems like the immediate work is done?  Is there a followup issue you're thinking to create?

**Comment by galargh** [comment]
Yes, I'd consider this piece of work complete. Further tasks will be captured via kuboreleaser issues - https://github.com/ipfs/kuboreleaser/issues
