### ISSUE TITLE
feat: create `kubo` recipe in homebrew

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/kubo#9449]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

We should create a new recipe in brew.sh for kubo. Currently, it's still using old `ipfs` namespace.

### Open questions:
- [ ] Should we keep publishing `ipfs` recipe and publish an additional `kubo` recipe?
- [ ] Can we create an alias from a new `kubo` recipe to the original `ipfs` recipe or vice/versa?

### Related
* https://github.com/ipfs/kubo/blame/3b00c81c8d92683d5ff6454827e20ec917da710e/README.md#L241-L245
* https://formulae.brew.sh/formula/ipfs#default
* https://formulae.brew.sh/formula/kubo#default (404) should be alias for ipfs or vice/versa
* https://github.com/ipfs/kubo/issues/8959

**Comment by lidel** [comment]
Kubo project only maintains official Docker images at https://hub.docker.com/r/ipfs/kubo/ and signed binaries at https://dist.ipfs.tech/#kubo

Everything else is maintained by community – i am closing this, but feel free to open PR against brew if you use it :-)

ps. note other package managers already renamed, without Kubo team's involvement, for example:
- https://archlinux.org/packages/community/x86_64/kubo/
- https://github.com/NixOS/nixpkgs/blob/release-22.11/pkgs/applications/networking/kubo/default.nix
- https://pkgs.alpinelinux.org/packages?name=kubo
