### ISSUE TITLE
Update `lowpower` profile to try HTTP routing first, and use DHT as a fallback / after a delay

### ISSUE THREAD

**Issue by guseggert** [ipfs/kubo#9480]
Followup from https://github.com/ipfs/kubo/pull/9475:

> @lidel: [`lowpower` profile](https://github.com/ipfs/kubo/blob/master/docs/config.md#profiles) uses `dhtclient`, but it would benefit the most from defaulting to HTTP IPNI router, and try DHT only if there was no response from HTTP (delay DHT lookup for ~3s or similar, giving HTTP chance to finish)

**Comment by lidel** [comment]
No, this is actually a different feature, I'll update the title.
