### ISSUE TITLE
ipfs should default to CIDv1

### ISSUE THREAD

**Issue by rlaferla** [ipfs/kubo#9494]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

`ipfs` should default to CIDv1 (multibase)

"If you can't decide between CIDv0 and CIDv1, consider choosing CIDv1 for your new project and opt in by passing a version flag (ipfs add --cid-version 1). This is more future-proof and [safe for use in browser contexts](https://docs.ipfs.tech/how-to/address-ipfs-on-web/#subdomain-gateway).

The IPFS project will switch to CIDv1 as the new default in the near future.

[#](https://docs.ipfs.tech/concepts/content-addressing/#cid-inspector)"

**Comment by lidel** [comment]
Tracked in https://github.com/ipfs/kubo/issues/4143.
