### ISSUE TITLE
Routing.Type=auto: announcements over HTTP PUT cid.contact always fail

### ISSUE THREAD

**Issue by lidel** [ipfs/kubo#9504]
### Version

```Text
0.18.0-rc1
```

### Config

```json
default produced by 'ipfs init' (Routing.Type=auto)
```

## Problem

Only `GET /routing/v1/providers/{CID}` in [IPIP-337](https://github.com/ipfs/specs/pull/337) is currently supported by https://cid.contact/, and they have no short term plans to enable it.

At the same time, Kubo 0.18.0-rc1 running with `Routing.Type=auto` (default) sends HTTP PUTs that will always fail.

## Solution

TBD, two obvious options come to mind: 
- (A) disable announcing over HTTP in `auto` mode  for now, we will enable it in the future release after cid.contact supports it
- (B) make it future-proof: detect IPNI being read-only (failing HTTP PUT multiple times) and temporarily block announcements on it (e.g. for 22h, to match default Reprovide.Interval)

I don't know how "stable" `PUT /routing/v1/providers` API is. If it is ready, then my vote would be to implement (B) in 0.18.0-rc2, as it is safer behavior that accounts for the slow rate of nodes updating to new versions of Kubo. (B) allows 0.18 nodes to start publishing as soon cid.contact supports it.

cc @ajnavarro @guseggert @willscott @masih

**Comment by ajnavarro** [comment]
We could use https://github.com/hashicorp/go-retryablehttp . Integration should be easy. WDYT?

**Comment by masih** [comment]
For reference IPNI [will return `501 Not Implemented` on `PUT`](https://github.com/ipni/indexstar/pull/55). That status code is not a retry-able error really, so maybe upon observing that status code the logic can aggressively increase retry intervals between consecutive `PUT`s, e.g. in order of days.
