### ISSUE TITLE
`Cache-Control: only-if-cached` gives incorrect response for inline CIDs

### ISSUE THREAD

**Issue by Winterhuman** [ipfs/kubo#9512]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.tech

### Version

```Text
N/A
```

### Config

```json
N/A
```

### Description

Related: https://github.com/ipfs/specs/issues/358

When using `Cache-Control: only-if-cached` & inline CIDs, public gateways respond with both `HTTP/2 200` and `MISS`, instead of `200+HIT` or `412+MISS`. The specs for `Cache-Control` handling doesn't mention any special handling for inline CIDs, so I'm not sure if 200 or 412 is the correct response (`200 + miss` definitely isn't correct though)

**Comment by Winterhuman** [comment]
@lidel Any chance you know what the correct response code should be in this case?

**Comment by lidel** [comment]
Identity CID is logically the same state as if block was in local datastore – gateway can respond without doing any p2p. 

And that is exactly how Kubo implements it. Requesting zero-length identity CID returns 200:

```console
$ curl -v -H "Cache-Control: only-if-cached" http://127.0.0.1:8080/ipfs/bafkqaaa
*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /ipfs/bafkqaaa HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.86.0
> Accept: */*
> Cache-Control: only-if-cached
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: Content-Type
< Access-Control-Allow-Headers: Range
< Access-Control-Allow-Headers: User-Agent
< Access-Control-Allow-Headers: X-Requested-With
< Access-Control-Allow-Methods: GET
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Content-Length
< Access-Control-Expose-Headers: Content-Range
< Access-Control-Expose-Headers: X-Chunked-Output
< Access-Control-Expose-Headers: X-Ipfs-Path
< Access-Control-Expose-Headers: X-Ipfs-Roots
< Access-Control-Expose-Headers: X-Stream-Output
< Cache-Control: public, max-age=29030400, immutable
< Content-Type: text/plain
< Etag: "bafkqaaa"
< X-Ipfs-Path: /ipfs/bafkqaaa
< X-Ipfs-Roots: bafkqaaa
< Date: Thu, 19 Jan 2023 19:58:10 GMT
< Content-Length: 0
```

The `MISS` you described is not part of Kubo, nor a part of [gateway specification](https://github.com/ipfs/specs/tree/main/http-gateways#readme), it is just a diagnostic header added by CDN that is in front of Kubo on `ipfs.io`:

```console
curl -v -H "Cache-Control: only-if-cached" http://ipfs.io/ipfs/bafkqaaa
*   Trying 209.94.90.1:80...
* Connected to ipfs.io (209.94.90.1) port 80 (#0)
> GET /ipfs/bafkqaaa HTTP/1.1
> Host: ipfs.io
> User-Agent: curl/7.86.0
> Accept: */*
> Cache-Control: only-if-cached
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: openresty
< Date: Thu, 19 Jan 2023 20:00:35 GMT
< Content-Type: text/plain
< Content-Length: 0
< Connection: keep-alive
< Access-Control-Allow-Methods: GET
< Cache-Control: public, max-age=29030400, immutable
< Etag: "bafkqaaa"
< X-Ipfs-Gateway-Host: ipfs-bank13-fr2
< X-Ipfs-Path: /ipfs/bafkqaaa
< X-Ipfs-Roots: bafkqaaa
< X-IPFS-POP: ipfs-bank13-fr2
< Timing-Allow-Origin: *
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, OPTIONS
< Access-Control-Allow-Headers: X-Requested-With, Range, Content-Range, X-Chunked-Output, X-Stream-Output
< Access-Control-Expose-Headers: Content-Range, X-Chunked-Output, X-Stream-Output
< X-IPFS-LB-POP: gateway-bank1-fr2
< X-Proxy-Cache: HIT
```

This is an additional layer of caching, not related to IPFS, Kubo, or Gateway.
