### ISSUE TITLE
0.18.0-rc2: 400 when "Accept: application/json, text/plain"

### ISSUE THREAD

**Issue by hamptonsmith** [ipfs/kubo#9520]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

ipfs-desktop

### Version

```Text
docker run -p 8080:8080 --rm ipfs/kubo:v0.18.0-rc1
```

### Config

```json
Default for docker container.
```

### Description

Pinata made my Christmas interesting by making rc0.18 their prod-facing release, so apologies if this RC isn't to the point of stability where you care about this sort of thing, but since I did all the work to track it down, here's the info. :) Best!

```shell
$ docker run -p 8080:8080 --rm ipfs/kubo:v0.18.0-rc1 &
$ http localhost:8080/ipfs/bafybeieznmzzuxoxqwmkgy5yycefaehgoswvc6yiu6mfhbblzkkj77w7oa Accept:'application/json'
> [200 OK, ...successful output...]
$ http localhost:8080/ipfs/bafybeieznmzzuxoxqwmkgy5yycefaehgoswvc6yiu6mfhbblzkkj77w7oa Accept:'application/json, text/plain'
> HTTP/1.1 400 Bad Request
Content-Length: 87
Content-Type: text/plain; charset=utf-8
Date: Mon, 26 Dec 2022 12:02:19 GMT
Location: http://bafybeieznmzzuxoxqwmkgy5yycefaehgoswvc6yiu6mfhbblzkkj77w7oa.ipfs.localhost:8080/
X-Content-Type-Options: nosniff

error while processing the Accept header: mime: unexpected content after media subtype
$ http localhost:8080/ipfs/bafybeieznmzzuxoxqwmkgy5yycefaehgoswvc6yiu6mfhbblzkkj77w7oa Accept:'foo/bar, application/json, text/plain'
> [200 OK, ...successful output...]
```

Suspect this was introduced in https://github.com/ipfs/kubo/commit/fdd19656c465f07ff6d7be653f5438d74a0c0c2f with error on line https://github.com/ipfs/kubo/blob/fdd19656c465f07ff6d7be653f5438d74a0c0c2f/core/corehttp/gateway_handler.go#L898

**Comment by stevedsimkins** [comment]
We've also come across this problem and believe its from this PR https://github.com/ipfs/kubo/pull/9335

**Comment by lidel** [comment]
Thank you for reporting this.

Confirmed, this is still the problem with `0.18.0-rc2`, error appears only when `application/json` is the first on the list that has more than one item.

Repro:

```console
$ curl -H "Accept: application/json" "http://127.0.0.1:8080/ipfs/bafybeieznmzzuxoxqwmkgy5yycefaehgoswvc6yiu6mfhbblzkkj77w7oa"
{"Data":{"/":{"bytes":"CAIStwJ7Im5hbWUiOiJNQURFLi4uIiwiZGVzY3JpcHRpb24iOiIuLi4gc2l0dGluZyBvbiBhIGNoYWlyIGluIHRoZSBza3kgLiIsImltYWdlIjoiaHR0cHM6Ly9jaWwuYXBpLmJhbmR3YWdvbmZhbmNsdWIuY29tL2NvbGxlY3Rpb25zL3BvZXQvaW1hZ2VzL0d4YkhnNHROYlNhaXVOaTJteXpMaUJrWk4xNjZYNDV5UkxZbzNyaHZqZEtVIiwidGFncyI6WyJwYWludGluZyIsImRpZ2l0YWxwYWludCIsImZyYW1lYnlmcmFtZSIsImFuaW1hdGlvbiIsImdpZiJdLCJwb2V0T3duZXIiOiIweGFiMzYyNzMxN2M0M2QzOTRlYjE3MTE3MGY4MTgxNTNiOTc2ZDI4YTMifRi3Ag"}},"Links":[]}

$ curl -H "Accept: application/json, plain/text" "http://127.0.0.1:8080/ipfs/bafybeieznmzzuxoxqwmkgy5yycefaehgoswvc6yiu6mfhbblzkkj77w7oa"
error while processing the Accept header: mime: unexpected content after media subtype
```

This is a bug in the way we parse `Accept` header, block/car responses always had single explicit type, with JSON we should fix this. 

Will prepare fix shortly.
