### ISSUE TITLE
Add --cid-version at files stat

### ISSUE THREAD

**Issue by thedmdim** [ipfs/kubo#9529]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

Hello, I found out that there is no --cid-version option in  `ipfs files stat <path>` and it only returns CIDv0. 
So to get CIDv1 we need to make two steps:
- get CIDv0 of needed MFS path
- convert CIDv0 to v1

As for using RPC API the suggested feature would save twice as many requests.

**Comment by lidel** [comment]
You can use `ipfs files stat --cid-base base32 /cat.jpg` :sparkles:
