### ISSUE TITLE
Fail if Swarm.ConnMgr.HighWater is above Swarm.ResourceMgr hard limits

### ISSUE THREAD

**Issue by BigLep** [ipfs/kubo#9549]
## Done Criteria
User get a clear message to the console and a terminated process if their Swarm.ConnMgr config has know issues.  Specifically:
if the resource manager is enabled,``Swarm.ConnMgr.HighWater`` must be below ``Swarm.ResourceMgr.System.Conns`` and  (``Swarm.ResourceMgr.System.ConnsInbound`` +  ``Swarm.ResourceMgr.System,ConnsOutbound``).  

- [ ] Code change (above)
- [ ] Docs update: https://github.com/ipfs/kubo/blob/master/docs/config.md#swarmconnmgr

## Why Important
If the soft connection manager limits are above the hard resource manager limits, then the soft connection manager will never kick in and there will be a confusing user experience.

This is a footgun that Kubo maintainers have observed during the 0.18RC phase.

Similar to https://github.com/ipfs/kubo/issues/9546, Swarm.ConnMgr has been present in Kubo for years and users have adjusted this value for their usecses. While https://github.com/ipfs/kubo/issues/9546 should help, it's still possible that a user's ConnMgr and ResourceMrg limits aren't configured appropriately relative to each other.  This acts as a backstop to catch this case. 

## Notes
* There is a backlog item in go-libp2p to better connect the connection manager and resource manager: https://github.com/libp2p/go-libp2p/issues/1640 .  To control the experience, we're solving this at the Kubo level with this issue.

**Comment by ajnavarro** [comment]
@Jorropo I assigned to you because you moved it from TODO to In Progress, to avoid confusion.

**Comment by BigLep** [comment]
@Jorropo @lidel : I saw we have the code change in #9560 .  What about the docs change for https://github.com/ipfs/kubo/blob/master/docs/config.md#swarmconnmgr ?
