### ISSUE TITLE
Replace flaky test/sharness/t0172-content-routing-over-http.sh  with go harness

### ISSUE THREAD

**Issue by lidel** [ipfs/kubo#9562]
Ref. https://github.com/ipfs/kubo/pull/9550/files#r1071977682

We already have https://github.com/ipfs/kubo/blob/master/test/cli/delegated_routing_http_test.go, we should move tests from sharness to that.

**Comment by BigLep** [comment]
@guseggert : I am moving this to 0.21 as I know we already have a lot on our plate, but feel free to pull in sooner if it will get fixed sooner as part of flaky erradication that is tripping up our CI.

**Comment by BigLep** [comment]
@lidel is going to see if that has already been migrated.  If it hasn't, they'll move it above the line.

**Comment by lidel** [comment]
This was fixed in https://github.com/ipfs/kubo/pull/9772
