### ISSUE TITLE
ci/gh-experiment: sharness fails: Downloaded SaxonHE11-4J.zip has wrong md5sum

### ISSUE THREAD

**Issue by lidel** [ipfs/kubo#9567]
"Run Sharness tests":

```
*** test/sharness/download-saxon ***
Downloading SaxonHE11-4J.zip
Downloaded SaxonHE11-4J.zip has wrong md5sum ('291fc26f7a9fcf73b9425e27592e6051' != '8a4783d307c32c898f8995b8f337fd6b')
[...]
Error: Process completed with exit code 2.
```

Log: https://github.com/ipfs/kubo/actions/runs/3959053284/jobs/6781377209#step:17:50

@galargh perhaps we could add these artifacts to IPFS and fetch them from gateway like we [do with webui in ipfs-desktop](https://github.com/ipfs/ipfs-desktop/blob/8aca5c268aea9d7066f2853639239563e4606545/package.json#L20) + add 2-3x  retry so we don't break CI on HTTP hiccups?

**Comment by galargh** [comment]
Thanks for letting me know! I'll try to get to it tomorrow.

**Comment by galargh** [comment]
Looks like https://sourceforge.net/projects/saxon/files/Saxon-HE/11/Java/SaxonHE11-4J.zip disappeared 🤦
