### ISSUE TITLE
ipfs swarm limit all --reset does not remove user overrides from Swarm.ResourceMgr.Limits

### ISSUE THREAD

**Issue by lidel** [ipfs/kubo#9576]
UX problem:
It is impossible to reset all scopes via single CLI/RPC call.
User is forced to list them first, and then remove manually one by one:

```console
$ ipfs swarm limit --help
...
  The scope can be one of the following:
  - all           -- all limits actually being applied.
  - system        -- limits for the system aggregate resource usage.
...

$ ipfs swarm limit all --reset
Error: invalid scope "all"
```

cc https://github.com/ipfs/kubo/issues/9417 (but not a hard blocker, we can fix this in 0.19)

**Comment by ajnavarro** [comment]
Possible alternative solution https://github.com/ipfs/kubo/issues/9603

**Comment by BigLep** [comment]
Agreed that we'll do https://github.com/ipfs/kubo/issues/9603 which neutralizes the need to solve this.  I'm closing this as won't fix.
