### ISSUE TITLE
ipfs swarm peers --enc=json --identify

### ISSUE THREAD

**Issue by lidel** [ipfs/kubo#9578]
Peers screen in ipfs-webui could show the agent versions, and all supported protocols, but it is too expensive to do `ipfs.id` call for each peer – especially in browser.

We already have `ipfs swarm peers --enc=json --streams` opt-in flag which fills `Streams` field in JSON response for each peer, example:

```json
{
      "Addr": "/ip4/97.70.169.114/udp/4001/quic",
      "Peer": "12D3KooWDqzNdf6Ctcm8Xp89x7MWcdSbCFwnXeNfNXHhBjpr9jx9",
      "Latency": "",
      "Muxer": "",
      "Direction": 0,
      "Streams": [
        {
          "Protocol": "/ipfs/kad/1.0.0"
        }
      ]
    }
```

`Streams` info is used for "Open Streams" column on the peers screen, but it only shows active streams, not all supported protocols and versions:

> ![Screenshot 2023-01-23 at 19-11-17 Peers IPFS](https://user-images.githubusercontent.com/157609/214117085-dd3daf3a-6cc1-4222-823a-d9da2cb6a40f.png)

### Proposed improvement 

Support passing `--identify` which adds `Identify` values, could be the same struct as one returned by  `ipfs id` ([result of libp2p's identify protocol](https://github.com/libp2p/specs/tree/master/identify)): 

```json
{
      "Addr": "/ip4/95.208.80.171/udp/4001/quic",
      "Peer": "12D3KooWNCogGjemMiMjZmDxyVcrjP3KW7VFdSPTTGousXEhczuq",
      "Latency": "",
      "Muxer": "",
      "Direction": 0,
      "Streams": [
        {
          "Protocol": "/ipfs/kad/1.0.0"
        }
      ],
      "Identify": {
        "ID": "12D3KooWNCogGjemMiMjZmDxyVcrjP3KW7VFdSPTTGousXEhczuq",
        "PublicKey": "CAESILgL3TiUmYeBy46Uzp0XZxwP4fcFVTIoX6ncvEr+hKSU",
        "Addresses": [
          "/ip4/127.0.0.1/tcp/4001/p2p/12D3KooWNCogGjemMiMjZmDxyVcrjP3KW7VFdSPTTGousXEhczuq",
          "/ip4/127.0.0.1/udp/4001/quic/p2p/12D3KooWNCogGjemMiMjZmDxyVcrjP3KW7VFdSPTTGousXEhczuq",
          "/ip4/172.17.0.2/tcp/4001/p2p/12D3KooWNCogGjemMiMjZmDxyVcrjP3KW7VFdSPTTGousXEhczuq",
          "/ip4/172.17.0.2/udp/4001/quic/p2p/12D3KooWNCogGjemMiMjZmDxyVcrjP3KW7VFdSPTTGousXEhczuq",
          "/ip4/95.208.80.171/tcp/4001/p2p/12D3KooWNCogGjemMiMjZmDxyVcrjP3KW7VFdSPTTGousXEhczuq",
          "/ip4/95.208.80.171/udp/4001/quic/p2p/12D3KooWNCogGjemMiMjZmDxyVcrjP3KW7VFdSPTTGousXEhczuq",
          "/ip6/::1/tcp/4001/p2p/12D3KooWNCogGjemMiMjZmDxyVcrjP3KW7VFdSPTTGousXEhczuq",
          "/ip6/::1/udp/4001/quic/p2p/12D3KooWNCogGjemMiMjZmDxyVcrjP3KW7VFdSPTTGousXEhczuq"
        ],
        "AgentVersion": "go-ipfs/0.8.0/ad14c3932e",
        "ProtocolVersion": "ipfs/0.1.0",
        "Protocols": [
          "/ipfs/bitswap",
          "/ipfs/bitswap/1.0.0",
          "/ipfs/bitswap/1.1.0",
          "/ipfs/bitswap/1.2.0",
          "/ipfs/id/1.0.0",
          "/ipfs/id/push/1.0.0",
          "/ipfs/ping/1.0.0",
          "/libp2p/circuit/relay/0.1.0",
          "/p2p/id/delta/1.0.0",
          "/x/"
        ]
      }
    }
```

If we had `ipfs swarm peers --enc=json  --identify` then we could unblock https://github.com/ipfs/ipfs-webui/issues/2086 and  show it on the Peers screen, and see which nodes is JS-IPFs, Iroh,  Kubo, which one is docker/brave/desktop etc 

Unsure if we are caching `identify` results, if not, we should start doing so, removing the need for executing `identify` protocol lookup for every peer  every time `ipfs swarm peers --enc=json  --identify` is called.

If anyone has bandwidth to do this, feel free to pick it up, and @lidel me for review.

**Comment by arthurgavazza** [comment]
@lidel can I pick this up? any tips on where to start?
