### ISSUE TITLE
Resource Manager: UX and improvements.

### ISSUE THREAD

**Issue by ajnavarro** [ipfs/kubo#9580]
## Description

I identified two main problems that we have to fix on Kubo regarding Resource Manager integration:

### Resource Manager is not backward-compatible

We can say that using Resource Manager is not backward-compatible with protocols that are using libp2p, because they must handle these resource manager errors. We have to fix that on our two main protocols: Bitswap and the DHT:
- https://github.com/libp2p/go-libp2p-kad-dht/issues/806 :
	- Avoid fire and forget actions. Handle all errors and not just log them.
	- Avoid spamming unlimited goroutines on processes.
- https://github.com/ipfs/go-bitswap/issues/599 : 
	- Put limits on requests and responses. Avoid requests of hundred of thousand of CIDs
	- Avoid fire and forget actions.
- https://github.com/libp2p/go-libp2p/issues/2013

### No way from the user side to specify to use all the available resources

We are setting Connections and Streams defaults based on available memory. The number of connections allocated is based on magic numbers and not on real available resources. 

Limiting memory and file descriptors will be easier to understand for the user. Defaults will be always ok, and experienced users can still tweak the Resource Manager configuration to limit by Streams or Connections if they need it. The work needed to make this possible is defined below:
- https://github.com/libp2p/go-libp2p/issues/2010
- https://github.com/ipfs/kubo/issues/9602

### Other improvements

One of the things that are also confusing people is the Resource Manager's name. It is not managing resources, but only counts resources in use by libp2p and other processes that want to use it:
- https://github.com/libp2p/go-libp2p/issues/2011
- https://github.com/libp2p/go-libp2p/pull/2008
- https://github.com/ipfs/kubo/issues/9577
- https://github.com/ipfs/kubo/issues/9603
  - [ ] or at least  https://github.com/ipfs/kubo/issues/9576
- https://github.com/libp2p/go-libp2p/issues/1628
- 
cc @MarcoPolo

**Comment by BigLep** [comment]
In the latest round of consolidating/organizing the resource manager/accountant work, I'm closing this in favor of https://github.com/ipfs/kubo/issues/9650
