### ISSUE TITLE
ipfs key list error on migrated repo

### ISSUE THREAD

**Issue by ThomasFreedman** [ipfs/kubo#9583]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.tech

### Version

```Text
Kubo version: 0.17.0
Repo version: 12
System version: amd64/linux
Golang version: go1.19.1
```

### Config

```json
{
  "API": {
    "HTTPHeaders": {}
  },
  "Addresses": {
    "API": "/ip4/0.0.0.0/tcp/5001",
    "Announce": [
      "/ip4/127.0.0.1/tcp/4001"
    ],
    "Gateway": "/ip4/127.0.0.1/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic"
    ]
  },
  "AutoNAT": {},
  "Bootstrap": [
    "/ip4/173.232.33.58/tcp/4001/p2p/QmXf1pyCfnupeMxnyQKWsGi7z3qdJQbeiePFPCLbvUL9vn",
    "/ip4/127.0.0.1/tcp/4002/p2p/12D3KooWSZFL4eWyufFTTfpXeKRJwkvHUq3LQ223jv6237MA1gmd"
  ],
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "3500GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 10
    }
  },
  "Experimental": {
    "FilestoreEnabled": false,
    "GraphsyncEnabled": false,
    "Libp2pStreamMounting": false,
    "P2pHttpProxy": false,
    "ShardingEnabled": false,
    "StrategicProviding": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": false,
    "PathPrefixes": [],
    "PublicGateways": null,
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "QmXZkyBfxjE4uT2iDk5bSwBNZTN7U5TXZeLrGutP2GN2Zb"
  },
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Peering": {},
  "Pinning": {},
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {
    "Interval": "12h",
    "Strategy": "all"
  },
  "Routing": {
    "Type": "none"
  },
  "Swarm": {
    "AddrFilters": [],
    "ConnMgr": {},
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": true,
    "RelayClient": {},
    "RelayService": {},
    "ResourceMgr": {},
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  }
}
```

### Description

Until today this server ran the most recent version of kubo, 17.

It was suggested by @stebalien to file a bug report.

After migrating one of my larger IPFS servers from an earlier version (I believe from ipfs 0.80.0) I was unable to list keys with `ipfs key list` although I could add them, which produced a file in the .ipfs/keystore folder. The error produced was:
`Error: proto: wrong wireType = 2 for field Type`

There were 35 old files in that folder dating back to the server's installation, the other 2 were files generated by `ipfs key gen` recently.

I downloaded the most recent version of kubo source and grepped it with `grep -eiR "wire\|proto\:\|wrong" *` which returned only 94 hits, none with “wireType”.

I renamed the folder and created a new empty one which eliminated the error.

**Comment by guseggert** [comment]
This sounds like it could be an issue in libp2p since it recently switched protobuf implementations.

One way to debug this is for you to do a "bisect" on your key with previous Kubo versions to isolate the exact version where this breaks. Could you also give us more info about the key, like its type?

**Comment by ThomasFreedman** [comment]
I'm OK with closing this. I reported the issue here and on 9600 in hopes it would be useful info for bug hunting. It appears to be a permissions issue (see 9600 for steps to trigger errant behavior).

I found a workaround, which was to only use this command from the same account as the ipfs daemon runs under.
