### ISSUE TITLE
Disable the build tests for PRs to any markdown files in the repo. 

### ISSUE THREAD

**Issue by ElPaisano** [ipfs/kubo#9592]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

# Suggestion

Disable the build tests for PRs to any markdown files in the repo. Per discussion with @lidel, these are not necessary for any changes to `.md` files

# How does this help?
- Resource-saving i.e. build tests aren't running necessarily
- Makes contribution to `kubo\docs` and other `.md`files easier

**Comment by ElPaisano** [comment]
@lidel per our conversation, tagging you on this issue

**Comment by lidel** [comment]
Thanks!  @galargh thoughts?
