### ISSUE TITLE
Resource Manager: Remove `ResourceMgr.Limits` configuration from Kubo and use the default libp2p JSON file for it

### ISSUE THREAD

**Issue by ajnavarro** [ipfs/kubo#9603]
Resource Manager config is really useful when you want to configure every aspect of your kubo node, but it is very complex for the average user. 

We should remove `.Limits` field from our configuration, only allowing us to change MaxMemory and MaxFileDescriptors as configurable parameters for RM. 

If some experienced user wants to modify any RM low-level parameter, they can still do it by creating a `limits.json` file near by kubo config that will be read using default libp2p functions: 

https://github.com/libp2p/go-libp2p/blob/97607949208fc95bea759eeaa88db3ad2c86bf38/p2p/host/resource-manager/limit.go#L59

We also need to make a decision on how we handle legacy `Swarm.ResourceMgr.Limits` configuration.

**Comment by markg85** [comment]
I'm not sure if this is the right thing todo.
We do still have this famous issue: https://github.com/ipfs/kubo/issues/3320 which can potentially be mitigated using those limits.

Yes yes, i agree, fiddling with limits is a workaround for that issue. But it's probably the only actually usable workaround when you face that issue as long as the core problem causing said issue isn't resolved [1].

[1] As far as i know, we still don't know what exactly causes it and how to fix it for real. There are some hints here and there but nothing seems to be a true solution.

**Comment by BigLep** [comment]
On the topic of `Swarm.ResourceMgr.Limits` configuration, my initial vote is that we don't migrate it and use this as an opportunity to have users reset and figure out what they actually need.

**Comment by lidel** [comment]
+1 – no migration, most users won't have it, but if someone set custom limits, we should error after update to new Kubo, asking them to remove `Swarm.ResourceMgr.Limits` from config, and try defaults (and if the need custom limits, link to go-libp2p docs around `limits.json`)
