### ISSUE TITLE
expected chan in accept muxer

### ISSUE THREAD

**Issue by hsn10** [ipfs/kubo#9625]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.tech

### Version

```Text
0.18.0 amd64/win
```

### Config

```json
private
```

### Description

panic: **expected chan in accept muxer**
```
goroutine 309 [running]:
github.com/libp2p/go-libp2p/p2p/transport/quic.(*acceptLoopRunner).RmAcceptForVersion(0xc00073b0c8, 0x4dfbe50?)
        github.com/libp2p/go-libp2p@v0.24.2/p2p/transport/quic/virtuallistener.go:72 +0x14a
github.com/libp2p/go-libp2p/p2p/transport/quic.(*virtualListener).Close(0xc00070b980)
        github.com/libp2p/go-libp2p@v0.24.2/p2p/transport/quic/virtuallistener.go:32 +0x28
github.com/libp2p/go-libp2p/p2p/net/swarm.(*Swarm).AddListenAddr.func2.1()
        github.com/libp2p/go-libp2p@v0.24.2/p2p/net/swarm/swarm_listen.go:117 +0x14e
github.com/libp2p/go-libp2p/p2p/net/swarm.(*Swarm).AddListenAddr.func2()
        github.com/libp2p/go-libp2p@v0.24.2/p2p/net/swarm/swarm_listen.go:130 +0x3a4
created by github.com/libp2p/go-libp2p/p2p/net/swarm.(*Swarm).AddListenAddr
        github.com/libp2p/go-libp2p@v0.24.2/p2p/net/swarm/swarm_listen.go:106 +0x271
```

**Comment by Jorropo** [comment]
@hsn10 any details please ? Are you doing anything ? Help to reproduce ? How often does that happen ?

**Comment by marten-seemann** [comment]
@hsn10 Why did you close this issue?

**Comment by hsn10** [comment]
I forgot that I can't unsubscribe from tracker emails at github.

**Comment by marten-seemann** [comment]
I don’t understand. Is this a bug in Kubo or not? Do we need to investigate this or not?

**Comment by hsn10** [comment]
Investigate in different ticket, so my email is not spammed. It crashes quite often, just wait until somebody else will report it.

**Comment by RadioSteve-dev** [comment]
I can confirm this behavior on Windows Server 2019. The daemon runs some hours well, and then "panics".

**Comment by RadioSteve-dev** [comment]
ipfs : panic: expected chan in accept muxer
At line:1 char:1
+ ipfs daemon
+ ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (panic: expected chan in accept muxer:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
goroutine 392 [running]:
github.com/libp2p/go-libp2p/p2p/transport/quic.(*acceptLoopRunner).RmAcceptForVersion(0xc0022b3818, 0x16d1fe50?)
	github.com/libp2p/go-libp2p@v0.24.2/p2p/transport/quic/virtuallistener.go:72 +0x14a
github.com/libp2p/go-libp2p/p2p/transport/quic.(*virtualListener).Close(0xc0022a6b00)
	github.com/libp2p/go-libp2p@v0.24.2/p2p/transport/quic/virtuallistener.go:32 +0x28
github.com/libp2p/go-libp2p/p2p/net/swarm.(*Swarm).AddListenAddr.func2.1()
	github.com/libp2p/go-libp2p@v0.24.2/p2p/net/swarm/swarm_listen.go:117 +0x14e
github.com/libp2p/go-libp2p/p2p/net/swarm.(*Swarm).AddListenAddr.func2()
	github.com/libp2p/go-libp2p@v0.24.2/p2p/net/swarm/swarm_listen.go:130 +0x3a4
created by github.com/libp2p/go-libp2p/p2p/net/swarm.(*Swarm).AddListenAddr
	github.com/libp2p/go-libp2p@v0.24.2/p2p/net/swarm/swarm_listen.go:106 +0x271

**Comment by RadioSteve-dev** [comment]
It happens now on the second Windows Server too. The first was Windows Server 2019, the second 2022.

**Comment by WeAreLegion999** [comment]
any fix for this? i have limited the memorysize and it started happening.... running in w10 wsl2
