### ISSUE TITLE
sharness - t0118 is broken - response for application/vnd.ipld.car SHOULD NOT include Content-Length

### ISSUE THREAD

**Issue by laurentsenta** [ipfs/kubo#9651]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.tech

### Version

```Text
Kubo version: 0.18.1
Repo version: 13
System version: arm64/darwin
Golang version: go1.19.1
```

### Description

In sharness t0118 it seems that the test is misusing the invert option in grep:

https://github.com/ipfs/kubo/blob/ed4d6b7d4187512ede4aeb19188a383d9aa55d45/test/sharness/t0118-gateway-car.sh#L93-L96

The comment says that we should NOT return a `Content-Length`, but we do:

```
› cat curl_output | grep Content-Length                                                                                                                        ☹
< Access-Control-Expose-Headers: Content-Length
< Content-Length: 127
```

(tested with Kubo and a car gateway from [go-libipfs](https://github.com/ipfs/go-libipfs/tree/main/examples/gateway/car))

Changing the test to : `! grep "< Content-Length:" curl_output` reveals the error.

I found a few other cases where we use `grep -v` and that might have a similar issue:

```
> ack 'grep.*-v' ./ - | pbcopy
t0119-prometheus.sh
t0250-files-api.sh
t0140-swarm.sh
t0060-daemon.sh
t0080-repo.sh
t0230-channel-streaming-http-content-type.sh
t0141-addfilter.sh
t0046-id-hash.sh
```

**Comment by lidel** [comment]
Thanks for catching this. 
As we've discussed during 1:1
-  we should not have this header because we don't know how long CAR stream will be
- there is some dance given gateway code for this lives now in https://github.com/ipfs/go-libipfs/blob/main/gateway/handler_car.go, but as long you open a PR in Kubo that passes sharness it will be ok

**Comment by BigLep** [comment]
This will get handled by https://github.com/ipfs/go-libipfs/pull/177 which is blocked.

**Comment by laurentsenta** [comment]
Discussion also happening in https://github.com/ipfs/gateway-conformance/pull/64

**Comment by lidel** [comment]
I believe this got resolved and can be closed:

- `test/sharness/t0118-gateway-car.sh` was removed  by #9914 
-  gateway-conformance no longer makes any assertions about this header (https://github.com/ipfs/gateway-conformance/pull/64#pullrequestreview-1550549245)
- [gateway specs](https://specs.ipfs.tech/http-gateways/) say nothing about `Content-Length` being incorrect. It is ok, as long it matches the response body size.
   - `Content-Length` can be returned when gateway knows the total size, and in golang (boxo/kubo) it may happen when a small DAG is flushed to the response writer
