### ISSUE TITLE
Support redirecting when `ipfs` subdomain is already present in Host.

### ISSUE THREAD

**Issue by MicahZoltu** [ipfs/kubo#9658]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

I have an IPFS server hosted at `ipfs.example.com`.  I also have `*.ipfs.example.com` setup to point at the same server and TLS configured for both.  The root domain (`example.com`) is hosting a different server.

I would like to be able to make it so `ipfs.example.com/ipfs/bafy...` redirects to `bafy....ipfs.example.com`.

If I setup my gateway like this, it will not redirect when I navigate to `ipfs.example.com/ipfs/bafy...`:
```json
"example.com": {
	"NoDNSLink": false,
	"Paths": [ "/ipfs", "/ipns" ],
	"UseSubdomains": true
},
```
If I setup my gateway like this, it will incorrectly redirect to `bafy....ipfs.ipfs.example.com` (note the double `ipfs` subdomain):
```json
"ipfs.example.com": {
	"NoDNSLink": false,
	"Paths": [ "/ipfs", "/ipns" ],
	"UseSubdomains": true
},
```
I initially expected the first configuration to work.  I was advised to try the second which resulted in unexpected behavior as well.  I am open to some third kubo configuration option that supports redirects without adding an extra `ipfs.` subdomain.

Note: I'm aware that I can work around this with a reverse proxy like nginx or traefik, but I feel like this setup is something that is reasonable to work out-of-the-box with Kubo.

**Comment by lidel** [comment]
Thank you for filling this. 

We triaged it, and it is a custom edge case that we don't plan to support, as the configuration is already way to complex for this.
There may be a way to get what you want with `X-Forwarded-Host` – see "Potential workaround with Nginx and X-Forwarded-Host" at the end.

> The root domain (example.com) is hosting a different server.

Unless you run with custom denylists or access control, It is a very bad idea to run public gateway on a domain name that you use for other purposes.

Ref. https://nft.storage/blog/post/2022-04-29-gateways-and-gatekeepers/

This is why we have https://ipfs.tech on different domain than https://ipfs.io path gateway or https://dweb.link subdomain one.

> I would like to be able to make it so `ipfs.example.com/ipfs/bafy...` redirects to `bafy....ipfs.example.com`.
> [..] it will incorrectly redirect to bafy....ipfs.ipfs.example.com (note the double ipfs subdomain):

Yes, duplicated `ipfs.ipfs` looks weird, but it is your it was your choice to reuse that domain name, and as noted before, it is an antipattern (should use separate domain for gateway purposes to avoid problems).

The double `ipfs.ipfs` is not a matter of aesthetics.  The Origin that does the redirect becomes parent of the subdomain gateway. This convention is used by various tools like IPFS Companion, Brave, Opera etc.

Ref.
- https://docs.ipfs.tech/how-to/address-ipfs-on-web/#subdomain-gateway
- https://www.npmjs.com/package/is-ipfs#subdomains

### Potential workaround with Nginx and X-Forwarded-Host

If you really, really want to redirect to a different parent Origin, you could do it with `X-Forwarded-Host`:
- set up subdomain gateways on both `example.com` and `ipfs.example.com`
- pass custom `X-Forwarded-Host: example.com`  as noted in [the public subdomain gateway recipe](https://github.com/ipfs/kubo/blob/master/docs/config.md#gateway-recipes), so when request arrives for `ipfs.example.com/ipfs/cid` it will get redirected to `cid.ipfs.example.com` and you won't have duplicated `ipfs.ipfs`


Hope this helps.

**Comment by MysticRyuujin** [comment]
Is there any chance you guys can share an nginx config that would work with this? I've been trying for a bit and can't figure it out.

I don't know why this is an anti-patern, especially if it's not a "public" gateway but instead it's a private gateway, eg. on a LAN, in a corporate environment, etc.

It seems silly to have to reserve an entire domain to be able to run a gateway...

**Comment by Jorropo** [comment]
@MysticRyuujin I'm not an nginx wizard so I can't help you on this.

But you don't have to reserve a full domain, a subdomain can be used for a gateway no problem, it just must not be one of the reserved `ipfs`, `ipns` or `ipld` (maybe `ipld` is fine I'm not sure). :slightly_smiling_face: 

So you can do `gateway.somedomain.com` with a star record `*.gateway.somedomain.com` and then register `gateway.somedomain.com` in your Kubo config and it should work, if it does not that a bug and please open a new issue.

**Comment by MysticRyuujin** [comment]
Damn, that's a wonderful idea, and I'm embarrassed that I didn't think of it lol

I just did gateway.my.network and created the certs, etc. and Brave accepted it :rofl:
