### ISSUE TITLE
Remove Writable Gateway

### ISSUE THREAD

**Issue by hacdias** [ipfs/kubo#9738]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

We deprecated the writable gateway in 0.19.0 (#9622). I'm creating this issue to track its complete removal so we have less code to maintain and less sources of possible bugs. I vote on removing it in 0.20. It's a relative simple removal. Wdyt? @ipfs/kubo-maintainers

**Comment by lidel** [comment]
I don't know if it makes sense to remove it:
 it will break existing users without giving them a better replacement any time soon.

It was marked as deprecated to set expectations, so people don't build new things on it while we work on https://github.com/ipfs/specs/issues/375.  The plan is to improve onboarding data over HTTP POST, make it useful beyond flat files, support JSON/CBOR,  blocks and CARs. Create IPIP spec for it, and replace the legacy writable gateway with better/more comprehensive API

Unfortunately, boxo and the Project Rhea happened, and our timelines/roadmaps changed again and again, but the rationale for https://github.com/ipfs/specs/issues/375 is still valid, and I believe we want to get back to it once we are done with Rhea.
 
If we want to remove something, probably better to spend time on [removing `/api/v0/pubsub`](https://github.com/ipfs/kubo/issues/9717) instead.
