### ISSUE TITLE
Gateway support for signed IPNS records doesn't work with raw base58 PeerIDs

### ISSUE THREAD

**Issue by 2color** [ipfs/kubo#9749]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

ipfs-desktop

### Version

```Text
Kubo version: 0.19.0-196321958
Repo version: 13
System version: arm64/darwin
Golang version: go1.20.2
```

### Description

[Kubo 0.19](https://github.com/ipfs/kubo/releases/tag/v0.19.0) add Gateway support for returning signed (verifiable) IPNS records. 

However, from initial testing, this only works for CID encodings of IPNS names (base32 and base36) but not with the raw base58 multihash.

- ✅ base32 CID: https://ipfs.io/ipns/bafzaajaiaejcbzdibmxyzdjbbehgvizh6g5tikvy47mshdy6gwbruvgwvd24seje?format=ipns-record 
- ✅ base36 CID: https://ipfs.io/ipns/k51qzi5uqu5dlvj2baxnqndepeb86cbk3ng7n3i46uzyxzyqj2xjonzllnv0v8?format=ipns-record
- ❌ raw base58 multihash (b58mh) https://ipfs.io/ipns/12D3KooWRBy97UB99e3J6hiPesre1MZeuNQvfan4gBziswrRJsNK This one fails with the error: "selected encoding not supported"

This is strange since all those URLs work without the `?format=ipns-record`.

## Suggestions

- Consider adding support for raw base58 multihash IPNS names. Given that this is always scoped to `/ipns/[ipns_name], there shouldn't be too much ambiguity
- Improve the error to be more specific, e.g. `selected encoding of the IPNS name not supported. Try passing an IPNS name encoded as a base32 or base36 CID.`
- Update the [IPFS HTTP Gateway spec](https://github.com/ipfs/specs/blob/main/http-gateways/PATH_GATEWAY.md#get-ipnsnamepathparams) to include the supported encodings for IPNS names.

**Comment by lidel** [comment]
Thank you for filling this! 

- We do not want to introduce concept of PeerIDs into Gateway specs, but at the same time I agree UX is a priority – Kubo should support b58mh here for consistency.

- My proposal would be to eliminate raw PeerIDs `b58mh` from gateway URLs, so they are never present in address bars, and are not copied around.
  - How? Make Kubo (boxo/gateway) detect `/ipns/b58mh` and return 302 to the same URL but with `b58mh` replaced with base36 CID version (consistent with the output of `ipfs name publish` etc)
