### ISSUE TITLE
error: selector 'ipfs' matches no derivations

### ISSUE THREAD

**Issue by kenorb** [ipfs/kubo#9752]
### Checklist

- [X] I am reporting a documentation issue in this repo, not https://docs.ipfs.tech.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Location

README.md

### Description

I'm following README's method of installing ipfs via nix: `nix-env -i ipfs`.

```
$ nix-env -i ipfs
error: selector 'ipfs' matches no derivations, maybe you meant:
       ipfs-cluster
       ipfs-upload-client
```

This is on Ubuntu 22.04.

I think steps should be updated.

**Comment by Jorropo** [comment]
I'm surprised https://github.com/NixOS/nixpkgs/blob/207f6b2f0e260a0b21b9c25a1109faa95e6fd738/pkgs/top-level/aliases.nix#L733 anyway thx for reporting I have submited a fix. :slightly_smiling_face: 
I would appreciate if you could try #9887's instructions and tell if it's correct, thx
