### ISSUE TITLE
`ipfs dag stat` should accept multiple CIDs and show deduplication ratio

### ISSUE THREAD

**Issue by Jorropo** [ipfs/kubo#9762]
It is a commun ask to calculate deduplication ratio of many CIDs.

This would be easy to do if done like this:
```go
$ ipfs dag stat Qmfoo Qmbar
Size: 21465226420, NumBlocks: 85369, SizeDedup: 1.5, NumBlocksDedup: 1.01
```

**Comment by arthurgavazza** [comment]
@Jorropo can I pick this up? I don't know where to start, but I'm looking for some other issues to work on and really wanna help

**Comment by Jorropo** [comment]
@arthurgavazza I would appreciate you picking this up.

So if you look at [`core/commands/dag/stat.go`](https://github.com/ipfs/kubo/blob/9fb09dd398c21b36a33a743433a550ecf6442c54/core/commands/dag/stat.go#L25-L60)

It has this logic:
```go
	rp, err := api.ResolvePath(req.Context, path.New(req.Arguments[0]))
	if err != nil {
		return err
	}

	if len(rp.Remainder()) > 0 {
		return fmt.Errorf("cannot return size for anything other than a DAG with a root CID")
	}

	nodeGetter := mdag.NewSession(req.Context, api.Dag())
	obj, err := nodeGetter.Get(req.Context, rp.Cid())
	if err != nil {
		return err
	}

	dagstats := &DagStat{}
	err = traverse.Traverse(obj, traverse.Options{
		DAG:   nodeGetter,
		Order: traverse.DFSPre,
		Func: func(current traverse.State) error {
			dagstats.Size += uint64(len(current.Node.RawData()))
			dagstats.NumBlocks++

			if progressive {
				if err := res.Emit(dagstats); err != nil {
					return err
				}
			}
			return nil
		},
		ErrFunc:        nil,
		SkipDuplicates: true,
	})
	if err != nil {
		return fmt.Errorf("error traversing DAG: %w", err)
	}
```

The minimal way to implement this is to wrap that in a `for _, a := range req.Arguments` loop.
`traverse.Traverse` is doing the heavy lifting here, it traverse recursively the data and will call you back for each block discovered.

You will need some map (such as `cid.Set`) to keep track of blocks you have discovered in other traversals already and now that I think about it an output similar to `btrfs fi du` but with deduplication data is more intresting.

An output like this would be good (made up numbers), with a JSON encoder that is machine parseable (and keep the json backward compatible, so no moving or deleting of existing fields), this is somewhat TSV, you can encode this easily with the std csv encoder:
```
CID		Blocks	Size
Qmfoo	456		1234564
Qmbar	1200	2234564

Summary	Unique Blocks 1024	Total Size 2534564	Ratio 1.36x
```
Total size only counts blocks once, even if they are seen multiple times across multiple CIDs.
`Ratio` is computed by summing the size of all the CIDs and dividing by the total size.

Bonus points:
1. You execute the multiple traversals in parallel of one an other.
2. You add computation of internal compression ratios too (that means CIDs that share blocks with themselves multiple times).
3. You optimize the code by caching results of the traversal at any point to only traverse blocks once, even if they are duplicated across the different CIDs (***hard***).
4. You compute a result in a single pass (***medium*** if done alone, ***very hard*** if combined with 1 and 3).

**Comment by arthurgavazza** [comment]
Thx for the detailed explanation! I'll start working on it tomorrow

**Comment by arthurgavazza** [comment]
@Jorropo I'm working on it now. Currently the command only accepts one cid right? I saw this validation : 
`if len(rp.Remainder()) > 0 {
		return fmt.Errorf("cannot return size for anything other than a DAG with a root CID")
	}`
since now we're gonna handle multiple cid's should I return an error if any of the cid's fails the validation?

**Comment by Jorropo** [comment]
@arthurgavazza sounds fair to me, I expect peoples to only input "pure" CIDs in this in the first place.
