### ISSUE TITLE
Is enable-namesys-pubsub going away too?

### ISSUE THREAD

**Issue by kallisti5** [ipfs/kubo#9795]
### Checklist

- [X] I am reporting a documentation issue in this repo, not https://docs.ipfs.tech.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Location

https://github.com/ipfs/kubo/releases/tag/v0.19.1

### Description

The 0.19.1 release documents getting rid of pubsub... however doesn't mention if enable-namesys-pubsub is impacted.
enable-namesys-pubsub greatly increases the resolution time of ipns keys... it would be a shame if it went away.

**Comment by Jorropo** [comment]
No :slightly_smiling_face:
