### ISSUE TITLE
Kubo writes to stdout when used as a library

### ISSUE THREAD

**Issue by rossjones** [ipfs/kubo#9802]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

built from source

### Version

```Text
github.com/ipfs/kubo v0.18.2-0.20230214211946-0ff406170dd9
```

### Description

When using Kubo as a library, the code at https://github.com/ipfs/kubo/blob/1958510b3e7b796b17cee27fa3424d7310905eae/core/node/libp2p/rcmgr.go#L65-L66 prints to the following to stdout and it isn't really appropriate or useful to our users.

```
Computed default go-libp2p Resource Manager limits based on:
    - 'Swarm.ResourceMgr.MaxMemory': "13 GB"
    - 'Swarm.ResourceMgr.MaxFileDescriptors': 46080

Theses can be inspected with 'ipfs swarm resources'.
```

Happy to send a PR to change it to a log message unless there's a useful way to determine that it is running as a binary and that writing to stdout makes sense then.

**Comment by lidel** [comment]
This was closed in https://github.com/ipfs/kubo/pull/9922, and shipped in Kubo 0.21.0-rc1:
