### ISSUE TITLE
HTTP Router only uses Addresses.Swarm

### ISSUE THREAD

**Issue by jtsmedley** [ipfs/kubo#9823]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.tech

### Version

```Text
Kubo version: 0.19.1-958e586
Repo version: 13
System version: amd64/linux
Golang version: go1.19.1
```

### Config

```json
{
  "API": {
    "HTTPHeaders": {}
  },
  "Addresses": {
    "API": "/ip4/0.0.0.0/tcp/5001",
    "Announce": [
      "/ip4/[PUBLIC_IP]/tcp/4001"
    ],
    "AppendAnnounce": [],
    "Gateway": "/ip4/0.0.0.0/tcp/8080",
    "NoAnnounce": [
      "/ip4/10.0.0.0/ipcidr/8",
      "/ip4/100.64.0.0/ipcidr/10",
      "/ip4/169.254.0.0/ipcidr/16",
      "/ip4/172.16.0.0/ipcidr/12",
      "/ip4/192.0.0.0/ipcidr/24",
      "/ip4/192.0.2.0/ipcidr/24",
      "/ip4/192.168.0.0/ipcidr/16",
      "/ip4/198.18.0.0/ipcidr/15",
      "/ip4/198.51.100.0/ipcidr/24",
      "/ip4/203.0.113.0/ipcidr/24",
      "/ip4/240.0.0.0/ipcidr/4",
      "/ip6/100::/ipcidr/64",
      "/ip6/2001:2::/ipcidr/48",
      "/ip6/2001:db8::/ipcidr/32",
      "/ip6/fc00::/ipcidr/7",
      "/ip6/fe80::/ipcidr/10"
    ],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001"
    ]
  },
  "AutoNAT": {
    "ServiceMode": "disabled"
  },
  "Bootstrap": [
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt"
  ],
  "DNS": {
    "Resolvers": {}
  },
  "Datastore": {
    "BloomFilterSize": 268435456,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/3",
            "sync": false,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "50GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": false
    }
  },
  "Experimental": {
    "AcceleratedDHTClient": true,
    "FilestoreEnabled": false,
    "GraphsyncEnabled": false,
    "Libp2pStreamMounting": false,
    "P2pHttpProxy": false,
    "StrategicProviding": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": true,
    "PathPrefixes": [],
    "PublicGateways": null,
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "[PEER_ID]"
  },
  "Internal": {
    "Bitswap": {
      "EngineBlockstoreWorkerCount": 1250,
      "EngineTaskWorkerCount": 250,
      "MaxOutstandingBytesPerPeer": 1048576,
      "TaskWorkerCount": 250
    }
  },
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Migration": {
    "DownloadSources": [],
    "Keep": ""
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Peering": {
    "Peers": null
  },
  "Pinning": {
    "RemoteServices": {}
  },
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {
    "Interval": "12h",
    "Strategy": "pinned"
  },
  "Routing": {
    "Methods": {
      "find-peers": {
        "RouterName": "WanDHT"
      },
      "find-providers": {
        "RouterName": "ParallelHelper"
      },
      "get-ipns": {
        "RouterName": "WanDHT"
      },
      "provide": {
        "RouterName": "ParallelHelper"
      },
      "put-ipns": {
        "RouterName": "WanDHT"
      }
    },
    "Routers": {
      "HttpIndexer": {
        "Parameters": {
          "Endpoint": "[MOCKING_ENDPOINT]"
        },
        "Type": "http"
      },
      "ParallelHelper": {
        "Parameters": {
          "Routers": [
            {
              "IgnoreErrors": true,
              "RouterName": "HttpIndexer",
              "Timeout": "3m"
            },
            {
              "ExecuteAfter": "2s",
              "IgnoreErrors": false,
              "RouterName": "WanDHT",
              "Timeout": "30m"
            }
          ]
        },
        "Type": "parallel"
      },
      "WanDHT": {
        "Parameters": {
          "AcceleratedDHTClient": true,
          "Mode": "dhtserver",
          "PublicIPNetwork": true
        },
        "Type": "dht"
      }
    },
    "Type": "custom"
  },
  "Swarm": {
    "AddrFilters": [
      "/ip4/100.64.0.0/ipcidr/10",
      "/ip4/169.254.0.0/ipcidr/16",
      "/ip4/172.16.0.0/ipcidr/12",
      "/ip4/192.0.0.0/ipcidr/24",
      "/ip4/192.0.2.0/ipcidr/24",
      "/ip4/192.168.0.0/ipcidr/16",
      "/ip4/198.18.0.0/ipcidr/15",
      "/ip4/198.51.100.0/ipcidr/24",
      "/ip4/203.0.113.0/ipcidr/24",
      "/ip4/240.0.0.0/ipcidr/4",
      "/ip6/100::/ipcidr/64",
      "/ip6/2001:2::/ipcidr/48",
      "/ip6/2001:db8::/ipcidr/32",
      "/ip6/fc00::/ipcidr/7",
      "/ip6/fe80::/ipcidr/10"
    ],
    "ConnMgr": {
      "HighWater": 1200
    },
    "DisableBandwidthMetrics": true,
    "DisableNatPortMap": true,
    "RelayClient": {
      "Enabled": true
    },
    "RelayService": {
      "Enabled": false
    },
    "ResourceMgr": {},
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  }
}
```

### Description

When using an HTTP router Kubo uses the config information from `.Addresses.Swarm` rather than addresses parsed from `.Addresses.Announce` which is what is consistently used for DHT announcements.

Possible Affected Code: https://github.com/ipfs/kubo/blob/master/routing/delegated.go#L202

--- HTTP Routing Payload [Actual]
`{
  "Providers": [
    {
      "Protocol": "transport-bitswap",
      "Schema": "bitswap",
      "Signature": "mglKVuUbSEZ45gQRS1is1CHhHQY7B1c+Zu39jXUM1zG4JNJyDczHgKpdNMZ7meFccy8MrIlXfReudSz3vD6+BCg",
      "Payload": {
        "Keys": [
          "[CONTENT_ID]"
        ],
        "Timestamp": 1681748062739,
        "AdvisoryTTL": 86400000000000,
        "ID": "[KUBO_ID]",
        "Addrs": [
          "/ip4/0.0.0.0/tcp/4001"
        ]
      }
    }
  ]
}`

--- HTTP Routing Payload [Expected]
`{
  "Providers": [
    {
      "Protocol": "transport-bitswap",
      "Schema": "bitswap",
      "Signature": "mglKVuUbSEZ45gQRS1is1CHhHQY7B1c+Zu39jXUM1zG4JNJyDczHgKpdNMZ7meFccy8MrIlXfReudSz3vD6+BCg",
      "Payload": {
        "Keys": [
          "[CONTENT_ID]"
        ],
        "Timestamp": 1681748062739,
        "AdvisoryTTL": 86400000000000,
        "ID": "[KUBO_ID]",
        "Addrs": [
          "/ip4/[PUBLIC_IP]/tcp/4001"
        ]
      }
    }
  ]
}`

**Comment by aschmahmann** [comment]
@jtsmedley where Routing v1 HTTP endpoint are you using? Are you trying to put provider records over HTTP or only receive them?

**Comment by jtsmedley** [comment]
@aschmahmann This issue occurs is related to publishing provider records over HTTP from Kubo.  The Routing  v1 HTTP request that is emitted by Kubo contains a list of addresses that is different than the list of addresses being published by the DHT publisher.

**Comment by lidel** [comment]
@jtsmedley  afaik PUTs to `/routing/v1` are not officially supported and experimental impl. may break at any time.

The fix for this needs to wait until [IPIP-378](https://github.com/ipfs/specs/pull/378) is finalized and implemented in [boxo/routing/http](https://github.com/ipfs/boxo/tree/main/routing/http), unless you have time to debug and submit a PR with surgical fix.

**Comment by jtsmedley** [comment]
@lidel To be clear this issue is with Kubo Delegated Routing posting to Index-Provider. This is not an issue with posting into Kubo.  I consider Kubo's IPNI put implementation to currently be broken and cannot use it.

**Comment by lidel** [comment]
Correct, you can't use it:  PUT to `/routing/v1` was never officially supported  anywhere, and it is still the case. 
There is no stable API/spec, no tests, no support.

- cid.contact does not accept PUTs (https://github.com/ipfs/kubo/issues/9504) and PUTs there are disabled in  Kubo client (`Routing.Type=auto`)
- Kubo does not expose `/routing/v1` yet, and TBD if we even support PUT in the MVP  (https://github.com/ipfs/kubo/pull/9877/)

We've just started working towards making `/routing/v1` useful beyond basic GET from cid.contact, and we will focus on exposing GET in Kubo first. PUT is planned, but after we have basic GET working reliably, as it serves more use cases.

@jtsmedley  It sounds like you are using experimental PUT code against your own endpoint, and it happens to work  aside from the `Announce` bug reported here.   I guess that is good news, but also a source of confusion on our end.

Why were you under impression PUTs are supported? 
Is it because of example in [/docs/config.md#routing-methods](https://github.com/ipfs/kubo/blob/master/docs/config.md#routing-methods) or some other docs?

**Comment by lidel** [comment]
Thank you, @jtsmedley, this clears a lot of confusion.

Since it was the IPNI project who did not test this, but prompted you to use this before it's ready, you could fill an issue in [ipni/index-provider](https://github.com/ipni/index-provider) and ask them to either provide support and fix bugs, or remove docs until it is safe to recommend.

**Comment by masih** [comment]
> Not sure if the note added in [this PR](https://github.com/ipni/index-provider/pull/373/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R142) is enough for your users.

Cc @ischasny

**Comment by lidel** [comment]
Triage notes:
- Kubo maintainers will get to this after PUTs in `/routing/v1` is finalized, can't spend time on experimental thing at  this time
- If anyone needs the fix for this sooner, PR welcome :pray:
