### ISSUE TITLE
Add support for GCS datastore

### ISSUE THREAD

**Issue by bjornleffler** [ipfs/kubo#9888]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

I've built a new go-datastore for Google Cloud Storage (GCS), available at:
https://github.com/bjornleffler/go-ds-gcs

I would like to:
1. Add a new config profile to kubo to simplify configuring kubo with the GCS datastore.
2. Merge github.com/bjornleffler/go-ds-gcs as github.com/ipfs/go-ds-gcs

This new feature is code complete, tested and documented.

**Comment by bjornleffler** [comment]
I totally get the maintenance issue, maintaining code is hard. I can figure out some way to do the configuration separately form the main kubo binary. Probably something like this:
https://github.com/ipfs/go-ds-s3#configuration

How do I get my code merge my datastore code as a separate repository, similar to the [S3 datastore repository](https://github.com/ipfs/go-ds-s3)?

**Comment by BigLep** [comment]
@lidel : I reopened so we speak to the question about repository location.

**Comment by bjornleffler** [comment]
Yes, that sounds great. Lets move the repository into the new location. Existing users can migrate.

Apologies for the late reply, I missed the previous notification.

**Comment by lidel** [comment]
@bjornleffler I seem to still lack permissions, maybe Transfer repo to me? I will re-add you after I'm done with moving it it the right place.

> ![2023-06-19_12-14](https://github.com/ipfs/kubo/assets/157609/2ced3350-dd06-426b-bb4e-e9eac8b15be3)
