### ISSUE TITLE
Why is the TSize obtained by ipfs dag different from the size displayed by ipfs desktop

### ISSUE THREAD

**Issue by ss75710541** [ipfs/kubo#9946]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

ipfs-desktop

### Version

```Text
Kubo version: 0.20.0
Repo version: 13
System version: amd64/darwin
Golang version: go1.19.8
```

### Description

![image](https://github.com/ipfs/kubo/assets/5858487/af4e3414-fbab-4852-8151-affce31c1755)

```
# ipfs dag get bafybeibawqusphaqfn7c7b5hsr4wgmxud7qfhnmd2ntco7oqjnvmg5njfa|python -m json.tool

{
    "Data": {
        "/": {
            "bytes": "CAIY+4rtJSCAgOAVIPuKjRA"
        }
    },
    "Links": [
        {
            "Hash": {
                "/": "bafybeif44kxkggwkawybjknxymrqn7tg7z5ib256rphmlagh7v37re7aza"
            },
            "Name": "",
            "Tsize": 45621766
        },
        {
            "Hash": {
                "/": "bafybeihuiy47fvxpa5oillqacv2gqtilq4ar5xjoqed2gik6uju6ym42se"
            },
            "Name": "",
            "Tsize": 33775287
        }
    ]
}
```

![image](https://github.com/ipfs/kubo/assets/5858487/1b844de3-bb32-426d-98d9-b1c8b3bc6da5)

**Comment by Jorropo** [comment]
TSize is not the size of the file:
https://github.com/ipfs/specs/pull/331
>  This is an optional field for Links of `dag-pb` nodes, **it does not represent any meaningfull information of the underlying structure**

**Comment by ss75710541** [comment]
However, this Tsize affects the cid calculation，The cid calculated by go-car is different from the cid calculated by ipfs because of the different Tsize

**Comment by ss75710541** [comment]
same file  go-car cid is bafybeiecchz2dlxyhgdz4v7w3bujemvogkqq6k7wt5rdvihe2fuavfbi4q

```
--- bafybeiecchz2dlxyhgdz4v7w3bujemvogkqq6k7wt5rdvihe2fuavfbi4q
+++ dag-json bafybeiecchz2dlxyhgdz4v7w3bujemvogkqq6k7wt5rdvihe2fuavfbi4q
@@ -0,23 +0,23 @@
{
	"Data": {
		"/": {
			"bytes": "CAIY+4rtJSCAgOAVIPuKjRA"
		}
	},
	"Links": [
		{
			"Hash": {
				"/": "bafybeif44kxkggwkawybjknxymrqn7tg7z5ib256rphmlagh7v37re7aza"
			},
			"Name": "",
			"Tsize": 45613056
		},
		{
			"Hash": {
				"/": "bafybeihuiy47fvxpa5oillqacv2gqtilq4ar5xjoqed2gik6uju6ym42se"
			},
			"Name": "",
			"Tsize": 33768827
		}
	]
}
```

# ipfs dag get bafybeibawqusphaqfn7c7b5hsr4wgmxud7qfhnmd2ntco7oqjnvmg5njfa|python -m json.tool

{
    "Data": {
        "/": {
            "bytes": "CAIY+4rtJSCAgOAVIPuKjRA"
        }
    },
    "Links": [
        {
            "Hash": {
                "/": "bafybeif44kxkggwkawybjknxymrqn7tg7z5ib256rphmlagh7v37re7aza"
            },
            "Name": "",
            "Tsize": 45621766
        },
        {
            "Hash": {
                "/": "bafybeihuiy47fvxpa5oillqacv2gqtilq4ar5xjoqed2gik6uju6ym42se"
            },
            "Name": "",
            "Tsize": 33775287
        }
    ]
}
