### ISSUE TITLE
How to run GC?

### ISSUE THREAD

**Issue by hacdias** [ipfs/kubo#9971]
While working on https://github.com/ipfs/testground/pull/58, I hit myself on a wall: how can we call the Garbage Collector programmatically?

**Comment by lidel** [comment]
`repoGcCmd` does:

https://github.com/ipfs/kubo/blob/8bba03d8bf46b4153e8724767c5098f92d9e363e/core/commands/repo.go#L86

If doing the same is not feasible, consider opening PR that adds it to https://github.com/ipfs/kubo/tree/master/client/rpc
